#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout (binding = 0) uniform VoxelizedInfoUBO
{
	vec4 mapMinVoxelSize;
	vec4 mapMaxWriteOffset;
	vec4 invMapDims;
	vec4 gridSize;
} voxelizedInfo;

layout (binding = 1, rgba16f) uniform readonly image3D srcRadiosityMapPX;
layout (binding = 2, rgba16f) uniform readonly image3D srcRadiosityMapNX;
layout (binding = 3, rgba16f) uniform readonly image3D srcRadiosityMapPY;
layout (binding = 4, rgba16f) uniform readonly image3D srcRadiosityMapNY;
layout (binding = 5, rgba16f) uniform readonly image3D srcRadiosityMapPZ;
layout (binding = 6, rgba16f) uniform readonly image3D srcRadiosityMapNZ;

layout (binding = 7, rgba16f) uniform image3D dstRadiosityMapPX;
layout (binding = 8, rgba16f) uniform image3D dstRadiosityMapNX;
layout (binding = 9, rgba16f) uniform image3D dstRadiosityMapPY;
layout (binding = 10, rgba16f) uniform image3D dstRadiosityMapNY;
layout (binding = 11, rgba16f) uniform image3D dstRadiosityMapPZ;
layout (binding = 12, rgba16f) uniform image3D dstRadiosityMapNZ;

void main()
{
	if ( any(greaterThanEqual(gl_GlobalInvocationID, ivec3 (voxelizedInfo.gridSize.xyz))) ) return ;

	vec4 dstPX = imageLoad (dstRadiosityMapPX, ivec3 (gl_GlobalInvocationID));
	vec4 dstNX = imageLoad (dstRadiosityMapNX, ivec3 (gl_GlobalInvocationID));
	vec4 dstPY = imageLoad (dstRadiosityMapPY, ivec3 (gl_GlobalInvocationID));
	vec4 dstNY = imageLoad (dstRadiosityMapNY, ivec3 (gl_GlobalInvocationID));
	vec4 dstPZ = imageLoad (dstRadiosityMapPZ, ivec3 (gl_GlobalInvocationID));
	vec4 dstNZ = imageLoad (dstRadiosityMapNZ, ivec3 (gl_GlobalInvocationID));

	vec4 srcPX = imageLoad (srcRadiosityMapPX, ivec3 (gl_GlobalInvocationID));
	vec4 srcNX = imageLoad (srcRadiosityMapNX, ivec3 (gl_GlobalInvocationID));
	vec4 srcPY = imageLoad (srcRadiosityMapPY, ivec3 (gl_GlobalInvocationID));
	vec4 srcNY = imageLoad (srcRadiosityMapNY, ivec3 (gl_GlobalInvocationID));
	vec4 srcPZ = imageLoad (srcRadiosityMapPZ, ivec3 (gl_GlobalInvocationID));
	vec4 srcNZ = imageLoad (srcRadiosityMapNZ, ivec3 (gl_GlobalInvocationID));
	
	imageStore (dstRadiosityMapPX, ivec3 (gl_GlobalInvocationID), mix (srcPX, dstPX, 0.7));
	imageStore (dstRadiosityMapNX, ivec3 (gl_GlobalInvocationID), mix (srcNX, dstNX, 0.7));
	imageStore (dstRadiosityMapPY, ivec3 (gl_GlobalInvocationID), mix (srcPY, dstPY, 0.7));
	imageStore (dstRadiosityMapNY, ivec3 (gl_GlobalInvocationID), mix (srcNY, dstNY, 0.7));
	imageStore (dstRadiosityMapPZ, ivec3 (gl_GlobalInvocationID), mix (srcPZ, dstPZ, 0.7));
	imageStore (dstRadiosityMapNZ, ivec3 (gl_GlobalInvocationID), mix (srcNZ, dstNZ, 0.7));
}