#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout (local_size_x = 8, local_size_y = 8, local_size_y = 8) in;
layout (binding = 0, rgba8) uniform readonly image3D diffuseImage;
layout (binding = 1, r8) uniform image3D dfImage;

layout (binding = 2) uniform GridSizeUBO
{
	vec4 gridDims;
	uvec4 startGridCoord;
	uvec4 endGridCoord;
} computeParams;

void main()
{
	if ( gl_GlobalInvocationID.xyz != clamp (gl_GlobalInvocationID.xyz, computeParams.startGridCoord.xyz, computeParams.endGridCoord.xyz) ) return;

	if ( imageLoad(diffuseImage, ivec3(gl_GlobalInvocationID.xyz)).a != 1.0 ) return ;

	for (int n = 0;n != 5;n++)
		for (int i = -n; i != n+1;i++)
			for (int j = -n; j != n+1;j++)
				for (int k = -n; k != n+1;k++)
				{
					if ( all(lessThanEqual (abs (ivec3 (i,j,k)), ivec3 (n-1))) ) continue;
					ivec3 curCoord = ivec3(gl_GlobalInvocationID.xyz) + ivec3 (i,j,k);
					if ( curCoord != clamp (curCoord, ivec3 (0),ivec3 (computeParams.gridDims.xyz)) ) continue;
					if ( int (imageLoad(dfImage, curCoord).r*255.0) > n ) imageStore (dfImage, curCoord, vec4 (float(n)/255.0));
				}
}