#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

#define VOXEL_DIM_SIZE voxelizedInfo.mapMinVoxelSize.w
#define M_PI 3.1415926535

layout (local_size_x = 8, local_size_y = 8, local_size_z = 8) in;

layout (binding = 0) uniform VoxelizedInfoUBO
{
	vec4 mapMinVoxelSize;
	vec4 mapMaxWriteOffset;
	vec4 invMapDims;
	vec4 gridSize;
} voxelizedInfo;

layout (binding = 1, rgba8) uniform readonly image3D sceneVoxelized;
layout (binding = 2) uniform samplerCube skyBox;

layout (binding = 3, rgba16f) uniform image3D radiosityMapPX;
layout (binding = 4, rgba16f) uniform image3D radiosityMapNX;
layout (binding = 5, rgba16f) uniform image3D radiosityMapPY;
layout (binding = 6, rgba16f) uniform image3D radiosityMapNY;
layout (binding = 7, rgba16f) uniform image3D radiosityMapPZ;
layout (binding = 8, rgba16f) uniform image3D radiosityMapNZ;

layout (binding = 9) uniform SkyShadowMapMVPUBO
{
    mat4 projectionViewMatrix;
    vec4 eye;
} SkyShadowMapMVP;

layout (binding = 10) uniform RayleighMieUBO
{
	vec4 lightDir;
	vec4 sunDirAndExp;
	vec4 invW4InnerRad;

	float innerCloudRad;
	float outerRad;
	float scaleDepth;
	float scaleOverScaleDepth;
	
	float scatteringCoeff;
	float extinctionCoeff;
	float ambientCoeff;
	float stepSizeEvalLightDir;

	float stepSizeToSky;
	float numStepsToSky;
	float stepSizeToSun;
	float numStepsToSun;
	
	vec4 addSkyColorAndNightAmount;
	vec4 skyObjectLightAndAngle;
	vec4 horizonColor;
	vec4 approxGroundColor;
} rayleighMieInfo;

layout (binding = 11, r32ui) uniform readonly uimage2D shadowDistance;
layout (binding = 12, rgba8) uniform readonly image2D shadowColor;

vec3 toVec3(vec2 inpVec)
{
	float phi = inpVec.x * (2.0 * M_PI);
	float theta = inpVec.y * M_PI;
	float sinTheta = sin(theta);
	return vec3 (cos(phi) * sinTheta, cos(theta), sin(phi) * sinTheta);
}

mat3 decodeTanBitan (float encodedTanBiTan, vec3 inpNorm)
{
	float encodedVal = round (encodedTanBiTan * 255.0);
	bool biTanDotBasisYNegative = false;
	if ( encodedVal >= 128.0 )
	{
		encodedVal -= 128.0;
		biTanDotBasisYNegative = true;
	}
	bool tanDotBasisYNegative = false;
	if ( encodedVal >= 64.0 )
	{
		encodedVal -= 64.0;
		tanDotBasisYNegative = true;
	}
	float basisXShadow = clamp (((encodedVal / 63.0) * 2.0) - 1.0, -1.0, 1.0);
	float basisYShadow = sqrt (1.0 - basisXShadow*basisXShadow);
	vec3 aBasisX = normalize (cross (inpNorm, inpNorm + vec3 (0.1)));
	vec3 aBasisY = cross (inpNorm,aBasisX);
	vec3 tanVector = basisXShadow * aBasisX;
	if (tanDotBasisYNegative)
		tanVector -= basisYShadow * aBasisY;
	else
		tanVector += basisYShadow * aBasisY;
	tanVector = normalize (tanVector);
	vec3 biTanVector = cross (inpNorm, tanVector);
	if ( dot (biTanVector, aBasisY) > 0.0 && biTanDotBasisYNegative ) biTanVector = -biTanVector;
	mat3 retVal;
	retVal[0] = tanVector;
	retVal[1] = biTanVector;
	retVal[2] = inpNorm;
	return retVal;
}

mat3 getOrthoBasisAndSpec (ivec3 texelLoc, out float specularityOut)
{
	vec4 fetchEncodedBasis = imageLoad(sceneVoxelized,texelLoc);
	specularityOut = fetchEncodedBasis.a;
	vec3 decodedNorm = normalize (toVec3 (fetchEncodedBasis.rg));
	mat3 decodedBasis = decodeTanBitan (fetchEncodedBasis.b, decodedNorm);
	return decodedBasis;
}

vec3 getEmissivityDielectricRefractiveIndexAndRoughness3DImage (ivec3 texelLoc, out bool diElectric, out float IoR)
{
	vec4 rawFetch = imageLoad(sceneVoxelized,texelLoc);
	float pureEmissivity = rawFetch.x * 25.5;
	vec2 fetchedRoughness = rawFetch.zw;
	
	float dielectricRefractiveIndex = rawFetch.y * 255.0;
	if ( dielectricRefractiveIndex >= 128.0 )
	{
		diElectric = true;
		dielectricRefractiveIndex -= 128.0;
	}
	else
		diElectric = false;
		
	IoR = dielectricRefractiveIndex * 0.03149606299212598425196850393701;

	return vec3 (pureEmissivity, fetchedRoughness);
}

vec3 getUVW (vec3 worldPos)
{
	vec3 posUVW = (worldPos - voxelizedInfo.mapMinVoxelSize.xyz) * voxelizedInfo.invMapDims.xyz;
	if ( posUVW != clamp (posUVW, vec3 (0.0), vec3 (0.999999)) ) return vec3 (2.0);
	return posUVW;
}

struct VoxelHitData
{
	vec4 albedo;
	vec4 specular;
	mat3 tangentSpace;

	vec2 roughness;
	float specularity;

	bool diElectric;
	float IoR;
	float emissivity;
};

VoxelHitData getMaterial (vec3 uvwLoc)
{
	VoxelHitData voxHitData;
	voxHitData.albedo = vec4 (0.0);
	voxHitData.specular = vec4 (0.0);
	voxHitData.tangentSpace = mat3(1.0);
	voxHitData.roughness = vec2 (0.0);
	voxHitData.specularity = 0.0;
	voxHitData.diElectric = false;
	voxHitData.IoR = 0.0;
	voxHitData.emissivity = 0.0;
	
	ivec3 texelLoc = ivec3 (uvwLoc * voxelizedInfo.gridSize.xyz);
	texelLoc.x *= 8;

	vec4 diffFetch = imageLoad (sceneVoxelized, texelLoc);
	if ( diffFetch.a == 0.0 )
	{
		texelLoc.x += 4;
		diffFetch = imageLoad (sceneVoxelized, texelLoc);
		if (diffFetch.a == 0.0) return voxHitData;
	}
	
	voxHitData.albedo = diffFetch;
	voxHitData.specular = imageLoad (sceneVoxelized, ivec3 (texelLoc.x + 3, texelLoc.yz));
	
	bool diElectric = false;
	float IoR = 0.0;
	vec3 emissivityAndRoughness = getEmissivityDielectricRefractiveIndexAndRoughness3DImage (ivec3 (texelLoc.x + 2, texelLoc.yz), diElectric, IoR);
	voxHitData.emissivity = emissivityAndRoughness.x;
	voxHitData.roughness = emissivityAndRoughness.yz;
	voxHitData.diElectric = diElectric;
	voxHitData.IoR = IoR;
	
	float specularity = 0.0;
	mat3 tangentSpace = getOrthoBasisAndSpec (ivec3 (texelLoc.x + 1, texelLoc.yz), specularity);
	
	voxHitData.tangentSpace = tangentSpace;
	voxHitData.specularity = specularity;
	
	return voxHitData;
}

float schlicks (float n1, float n2, vec3 norm, vec3 light)
{
	float R0 = (n1 - n2)/(n1 + n2);
	R0 *= R0;
	float _1_minus_dot = 1.0 - min(abs (dot (norm, light)), 1.0);
	_1_minus_dot = _1_minus_dot*_1_minus_dot*_1_minus_dot*_1_minus_dot*_1_minus_dot;
	return R0 + (1 - R0) * _1_minus_dot;
}

vec3 getSkyValue (vec3 dirToSample)
{
	dirToSample.z = -dirToSample.z;
	return texture(skyBox,dirToSample).xyz;
}

vec2 getScreenSampleCoord (vec3 ptWorld)
{
    vec4 ptInfo = SkyShadowMapMVP.projectionViewMatrix * vec4 (ptWorld,1.0);
    ptInfo.xy = ((ptInfo.xy/ptInfo.w)+vec2 (1.0))*0.5;
    return ptInfo.xy;
}

float luminance(vec3 rgb)
{
    return dot(rgb, vec3(0.2125, 0.7154, 0.0721));
}

vec3 getSkyDirectLight ()
{
	return rayleighMieInfo.skyObjectLightAndAngle.xyz * max (luminance (getSkyValue (rayleighMieInfo.lightDir.xyz) * 0.1) * sqrt (max (rayleighMieInfo.sunDirAndExp.y, 0.0)), 1.0);
}

vec3 getSunContrib (vec3 pos, vec3 norm)
{
	float sunDotProd = max (dot (norm, rayleighMieInfo.lightDir.xyz), 0.0);
	float shadowBias = (1.0 - sunDotProd) * 1.0 + 0.5;
	float distToSkyLum = length (SkyShadowMapMVP.eye.xyz - pos) - shadowBias;
	ivec2 texeLoc = ivec2 (clamp (getScreenSampleCoord (pos), vec2 (0.0), vec2 (0.999999)) * vec2 (imageSize(shadowDistance).xy));
	uint distanceFetch = imageLoad (shadowDistance, texeLoc).x;
	float shadowDist = sqrt (float (distanceFetch) * 0.1);
	float sunVis = max (sign (shadowDist - distToSkyLum), 0.0) * sunDotProd;
	if ( sunVis > 0.0 )
	{
		vec3 retVal = getSkyDirectLight () * sunVis;
		vec3 stainedColorFetch = imageLoad (shadowColor, texeLoc).rgb;
		if ( stainedColorFetch != vec3 (0.0) ) retVal *= stainedColorFetch;
		return retVal;
	}
	return vec3 (0.0);
}

void main()
{
	if ( any(greaterThanEqual(gl_GlobalInvocationID, ivec3 (voxelizedInfo.gridSize.xyz))) ) return ;

	vec3 curPos = voxelizedInfo.mapMinVoxelSize.xyz + (vec3 (gl_GlobalInvocationID) + vec3 (0.5)) * VOXEL_DIM_SIZE;
	vec3 uvwLoc = getUVW (curPos);
	VoxelHitData curVoxelMaterial = getMaterial (uvwLoc);
	if ( curVoxelMaterial.albedo.a < 1.0 || curVoxelMaterial.emissivity != 0.0 || curVoxelMaterial.diElectric ) return ;

	vec3 absNormal = abs (curVoxelMaterial.tangentSpace[2]);
	vec3 origPos = curPos;
	if ( any(greaterThan(absNormal, vec3 (0.8))) )
		origPos += curVoxelMaterial.tangentSpace[2] * VOXEL_DIM_SIZE;
	else
		origPos += curVoxelMaterial.tangentSpace[2] * VOXEL_DIM_SIZE * 1.41;
	
	vec4 storeLightPX = vec4 (0.0);
	vec4 storeLightNX = vec4 (0.0);
	vec4 storeLightPY = vec4 (0.0);
	vec4 storeLightNY = vec4 (0.0);
	vec4 storeLightPZ = vec4 (0.0);
	vec4 storeLightNZ = vec4 (0.0);
	vec3 irrad, xIrrad, yIrrad, zIrrad;

	for (int i = 0;i != 21;i++)
		for (int j = 1;j != 12;j++)
		{
			vec3 dirToTrace = toVec3 (vec2 (float(i)/21.0, float(j)/12.0));
			curPos = origPos + dirToTrace * VOXEL_DIM_SIZE;
			vec3 glossMod = vec3 (1.0);
			while (true)
			{
				uvwLoc = getUVW (curPos);
				curVoxelMaterial = getMaterial (uvwLoc);
				if ( uvwLoc == vec3 (2.0) )
				{
					irrad = glossMod * getSkyValue (dirToTrace);
					xIrrad = dirToTrace.x * irrad;
					yIrrad = dirToTrace.y * irrad;
					zIrrad = dirToTrace.z * irrad;
					if ( dirToTrace.x > 0.0 ) storeLightPX += vec4 (xIrrad, 0.5);
					if ( dirToTrace.x < 0.0 ) storeLightNX += vec4 (-xIrrad, 0.5);
					if ( dirToTrace.y > 0.0 ) storeLightPY += vec4 (yIrrad, 0.5);
					if ( dirToTrace.y < 0.0 ) storeLightNY += vec4 (-yIrrad, 0.5);
					if ( dirToTrace.z > 0.0 ) storeLightPZ += vec4 (zIrrad, 0.5);
					if ( dirToTrace.z < 0.0 ) storeLightNZ += vec4 (-zIrrad, 0.5);
					break;
				}
				if ( curVoxelMaterial.albedo.a == 1.0 )
				{
					vec3 decodedNorm = curVoxelMaterial.tangentSpace[2];
					absNormal = abs(decodedNorm);
					vec3 moveDir;
					if ( curVoxelMaterial.emissivity > 0.0 )
					{
						irrad = glossMod * curVoxelMaterial.albedo.rgb * curVoxelMaterial.emissivity;
						xIrrad = dirToTrace.x * irrad;
						yIrrad = dirToTrace.y * irrad;
						zIrrad = dirToTrace.z * irrad;
						if ( dirToTrace.x > 0.0 ) storeLightPX += vec4 (xIrrad, 0.5);
						if ( dirToTrace.x < 0.0 ) storeLightNX += vec4 (-xIrrad, 0.5);
						if ( dirToTrace.y > 0.0 ) storeLightPY += vec4 (yIrrad, 0.5);
						if ( dirToTrace.y < 0.0 ) storeLightNY += vec4 (-yIrrad, 0.5);
						if ( dirToTrace.z > 0.0 ) storeLightPZ += vec4 (zIrrad, 0.5);
						if ( dirToTrace.z < 0.0 ) storeLightNZ += vec4 (-zIrrad, 0.5);
						break ;
					}
					else if ( curVoxelMaterial.diElectric )
					{
						float hitAngle = dot (decodedNorm, dirToTrace);
						if ( hitAngle < 0.0 )
						{
							if ( schlicks (1.0, curVoxelMaterial.IoR, decodedNorm, dirToTrace) > 0.75 )
							{
								dirToTrace = reflect (dirToTrace, decodedNorm);
								moveDir = decodedNorm;
							}
							else
							{
								dirToTrace = refract (dirToTrace, decodedNorm, 1.0/curVoxelMaterial.IoR);
								moveDir = -decodedNorm;
							}
						}
						else
						{
							float nRatio = 1.0/curVoxelMaterial.IoR;
							if ( (nRatio * nRatio) - 1.0 + (hitAngle * hitAngle) < 0.0 )
							{
								dirToTrace = reflect (dirToTrace, -decodedNorm);
								moveDir = -decodedNorm;
							}
							else
							{
								dirToTrace = refract (dirToTrace, -decodedNorm, curVoxelMaterial.IoR);
								moveDir = decodedNorm;
							}
						}
						glossMod *= curVoxelMaterial.specular.rgb;
						if ( any(greaterThan(absNormal, vec3 (0.8))) )
							curPos += moveDir * VOXEL_DIM_SIZE;
						else
							curPos += moveDir * VOXEL_DIM_SIZE * 1.41;
					}
					else if ( curVoxelMaterial.specularity > 0.8 )
					{
						dirToTrace = reflect (dirToTrace, decodedNorm);
						glossMod *= curVoxelMaterial.specular.rgb;
						if ( any(greaterThan(absNormal, vec3 (0.8))) )
							curPos += decodedNorm * VOXEL_DIM_SIZE;
						else
							curPos += decodedNorm * VOXEL_DIM_SIZE * 1.41;
					}
					else {
						vec3 decodedNormAbs = abs(decodedNorm);
						float maxNormComp = max(max(decodedNormAbs.x, decodedNormAbs.y), decodedNormAbs.z);
						ivec3 imgUvwLoc = ivec3 (uvwLoc * voxelizedInfo.gridSize.xyz);
						vec4 fetchVoxelRadiance;
						if ( maxNormComp == decodedNormAbs.x )
						{
							if ( decodedNormAbs.x > 0.0 )
								fetchVoxelRadiance = imageLoad (radiosityMapPX, imgUvwLoc);
							else
								fetchVoxelRadiance = imageLoad (radiosityMapNX, imgUvwLoc);
						}
						else if ( maxNormComp == decodedNormAbs.y )
						{
							if ( decodedNormAbs.y > 0.0 )
								fetchVoxelRadiance = imageLoad (radiosityMapPY, imgUvwLoc);
							else
								fetchVoxelRadiance = imageLoad (radiosityMapNY, imgUvwLoc);
						}
						else
						{
							if ( decodedNormAbs.z > 0.0 )
								fetchVoxelRadiance = imageLoad (radiosityMapPZ, imgUvwLoc);
							else
								fetchVoxelRadiance = imageLoad (radiosityMapNZ, imgUvwLoc);
						}
						irrad = fetchVoxelRadiance.rgb * glossMod * curVoxelMaterial.albedo.rgb;
						xIrrad = dirToTrace.x * irrad;
						yIrrad = dirToTrace.y * irrad;
						zIrrad = dirToTrace.z * irrad;
						if ( dirToTrace.x > 0.0 ) storeLightPX += vec4 (xIrrad, 0.5);
						if ( dirToTrace.x < 0.0 ) storeLightNX += vec4 (-xIrrad, 0.5);
						if ( dirToTrace.y > 0.0 ) storeLightPY += vec4 (yIrrad, 0.5);
						if ( dirToTrace.y < 0.0 ) storeLightNY += vec4 (-yIrrad, 0.5);
						if ( dirToTrace.z > 0.0 ) storeLightPZ += vec4 (zIrrad, 0.5);
						if ( dirToTrace.z < 0.0 ) storeLightNZ += vec4 (-zIrrad, 0.5);
						break ;
					}
				}
				curPos += dirToTrace * VOXEL_DIM_SIZE;
			}
		}

	imageStore (radiosityMapPX, ivec3 (gl_GlobalInvocationID), vec4 (storeLightPX.rgb / storeLightPX.a + getSunContrib(origPos, vec3 (1.0, 0.0, 0.0)), 1.0));
	imageStore (radiosityMapNX, ivec3 (gl_GlobalInvocationID), vec4 (storeLightNX.rgb / storeLightNX.a + getSunContrib(origPos, vec3 (-1.0, 0.0, 0.0)), 1.0));
	imageStore (radiosityMapPY, ivec3 (gl_GlobalInvocationID), vec4 (storeLightPY.rgb / storeLightPY.a + getSunContrib(origPos, vec3 (0.0, 1.0, 0.0)), 1.0));
	imageStore (radiosityMapNY, ivec3 (gl_GlobalInvocationID), vec4 (storeLightNY.rgb / storeLightNY.a + getSunContrib(origPos, vec3 (0.0, -1.0, 0.0)), 1.0));
	imageStore (radiosityMapPZ, ivec3 (gl_GlobalInvocationID), vec4 (storeLightPZ.rgb / storeLightPZ.a + getSunContrib(origPos, vec3 (0.0, 0.0, 1.0)), 1.0));
	imageStore (radiosityMapNZ, ivec3 (gl_GlobalInvocationID), vec4 (storeLightNZ.rgb / storeLightNZ.a + getSunContrib(origPos, vec3 (0.0, 0.0, -1.0)), 1.0));
}