#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_control_flow_attributes : enable

#define NUM_PREDICATES 16
#define NUM_THREADS 512

layout (local_size_x = NUM_THREADS, local_size_y = 1, local_size_z = 1) in;

shared uint predicateSumChunk[NUM_THREADS][NUM_PREDICATES];
shared uint predicateSum[NUM_PREDICATES-1];

layout(binding = 0) uniform paramsBuf
{
	uvec4 countReserved;
} params;

layout(binding = 1) buffer srcDataBuf
{
	uvec4 data[];
} src;

layout(binding = 2) buffer dstDataBuf
{
	uvec4 data[];
} dst;

void radixPhase(uint shiftAmount)
{
	uint bitMask = 0x0000000F << shiftAmount;
	bool isEven = ((shiftAmount / 4) % 2 == 0);
	uint chunkSize = (params.countReserved.x / NUM_THREADS) + 1;
	uint baseIndex = gl_LocalInvocationID.x * chunkSize;
	
	[[unroll]]
	for (uint i = 0; i != NUM_PREDICATES; i++)
		predicateSumChunk[gl_LocalInvocationID.x][i] = 0;

	memoryBarrierShared();
	barrier();

	if ( baseIndex < params.countReserved.x )
	{
		for (uint i = baseIndex; i != baseIndex + chunkSize; i++)
		{
			if ( i >= params.countReserved.x ) break;
			uint srcDataFetch = isEven ? src.data[i / 4][i % 4] : dst.data[i / 4][i % 4];
			predicateSumChunk[gl_LocalInvocationID.x][((srcDataFetch & bitMask) >> shiftAmount)]++;
		}
	}

	memoryBarrierShared();
	barrier();

	if ( gl_LocalInvocationID.x == 0 )
	{
		[[unroll]]
		for (uint i = 0; i != NUM_PREDICATES-1; i++)
		{
			predicateSum[i] = 0;
			[[unroll]]
			for (uint j = 0; j != NUM_THREADS; j++)
				predicateSum[i] += predicateSumChunk[j][i];
		}
	}

	memoryBarrierShared();
	barrier();

	uint predOffset[NUM_PREDICATES];
	[[unroll]]
	for (uint i = 0; i != NUM_PREDICATES; i++)
		predOffset[i] = 0;
	for (uint i = 0; i != gl_LocalInvocationID.x; i++)
	{
		[[unroll]]
		for (uint j = 0; j != NUM_PREDICATES; j++)
			predOffset[j] += predicateSumChunk[i][j];
	}

	[[unroll]]
	for (uint i = 0; i != NUM_PREDICATES; i++)
		for (uint j = 0; j != i; j++)
			predOffset[i] += predicateSum[j];
	
	if ( baseIndex < params.countReserved.x )
	{
		for (uint i = baseIndex; i != baseIndex + chunkSize; i++)
		{
			if ( i >= params.countReserved.x ) break;
			uint srcDataFetch = isEven ? src.data[i / 4][i % 4] : dst.data[i / 4][i % 4];
			uint curPredicate = ((srcDataFetch & bitMask) >> shiftAmount);
			uint newIndex = predOffset[curPredicate];
			predOffset[curPredicate]++;
			if ( isEven )
				dst.data[newIndex / 4][newIndex % 4] = src.data[i / 4][i % 4];
			else
				src.data[newIndex / 4][newIndex % 4] = dst.data[i / 4][i % 4];
		}
	}
}

void main()
{
	radixPhase (0);
	radixPhase (4);
	radixPhase (8);
	radixPhase (12);
	radixPhase (16);
	radixPhase (20);
	radixPhase (24);
	radixPhase (28);
}