#version 460
#extension GL_EXT_ray_tracing : require

#define HIGHOMEGA_MAX_NEE_HINTS 200
#define HIGHOMEGA_GENERATE_HINTS_PER_LUMINARE 20
#define M_PI 3.1415926535
#define M_INV_PI 0.31830988618

layout (binding = 0, set = 0) uniform accelerationStructureEXT topLevelAS;
layout (binding = 1) uniform sampler2D materialAttach;
layout (binding = 2) uniform sampler2D worldPosAttach;
layout (binding = 3) uniform sampler2D normalAttach;
layout (binding = 4) uniform samplerCube skyBox;

layout (binding = 6) uniform RayleighMieUBO
{
	vec4 lightDir;
	vec4 sunDirAndExp;
	vec4 invW4InnerRad;

	float innerCloudRad;
	float outerRad;
	float scaleDepth;
	float scaleOverScaleDepth;
	
	float scatteringCoeff;
	float extinctionCoeff;
	float ambientCoeff;
	float stepSizeEvalLightDir;

	float stepSizeToSky;
	float numStepsToSky;
	float stepSizeToSun;
	float numStepsToSun;
	
	vec4 addSkyColorAndNightAmount;
	vec4 skyObjectLightAndAngle;
	vec4 horizonColor;
	vec4 approxGroundColor;
} rayleighMieInfo;

layout (binding = 7, r32ui) uniform readonly uimage2D shadowDistance;
layout (binding = 8, rgba8) uniform readonly image2D shadowColor;

struct NEEHint
{
    vec4 posArea;
	vec4 norm;
};

layout (binding = 9) uniform NEEDataUBO
{
    NEEHint hint[HIGHOMEGA_MAX_NEE_HINTS];
    uvec4 hintCountReserved;
} NEEData;

layout (binding = 10) uniform FrameMVPUBO
{
	mat4 projectionViewMatrix;
	vec4 lookEyeX;
	vec4 upEyeY;
	vec4 sideEyeZ;
} frameMVP;

layout (binding = 11, rgba16f) uniform writeonly image2D glossTraceOutput;
layout (binding = 12) uniform sampler2D blueNoise;

layout (binding = 13) uniform PathTraceParamsUBO
{
	vec4 motionFactorDiffuseOnlyReserved;
	vec4 timeTurnBlurDirectionRawLight;
} pathTraceParams;

layout(location = 0) rayPayloadEXT struct {
	vec3 contrib;
	vec3 explicitContrib;
	vec3 lastVertexNormal;
	vec3 lastVertexPos;
	bool lastVertexDiffuse;
	uint bounceCount;
	/*bool checkLuminare;
	bool hitHint;
	vec3 hintPos;
	vec3 hintNormal;
	vec3 luminareEnergy;*/
} hitValues;

vec3 getRand (vec3 forPos)
{
    float rx = fract(sin(dot(forPos, vec3(-9062.9898,  4528.233,  1296.1938))) * 43758.5453);
    float ry = fract(cos(dot(forPos, vec3( 1137.1948,  7670.963, -4424.0687))) * 43758.5453);
    float rz = fract(sin(dot(forPos, vec3( 5649.4233, -3286.248,  4353.5856))) * 93758.5453);
    
    return (vec3 (rx,ry,rz) - vec3 (0.5))* 2.0;
}

float schlicks (float n1, float n2, vec3 norm, vec3 light)
{
	float R0 = (n1 - n2)/(n1 + n2);
	R0 *= R0;
	float _1_minus_dot = 1.0 - min(abs (dot (norm, light)), 1.0);
	_1_minus_dot = _1_minus_dot*_1_minus_dot*_1_minus_dot*_1_minus_dot*_1_minus_dot;
	return R0 + (1 - R0) * _1_minus_dot;
}

vec3 diffuseBounce (mat3 tangentSpace, vec3 randVal)
{
    return normalize (tangentSpace[2] + normalize (randVal)*0.999999);
}

#define SCALE_ROUGHNESS 0.1

vec3 reflectRay (vec3 rayToReflect, mat3 tangentSpace, vec2 withRoughness, vec3 randVal)
{
	return normalize (reflect (rayToReflect, tangentSpace[2]) + tangentSpace[0] * withRoughness.x * randVal.x * SCALE_ROUGHNESS + tangentSpace[1] * withRoughness.y * randVal.y * SCALE_ROUGHNESS);
}

vec3 refractRay (vec3 rayToRefract, mat3 tangentSpace, vec2 withRoughness, float n1, float n2, out bool TIR, vec3 randVal)
{
	vec3 snellsLaw = refract (rayToRefract, tangentSpace[2], n1/n2);
	if ( snellsLaw == vec3 (0.0) )
	{
		TIR = true;
		return reflectRay (rayToRefract, tangentSpace, withRoughness, randVal);
	}
	else
	{
		TIR = false;
		return normalize (snellsLaw + tangentSpace[0] * withRoughness.x * randVal.x * SCALE_ROUGHNESS + tangentSpace[1] * withRoughness.y * randVal.y * SCALE_ROUGHNESS);
	}
}

vec3 toVec3(vec2 inpVec)
{
	float phi = inpVec.x * (2.0 * M_PI);
	float theta = inpVec.y * M_PI;
	float sinTheta = sin(theta);
	return vec3 (cos(phi) * sinTheta, cos(theta), sin(phi) * sinTheta);
}

vec3 getExplicitContrib(vec3 rayOrigin, vec3 originNormal, vec3 randVal)
{
	/*uint pickAHint = uint (float (NEEData.hintCountReserved.x) * ((randVal.z + 1.0) * 0.4999999));
	NEEHint pickedHint = NEEData.hint[pickAHint];
	vec3 traceLine = pickedHint.posArea.xyz - rayOrigin;
	float traceLineLength = max (length(traceLine), 0.0001);
    vec3 traceDir = normalize (traceLine);
	float cosOutgoing = max (dot (traceDir, originNormal), 0.0);
	if ( cosOutgoing == 0.0 ) return vec3 (0.0);
	float cosIncoming = max (dot (-traceDir, pickedHint.norm.xyz), 0.0);
	if ( cosIncoming == 0.0 ) return vec3 (0.0);

    uint rayFlags = 0;
    uint cullMask = 0xff;
    float tmin = 0.1;
    float tmax = (traceLineLength + 0.1)/traceLineLength;
	
	hitValues.checkLuminare = true;
	hitValues.hitHint = false;
	hitValues.hintPos = pickedHint.posArea.xyz;
	hitValues.hintNormal = pickedHint.norm.xyz;

	traceRayEXT(topLevelAS, rayFlags, cullMask, 0 , 0 , 0 , rayOrigin, tmin, traceLine, tmax, 0 );
	
	hitValues.checkLuminare = false;

	if ( hitValues.hitHint )
	{
		hitValues.hitHint = false;
		float lightPDF = dot (traceLine, traceLine) / (pickedHint.posArea.a * cosIncoming);
		float scatteringPDF = cosOutgoing * M_INV_PI;
		float MISWeight = lightPDF / ((lightPDF * lightPDF) + (scatteringPDF * scatteringPDF)); // Power heuristic, B=2.0
		// M_INV_PI is because of diffuse BRDF (albedo/PI) and the foreshortening factor needs to be here: things don't cancel out anymore as the PDF cancels with the MIS weight numerator
		return (float (NEEData.hintCountReserved.x) / float(HIGHOMEGA_GENERATE_HINTS_PER_LUMINARE)) * hitValues.luminareEnergy * MISWeight * cosOutgoing * M_INV_PI;
	}
	else*/
		return vec3 (0.0);
}

vec3 getContribDiffuseOnly(vec3 rayOrigin, vec3 rayDir, vec2 fragRoughness, float fragSpecularity, float refractiveIndex, bool isDielectric, mat3 tangentSpace, vec3 fragGeomNorm, inout vec3 hitPoint)
{
	hitValues.contrib = vec3 (1.0);
	hitValues.explicitContrib = vec3 (0.0);
	hitValues.bounceCount = 0;

	vec3 tracePos = rayOrigin;
	vec3 traceDir = rayDir;
	vec3 moveDir = fragGeomNorm;
	hitValues.lastVertexNormal = tangentSpace[2];
	hitValues.lastVertexPos = tracePos;
	hitValues.lastVertexDiffuse = false;
	vec3 randVal = vec3 (0.0);

	vec2 blueNoiseLoc = vec2 (int(gl_LaunchIDEXT.x) % textureSize (blueNoise, 0).x, int(gl_LaunchIDEXT.y) % textureSize (blueNoise, 0).y) / vec2 (textureSize (blueNoise, 0).xy);
	blueNoiseLoc += getRand (rayOrigin * pathTraceParams.timeTurnBlurDirectionRawLight.x).xy * 0.33333;
	ivec2 blueNoiseTexelLoc = ivec2 (clamp (fract(abs(blueNoiseLoc)), vec2 (0.0), vec2 (0.999999)) * vec2 (textureSize (blueNoise, 0).xy));
	vec4 blueNoiseFetch = texelFetch (blueNoise, blueNoiseTexelLoc, 0);
	randVal = blueNoiseFetch.xyz * 2.0 - vec3 (1.0);

	hitValues.lastVertexDiffuse = true;
	traceDir = diffuseBounce (tangentSpace, randVal);
	hitValues.explicitContrib += getExplicitContrib (hitValues.lastVertexPos, hitValues.lastVertexNormal, randVal);
	// First-bounce sun contrib is added later post-denoise

    uint rayFlags = 0;
    uint cullMask = 0xff;
    float tmin = 0.1;
    float tmax = 1000000.0;
	
	traceRayEXT(topLevelAS, rayFlags, cullMask, 0 , 0 , 0 , tracePos, tmin, traceDir, tmax, 0 );
	
	return hitValues.contrib + hitValues.explicitContrib;
}

vec3 getContribSpecularOnly(vec3 rayOrigin, vec3 rayDir, vec2 fragRoughness, float fragSpecularity, float refractiveIndex, bool isDielectric, mat3 tangentSpace, vec3 fragGeomNorm, inout vec3 hitPoint)
{
	hitValues.contrib = vec3 (1.0);
	hitValues.explicitContrib = vec3 (0.0);
	hitValues.bounceCount = 0;

	vec3 tracePos = rayOrigin;
	vec3 traceDir = rayDir;
	vec3 moveDir = fragGeomNorm;
	hitValues.lastVertexNormal = tangentSpace[2];
	hitValues.lastVertexPos = tracePos;
	hitValues.lastVertexDiffuse = false;
	vec3 randVal = vec3 (0.0);

	vec2 blueNoiseLoc = vec2 (int(gl_LaunchIDEXT.x) % textureSize (blueNoise, 0).x, int(gl_LaunchIDEXT.y) % textureSize (blueNoise, 0).y) / vec2 (textureSize (blueNoise, 0).xy);
	blueNoiseLoc += getRand (rayOrigin * pathTraceParams.timeTurnBlurDirectionRawLight.x).xy * 0.33333;
	ivec2 blueNoiseTexelLoc = ivec2 (clamp (fract(abs(blueNoiseLoc)), vec2 (0.0), vec2 (0.999999)) * vec2 (textureSize (blueNoise, 0).xy));
	vec4 blueNoiseFetch = texelFetch (blueNoise, blueNoiseTexelLoc, 0);
	randVal = blueNoiseFetch.xyz * 2.0 - vec3 (1.0);

	if ( !isDielectric )
	{
		//if ( fragSpecularity * schlicks (1.0, refractiveIndex, tangentSpace[2], traceDir) >= max ((randVal.z + 1.0) * 0.5, 0.000001) )
		{
			traceDir = reflectRay (traceDir, tangentSpace, fragRoughness, randVal);
		}
		/*else
		{
			hitValues.lastVertexDiffuse = true;
			traceDir = diffuseBounce (tangentSpace, randVal);
			hitValues.explicitContrib += getExplicitContrib (hitValues.lastVertexPos, hitValues.lastVertexNormal, randVal);
			// First-bounce sun contrib is added later post-denoise
		}*/
	}
	else
	{
		if ( schlicks (1.0, refractiveIndex, tangentSpace[2], traceDir) >= max ((randVal.z + 1.0) * 0.5, 0.000001) )
		{
			traceDir = reflectRay (traceDir, tangentSpace, fragRoughness, randVal);
		}
		else
		{
			bool TIR = false; // Kinda useless here as we'll make sure we don't start inside di-electric materials...
			moveDir = -fragGeomNorm;
			traceDir = refractRay (traceDir, tangentSpace, fragRoughness, 1.0, refractiveIndex, TIR, randVal);
		}
	}

    uint rayFlags = 0;
    uint cullMask = 0xff;
    float tmin = 0.1;
    float tmax = 1000000.0;
	
	traceRayEXT(topLevelAS, rayFlags, cullMask, 0 , 0 , 0 , tracePos, tmin, traceDir, tmax, 0 );
	
	return hitValues.contrib + hitValues.explicitContrib;
}


vec2 unpackEmissivityRefractiveIndexDielectric (float inpEmissivityRefractiveIndexDielectricPacked, out bool isDielectric)
{
	float ourEmissivityRefractiveIndexDielectricPacked = inpEmissivityRefractiveIndexDielectricPacked;
	if ( ourEmissivityRefractiveIndexDielectricPacked < 0.0 )
	{
		ourEmissivityRefractiveIndexDielectricPacked = -ourEmissivityRefractiveIndexDielectricPacked;
		isDielectric = true;
	}
	else
	{
		isDielectric = false;
	}
	float emissivity = fract (ourEmissivityRefractiveIndexDielectricPacked)* 255.0;
	float refractiveIndex = floor (ourEmissivityRefractiveIndexDielectricPacked) / 1000.0;
	return vec2 (emissivity,refractiveIndex);
}

vec2 unpackSpherical(float inpPack)
{
	uint packInt = floatBitsToUint(inpPack);
	vec2 retVal;
	retVal.x = float((packInt & 0xFFFF0000) >> 16) / 65535.0;
	retVal.y = float(packInt & 0x0000FFFF) / 65535.0;
	return retVal;
}

void main()
{
	vec2 inUV = (vec2 (gl_LaunchIDEXT.xy) + vec2 (0.5)) / vec2(gl_LaunchSizeEXT.xy);
	ivec2 texelLoc = ivec2 (vec2 (textureSize(materialAttach, 0).xy) * inUV);

	vec4 fetchedWorldPosAndMaterialHint = texelFetch(worldPosAttach, texelLoc, 0);
	if (fetchedWorldPosAndMaterialHint == vec4 (0.0))
	{
		imageStore (glossTraceOutput, texelLoc, vec4 (0.0));
		return ;
	}
	vec4 materialFetch = texelFetch(materialAttach, texelLoc, 0);
	bool isDielectric;
	vec2 emissivityRefractiveIndex = unpackEmissivityRefractiveIndexDielectric (materialFetch.w, isDielectric);

	if ( emissivityRefractiveIndex.x > 0.0 )
	{
		imageStore (glossTraceOutput, texelLoc, vec4 (0.0));
		return ;
	}
	
	vec3 rayOrigin = fetchedWorldPosAndMaterialHint.xyz;
	vec3 rayDir = normalize (fetchedWorldPosAndMaterialHint.xyz - vec3 (frameMVP.lookEyeX.a, frameMVP.upEyeY.a, frameMVP.sideEyeZ.a));
	
	vec4 fragmentRoughnessSpecularity = unpackUnorm4x8(floatBitsToUint (materialFetch.z));
	
	vec4 normalFetch = texelFetch(normalAttach, texelLoc, 0);

	mat3 tangentSpace;
	tangentSpace[2] = toVec3 (unpackSpherical (normalFetch.x));
	vec3 fragmentGeomNorm = toVec3 (unpackSpherical (normalFetch.y));
	tangentSpace[0] = toVec3 (unpackSpherical (normalFetch.z));
	tangentSpace[1] = toVec3 (unpackSpherical (normalFetch.w));

	tangentSpace[2] = -sign (dot (rayDir, tangentSpace[2])) * tangentSpace[2];
	fragmentGeomNorm = -sign (dot (rayDir, fragmentGeomNorm)) * fragmentGeomNorm;
	
	vec3 hitPoint = vec3 (0.0);

	vec3 diffuseContrib = vec3 (0.0);
	vec3 glossContrib = vec3 (0.0);

	/*if ( pathTraceParams.motionFactorDiffuseOnlyReserved.y == 1.0 )
	{
		if ( fragmentRoughnessSpecularity.b < 1.0 )
			diffuseContrib = getContribDiffuseOnly (rayOrigin, rayDir, fragmentRoughnessSpecularity.rg, fragmentRoughnessSpecularity.b, emissivityRefractiveIndex.y, isDielectric, tangentSpace, fragmentGeomNorm, hitPoint);
	}
	else*/
	{
		if ( fragmentRoughnessSpecularity.b > 0.0 )
		{
			glossContrib = getContribSpecularOnly (rayOrigin, rayDir, fragmentRoughnessSpecularity.rg, fragmentRoughnessSpecularity.b, emissivityRefractiveIndex.y, isDielectric, tangentSpace, fragmentGeomNorm, hitPoint);
			float distToHit = length (rayOrigin - hitPoint);
			imageStore (glossTraceOutput, texelLoc, vec4 (glossContrib, distToHit));
		}
	}
}