#version 460
#extension GL_NV_ray_tracing : require

#define VOXEL_DIM_SIZE gridInfo.center.w
#define M_PI 3.1415926535

layout (binding = 0, set = 0) uniform accelerationStructureNV topLevelAS;
layout (binding = 1) uniform sampler3D diffuseSampler;
layout (binding = 2) uniform sampler3D normalSampler;
layout (binding = 3) uniform sampler3D emissivityDielectricRefractiveIndexAndRoughness3DSampler;
layout (binding = 4) uniform sampler3D specular3DSampler;

layout (binding = 5, rgba16f) uniform image3D preIlluminateImage;

layout (binding = 6) uniform GridInfoUBO
{
	vec4 gridMin;
	vec4 gridMax;
	vec4 center;
	vec4 mapMin;
	vec4 mapMax;
} gridInfo;

layout (binding = 8) uniform SunUBO
{
	vec4 dir;
} sun;

layout(location = 0) rayPayloadNV struct {
	vec3 radiance;
} hitValues;

vec3 getUVW (vec3 worldPos)
{
	vec3 boxMax = gridInfo.center.xyz + gridInfo.gridMax.xyz;
	vec3 boxMin = gridInfo.center.xyz + gridInfo.gridMin.xyz;
	vec3 boxLen = boxMax - boxMin;
    vec3 boxUVW = (worldPos - boxMin)/boxLen;
	if ( boxUVW == clamp (boxUVW, vec3(0.0), vec3(1.0)) )
	{
		return boxUVW;
	}
	return vec3 (2.0);
}

vec3 toVec3(vec2 inpVec)
{
	float phi = inpVec.x * (2.0 * M_PI);
	float theta = inpVec.y * M_PI;
	vec3 onPlane = vec3 (cos(phi), 0.0, 0.0) + vec3 (0.0, 0.0, sin(phi));
	return onPlane*sin(theta) + vec3(0.0, cos(theta), 0.0);
}

mat3 decodeTanBitan (float encodedTanBiTan, vec3 inpNorm)
{
	float encodedVal = round (encodedTanBiTan * 255.0);
	bool biTanDotBasisYNegative = false;
	if ( encodedVal >= 128.0 )
	{
		encodedVal -= 128.0;
		biTanDotBasisYNegative = true;
	}
	bool tanDotBasisYNegative = false;
	if ( encodedVal >= 64.0 )
	{
		encodedVal -= 64.0;
		tanDotBasisYNegative = true;
	}
	float basisXShadow = clamp (((encodedVal / 63.0) * 2.0) - 1.0, -1.0, 1.0);
	float basisYShadow = sqrt (1.0 - basisXShadow*basisXShadow);
	vec3 aBasisX = normalize (cross (inpNorm, inpNorm + vec3 (0.1)));
	vec3 aBasisY = cross (inpNorm,aBasisX);
	vec3 tanVector = basisXShadow * aBasisX;
	if (tanDotBasisYNegative)
		tanVector -= basisYShadow * aBasisY;
	else
		tanVector += basisYShadow * aBasisY;
	tanVector = normalize (tanVector);
	vec3 biTanVector = cross (inpNorm, tanVector);
	if ( dot (biTanVector, aBasisY) > 0.0 && biTanDotBasisYNegative ) biTanVector = -biTanVector;
	mat3 retVal;
	retVal[0] = tanVector;
	retVal[1] = biTanVector;
	retVal[2] = inpNorm;
	return retVal;
}

mat3 getOrthoBasis (vec3 uvwLoc)
{
	vec4 fetchEncodedBasis = texture(normalSampler,uvwLoc);
	vec3 decodedNorm = normalize (toVec3 (fetchEncodedBasis.rg));
	mat3 decodedBasis = decodeTanBitan (fetchEncodedBasis.b, decodedNorm);
	return decodedBasis;
}

vec3 getEmissivityDielectricRefractiveIndexAndRoughness3DImage (vec3 uvwLoc, out bool diElectric, out float IoR)
{
	vec4 rawFetch = texture(emissivityDielectricRefractiveIndexAndRoughness3DSampler,uvwLoc);
	float pureEmissivity = rawFetch.x * 25.5;
	vec2 fetchedRoughness = rawFetch.zw;
	
	float dielectricRefractiveIndex = rawFetch.y * 255.0;
	if ( dielectricRefractiveIndex >= 128.0 )
	{
		diElectric = true;
		dielectricRefractiveIndex -= 128.0;
	}
	else
		diElectric = false;
		
	IoR = dielectricRefractiveIndex * 0.03149606299212598425196850393701;

	return vec3 (pureEmissivity, fetchedRoughness);
}

ivec3 getImageLoc (vec3 uvwLoc)
{
	vec3 boxMax = gridInfo.center.xyz + gridInfo.gridMax.xyz;
	vec3 boxMin = gridInfo.center.xyz + gridInfo.gridMin.xyz;
	vec3 boxLen = boxMax - boxMin;
	return ivec3 (round((uvwLoc * boxLen) / VOXEL_DIM_SIZE));
}

void main() 
{
	vec3 curPos = gridInfo.mapMin.xyz + vec3 (gl_LaunchIDNV.xyz) * VOXEL_DIM_SIZE;
	vec3 uvwLoc = getUVW (curPos);
	vec3 uvwOrigLoc = uvwLoc;
	ivec3 iUvwOrigLoc = getImageLoc(uvwOrigLoc);
	bool diElectric;
	float IoR;
	vec3 emissivityRoughness = getEmissivityDielectricRefractiveIndexAndRoughness3DImage (uvwLoc, diElectric, IoR);
	if ( texture(diffuseSampler, uvwLoc).a == 0.0 || emissivityRoughness.x != 0.0 || diElectric ) return ;
	if ( imageLoad (preIlluminateImage, iUvwOrigLoc) != vec4 (0.0) ) return ;

	mat3 curBasis = getOrthoBasis (uvwLoc);
	curPos += curBasis[2] * VOXEL_DIM_SIZE * 1.41;
	vec3 origPos = curPos;
	
	vec4 storeLight = vec4 (0.0);

	for (int i = 0;i != 21;i++)
		for (int j = 1;j != 6;j++)
		{
			float phi =  (float(i)/21.0) * M_PI * 2.0;
			float theta = (float(j)/6.0) * M_PI * 0.5;
			curPos = origPos;
			vec3 dirToTrace = (cos(phi) * curBasis[0] + sin(phi) * curBasis[1]) * cos (theta) + curBasis[2] * sin (theta);
			hitValues.radiance = vec3 (1.0);
			
			uint rayFlags = 0;
			uint cullMask = 0xff;
			float tmin = 0.1;
			float tmax = 1000000.0;
			
			traceNV(topLevelAS, rayFlags, cullMask, 0 , 0 , 0 , curPos.xyz, tmin, dirToTrace, tmax, 0 );
			
			storeLight += vec4 (hitValues.radiance, 1.0) * abs (dot (curBasis[2], dirToTrace)) * 0.01 * sin (theta);
		}

	imageStore (preIlluminateImage, iUvwOrigLoc, storeLight);
}