/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

#define NUM_THREADS 32

layout (local_size_x = NUM_THREADS, local_size_y = 1, local_size_z = 1) in;

layout(binding = 0) uniform buildParamsUBO
{
	vec4 mapMinLeafCount;
	vec4 mapMax;
} buildParams;

struct SDFLeaf
{
	vec4 leafMinMorton;
	vec4 leafMaxLeafId;
};

layout(binding = 1) buffer sdfLeavesSSBO
{
	SDFLeaf leaf[];
} sdfLeaves;

uint expandBits(uint v)
{
	v = (v * 0x00010001u) & 0xFF0000FFu;
	v = (v * 0x00000101u) & 0x0F00F00Fu;
	v = (v * 0x00000011u) & 0xC30C30C3u;
	v = (v * 0x00000005u) & 0x49249249u;
	return v;
}

uint morton3D(vec3 inp)
{
	inp = clamp (inp * vec3 (1024.0), vec3 (0.0), vec3 (1023.0));
	uint xx = expandBits(uint(inp.x));
	uint yy = expandBits(uint(inp.y));
	uint zz = expandBits(uint(inp.z));
	return xx * 4 + yy * 2 + zz;
}

void main()
{
	if ( gl_GlobalInvocationID.x >= floatBitsToUint(buildParams.mapMinLeafCount.a) ) return ;
	
	vec3 leafCentroid = (sdfLeaves.leaf[gl_GlobalInvocationID.x].leafMinMorton.xyz + sdfLeaves.leaf[gl_GlobalInvocationID.x].leafMaxLeafId.xyz) * 0.5;
	vec3 aabbFrac = (leafCentroid - buildParams.mapMinLeafCount.xyz) / (buildParams.mapMax.xyz - buildParams.mapMinLeafCount.xyz);

	sdfLeaves.leaf[gl_GlobalInvocationID.x].leafMinMorton.a = uintBitsToFloat (morton3D (aabbFrac));
}