/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (binding = 0, r32f) uniform readonly image2D LOD64MinZ;
layout (binding = 1, r32f) coherent uniform writeonly image2D LODMinZChain[6];
layout (binding = 2, r32f) uniform readonly image2D LOD64MaxZ;
layout (binding = 3, r32f) coherent uniform writeonly image2D LODMaxZChain[6];

shared float cachedMinValues[64][64], cachedMaxValues[64][64];

float computeCachedMinValue(uint readStride, uvec2 readCoord, uvec2 writeCoord)
{
	uint writeStride = readStride * 2;
	uvec2 readCoord00 = readCoord * readStride;
	uvec2 readCoord01 = uvec2 (readCoord.x, readCoord.y + 1) * readStride;
	uvec2 readCoord10 = uvec2 (readCoord.x + 1, readCoord.y) * readStride;
	uvec2 readCoord11 = uvec2 (readCoord.x + 1, readCoord.y + 1) * readStride;
	writeCoord *= writeStride;
	cachedMinValues[writeCoord.x][writeCoord.y] = min (min (cachedMinValues[readCoord00.x][readCoord00.y], cachedMinValues[readCoord10.x][readCoord10.y]), 
													   min (cachedMinValues[readCoord01.x][readCoord01.y], cachedMinValues[readCoord11.x][readCoord11.y]));
	return cachedMinValues[writeCoord.x][writeCoord.y];
}

float computeCachedMaxValue(uint readStride, uvec2 readCoord, uvec2 writeCoord)
{
	uint writeStride = readStride * 2;
	uvec2 readCoord00 = readCoord * readStride;
	uvec2 readCoord01 = uvec2 (readCoord.x, readCoord.y + 1) * readStride;
	uvec2 readCoord10 = uvec2 (readCoord.x + 1, readCoord.y) * readStride;
	uvec2 readCoord11 = uvec2 (readCoord.x + 1, readCoord.y + 1) * readStride;
	writeCoord *= writeStride;
	cachedMaxValues[writeCoord.x][writeCoord.y] = max (max (cachedMaxValues[readCoord00.x][readCoord00.y], cachedMaxValues[readCoord10.x][readCoord10.y]), 
													   max (cachedMaxValues[readCoord01.x][readCoord01.y], cachedMaxValues[readCoord11.x][readCoord11.y]));
	return cachedMaxValues[writeCoord.x][writeCoord.y];
}

void main()
{
	for (int i = 0; i != 8; i++)
		for (int j = 0; j != 8; j++)
		{
			ivec2 cacheIndex = ivec2 (gl_GlobalInvocationID.xy * 8) + ivec2 (i, j);
			cachedMinValues[cacheIndex.x][cacheIndex.y] = imageLoad (LOD64MinZ, cacheIndex).x;
			cachedMaxValues[cacheIndex.x][cacheIndex.y] = imageLoad (LOD64MaxZ, cacheIndex).x;
		}

	memoryBarrier();
	barrier();

	for (int i = 0; i != 4; i++)
		for (int j = 0; j != 4; j++)
		{
			ivec2 readIndex = ivec2 (gl_GlobalInvocationID.xy * 8) + ivec2 (i, j) * 2;
			ivec2 writeIndex = readIndex / 2;
			imageStore (LODMinZChain[0], writeIndex.xy, vec4(computeCachedMinValue (1, readIndex, writeIndex)));
			imageStore (LODMaxZChain[0], writeIndex.xy, vec4(computeCachedMaxValue (1, readIndex, writeIndex)));
		}

	memoryBarrier();
	barrier();

	for (int i = 0; i != 2; i++)
		for (int j = 0; j != 2; j++)
		{
			ivec2 readIndex = ivec2 (gl_GlobalInvocationID.xy * 4) + ivec2 (i, j) * 2;
			ivec2 writeIndex = readIndex / 2;
			imageStore (LODMinZChain[1], writeIndex.xy, vec4(computeCachedMinValue (2, readIndex, writeIndex)));
			imageStore (LODMaxZChain[1], writeIndex.xy, vec4(computeCachedMaxValue (2, readIndex, writeIndex)));
		}

	memoryBarrier();
	barrier();

	ivec2 readIndex = ivec2 (gl_GlobalInvocationID.xy * 2);
	imageStore (LODMinZChain[2], ivec2 (gl_GlobalInvocationID.xy), vec4(computeCachedMinValue (4, readIndex, gl_GlobalInvocationID.xy)));
	imageStore (LODMaxZChain[2], ivec2 (gl_GlobalInvocationID.xy), vec4(computeCachedMaxValue (4, readIndex, gl_GlobalInvocationID.xy)));

	if ( gl_GlobalInvocationID.x >= 4 || gl_GlobalInvocationID.y >= 4 ) return;

	memoryBarrier();
	barrier();

	readIndex = ivec2 (gl_GlobalInvocationID.xy * 2);
	imageStore (LODMinZChain[3], ivec2 (gl_GlobalInvocationID.xy), vec4(computeCachedMinValue (8, readIndex, gl_GlobalInvocationID.xy)));
	imageStore (LODMaxZChain[3], ivec2 (gl_GlobalInvocationID.xy), vec4(computeCachedMaxValue (8, readIndex, gl_GlobalInvocationID.xy)));

	if ( gl_GlobalInvocationID.x >= 2 || gl_GlobalInvocationID.y >= 2 ) return;

	memoryBarrier();
	barrier();

	readIndex = ivec2 (gl_GlobalInvocationID.xy * 2);
	imageStore (LODMinZChain[4], ivec2 (gl_GlobalInvocationID.xy), vec4(computeCachedMinValue (16, readIndex, gl_GlobalInvocationID.xy)));
	imageStore (LODMaxZChain[4], ivec2 (gl_GlobalInvocationID.xy), vec4(computeCachedMaxValue (16, readIndex, gl_GlobalInvocationID.xy)));

	if ( gl_GlobalInvocationID.xy != uvec2(0) ) return;

	memoryBarrier();
	barrier();

	imageStore (LODMinZChain[5], ivec2 (0), vec4(computeCachedMinValue (32, uvec2(0), uvec2(0))));
	imageStore (LODMaxZChain[5], ivec2 (0), vec4(computeCachedMaxValue (32, uvec2(0), uvec2(0))));
}