/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

layout (binding = 0, r32f) uniform readonly image2D LOD64MinZ;
layout (binding = 1, r32f) coherent uniform writeonly image2D LODMinZChain[6];
layout (binding = 2, r32f) uniform readonly image2D LOD64MaxZ;
layout (binding = 3, r32f) coherent uniform writeonly image2D LODMaxZChain[6];

shared float cachedMinValues64[64][64], cachedMaxValues64[64][64];
shared float cachedMinValues32[32][32], cachedMaxValues32[32][32];
shared float cachedMinValues16[16][16], cachedMaxValues16[16][16];
shared float cachedMinValues8[8][8], cachedMaxValues8[8][8];
shared float cachedMinValues4[4][4], cachedMaxValues4[4][4];
shared float cachedMinValues2[2][2], cachedMaxValues2[2][2];

void main()
{
	for (int i = 0; i != 8; i++)
		for (int j = 0; j != 8; j++)
		{
			ivec2 cacheIndex = ivec2 (gl_GlobalInvocationID.xy * 8) + ivec2 (i, j);
			cachedMinValues64[cacheIndex.x][cacheIndex.y] = imageLoad (LOD64MinZ, cacheIndex).x;
			cachedMaxValues64[cacheIndex.x][cacheIndex.y] = imageLoad (LOD64MaxZ, cacheIndex).x;
		}

	memoryBarrier();
	barrier();

	for (int i = 0; i != 4; i++)
		for (int j = 0; j != 4; j++)
		{
			ivec2 readIndex = ivec2 (gl_GlobalInvocationID.xy * 8) + ivec2 (i, j) * 2;
			ivec2 writeIndex = readIndex / 2;
			cachedMinValues32[writeIndex.x][writeIndex.y] = min (min (cachedMinValues64[readIndex.x][readIndex.y], cachedMinValues64[readIndex.x + 1][readIndex.y]), 
																 min (cachedMinValues64[readIndex.x][readIndex.y + 1], cachedMinValues64[readIndex.x + 1][readIndex.y + 1]));
			cachedMaxValues32[writeIndex.x][writeIndex.y] = max (max (cachedMaxValues64[readIndex.x][readIndex.y], cachedMaxValues64[readIndex.x + 1][readIndex.y]), 
																 max (cachedMaxValues64[readIndex.x][readIndex.y + 1], cachedMaxValues64[readIndex.x + 1][readIndex.y + 1]));
			imageStore (LODMinZChain[0], writeIndex.xy, vec4(cachedMinValues32[writeIndex.x][writeIndex.y]));
			imageStore (LODMaxZChain[0], writeIndex.xy, vec4(cachedMaxValues32[writeIndex.x][writeIndex.y]));
		}

	memoryBarrier();
	barrier();

	for (int i = 0; i != 2; i++)
		for (int j = 0; j != 2; j++)
		{
			ivec2 readIndex = ivec2 (gl_GlobalInvocationID.xy * 4) + ivec2 (i, j) * 2;
			ivec2 writeIndex = readIndex / 2;
			cachedMinValues16[writeIndex.x][writeIndex.y] = min (min (cachedMinValues32[readIndex.x][readIndex.y], cachedMinValues32[readIndex.x + 1][readIndex.y]), 
																 min (cachedMinValues32[readIndex.x][readIndex.y + 1], cachedMinValues32[readIndex.x + 1][readIndex.y + 1]));
			cachedMaxValues16[writeIndex.x][writeIndex.y] = max (max (cachedMaxValues32[readIndex.x][readIndex.y], cachedMaxValues32[readIndex.x + 1][readIndex.y]), 
																 max (cachedMaxValues32[readIndex.x][readIndex.y + 1], cachedMaxValues32[readIndex.x + 1][readIndex.y + 1]));
			imageStore (LODMinZChain[1], writeIndex.xy, vec4(cachedMinValues16[writeIndex.x][writeIndex.y]));
			imageStore (LODMaxZChain[1], writeIndex.xy, vec4(cachedMaxValues16[writeIndex.x][writeIndex.y]));
		}

	memoryBarrier();
	barrier();

	ivec2 readIndex = ivec2 (gl_GlobalInvocationID.xy * 2);
	cachedMinValues8[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y] = min (min (cachedMinValues16[readIndex.x][readIndex.y], cachedMinValues16[readIndex.x + 1][readIndex.y]), 
																			  min (cachedMinValues16[readIndex.x][readIndex.y + 1], cachedMinValues16[readIndex.x + 1][readIndex.y + 1]));
	cachedMaxValues8[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y] = max (max (cachedMaxValues16[readIndex.x][readIndex.y], cachedMaxValues16[readIndex.x + 1][readIndex.y]), 
																			  max (cachedMaxValues16[readIndex.x][readIndex.y + 1], cachedMaxValues16[readIndex.x + 1][readIndex.y + 1]));
	imageStore (LODMinZChain[2], ivec2 (gl_GlobalInvocationID.xy), vec4(cachedMinValues8[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y]));
	imageStore (LODMaxZChain[2], ivec2 (gl_GlobalInvocationID.xy), vec4(cachedMaxValues8[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y]));

	if ( gl_GlobalInvocationID.x >= 4 || gl_GlobalInvocationID.y >= 4 ) return;

	memoryBarrier();
	barrier();

	readIndex = ivec2 (gl_GlobalInvocationID.xy * 2);
	cachedMinValues4[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y] = min (min (cachedMinValues8[readIndex.x][readIndex.y], cachedMinValues8[readIndex.x + 1][readIndex.y]), 
																			  min (cachedMinValues8[readIndex.x][readIndex.y + 1], cachedMinValues8[readIndex.x + 1][readIndex.y + 1]));
	cachedMaxValues4[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y] = max (max (cachedMaxValues8[readIndex.x][readIndex.y], cachedMaxValues8[readIndex.x + 1][readIndex.y]), 
																			  max (cachedMaxValues8[readIndex.x][readIndex.y + 1], cachedMaxValues8[readIndex.x + 1][readIndex.y + 1]));
	imageStore (LODMinZChain[3], ivec2 (gl_GlobalInvocationID.xy), vec4(cachedMinValues4[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y]));
	imageStore (LODMaxZChain[3], ivec2 (gl_GlobalInvocationID.xy), vec4(cachedMaxValues4[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y]));

	if ( gl_GlobalInvocationID.x >= 2 || gl_GlobalInvocationID.y >= 2 ) return;

	memoryBarrier();
	barrier();

	readIndex = ivec2 (gl_GlobalInvocationID.xy * 2);
	cachedMinValues2[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y] = min (min (cachedMinValues4[readIndex.x][readIndex.y], cachedMinValues4[readIndex.x + 1][readIndex.y]), 
																			  min (cachedMinValues4[readIndex.x][readIndex.y + 1], cachedMinValues4[readIndex.x + 1][readIndex.y + 1]));
	cachedMaxValues2[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y] = max (max (cachedMaxValues4[readIndex.x][readIndex.y], cachedMaxValues4[readIndex.x + 1][readIndex.y]), 
																			  max (cachedMaxValues4[readIndex.x][readIndex.y + 1], cachedMaxValues4[readIndex.x + 1][readIndex.y + 1]));
	imageStore (LODMinZChain[4], ivec2 (gl_GlobalInvocationID.xy), vec4(cachedMinValues2[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y]));
	imageStore (LODMaxZChain[4], ivec2 (gl_GlobalInvocationID.xy), vec4(cachedMaxValues2[gl_GlobalInvocationID.x][gl_GlobalInvocationID.y]));

	if ( gl_GlobalInvocationID.xy != uvec2(0) ) return;

	memoryBarrier();
	barrier();

	imageStore (LODMinZChain[5], ivec2(0), vec4(min (min (cachedMinValues2[0][0], cachedMinValues2[1][0]), min (cachedMinValues2[0][1], cachedMinValues2[1][1]))));
	imageStore (LODMaxZChain[5], ivec2(0), vec4(max (max (cachedMaxValues2[0][0], cachedMaxValues2[1][0]), max (cachedMaxValues2[0][1], cachedMaxValues2[1][1]))));
}