/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_scalar_block_layout : require

layout (local_size_x = 8, local_size_y = 8, local_size_z = 1) in;

shared uvec2 cachedInstTriID;
shared vec3 cachedE1, cachedE2, cachedE3;
shared vec3 cachedVel1, cachedVel2, cachedVel3;
shared vec3 cachedN1, cachedN2, cachedN3;

#define M_PI 3.1415926535
#define diffuseSampler sceneTextures[nonuniformEXT(uint(instanceInfo.props[InstID].diffOffset))]
#define normalSampler sceneTextures[nonuniformEXT(uint(instanceInfo.props[InstID].nrmOffset))]
#define roughnessAndSpecSampler sceneTextures[nonuniformEXT(uint(instanceInfo.props[InstID].rghOffset))]
#define heightmapSampler sceneTextures[nonuniformEXT(uint(instanceInfo.props[InstID].hgtOffset))]
#define specularSampler sceneTextures[nonuniformEXT(uint(instanceInfo.props[InstID].spcOffset))]

layout (scalar, binding = 0) uniform FrameMVPUBO
{
	mat4 projectionViewMatrix;
	vec4 lookEyeX;
	vec4 upEyeY;
	vec4 sideEyeZ;
	vec2 whrTanHalfFovY;
} frameMVP;

layout (scalar, binding = 1) uniform PrevFrameMVPUBO
{
	mat4 projectionViewMatrix;
	vec4 lookEyeX;
	vec4 upEyeY;
	vec4 sideEyeZ;
	vec2 whrTanHalfFovY;
} prevFrameMVP;

layout (binding = 2) uniform usampler2D visBufTriInfo;

layout (set = 1, binding = 0) uniform sampler2DArray sceneTextures[];

struct TriangleFromVertBufWide
{
	vec4 e1Col1;
	vec2 uv1;
	uint Norm1;
	vec4 e2Col2;
	vec2 uv2;
	uint Norm2;
	vec4 e3Col3;
	vec2 uv3;
	uint Norm3;
};

#define ReadTri(o,i,j) {uint triCount = giantVB.dat[i];\
						uint offsetToIndices = i + 2, offsetToVertices = 2 + (triCount * 3); offsetToVertices += i + ((24 - ((offsetToVertices * 4) % 24 /* sizeof(RasterVertex) */ )) / 4);\
						uint e1Offset = offsetToVertices + giantVB.dat[offsetToIndices + j * 3] * 6;\
						uint e2Offset = offsetToVertices + giantVB.dat[offsetToIndices + j * 3 + 1] * 6;\
						uint e3Offset = offsetToVertices + giantVB.dat[offsetToIndices + j * 3 + 2] * 6;\
						o.e1Col1 = vec4 (uintBitsToFloat(giantVB.dat[e1Offset]), uintBitsToFloat(giantVB.dat[e1Offset + 1]), uintBitsToFloat(giantVB.dat[e1Offset + 2]), uintBitsToFloat(giantVB.dat[e1Offset + 3]));\
						o.uv1 = unpackHalf2x16(giantVB.dat[e1Offset + 4]);\
						o.Norm1 = giantVB.dat[e1Offset + 5];\
						o.e2Col2 = vec4 (uintBitsToFloat(giantVB.dat[e2Offset]), uintBitsToFloat(giantVB.dat[e2Offset + 1]), uintBitsToFloat(giantVB.dat[e2Offset + 2]), uintBitsToFloat(giantVB.dat[e2Offset + 3]));\
						o.uv2 = unpackHalf2x16(giantVB.dat[e2Offset + 4]);\
						o.Norm2 = giantVB.dat[e2Offset + 5];\
						o.e3Col3 = vec4 (uintBitsToFloat(giantVB.dat[e3Offset]), uintBitsToFloat(giantVB.dat[e3Offset + 1]), uintBitsToFloat(giantVB.dat[e3Offset + 2]), uintBitsToFloat(giantVB.dat[e3Offset + 3]));\
						o.uv3 = unpackHalf2x16(giantVB.dat[e3Offset + 4]);\
						o.Norm3 = giantVB.dat[e3Offset + 5];}

struct InstanceProps
{
	vec3 geomMin;
	vec3 geomMax;
    vec3 attribs1;
    vec4 attribs2;
	uint16_t splatOffset;
	uint16_t diffOffset;
	uint16_t nrmOffset;
	uint16_t rghOffset;
	uint16_t hgtOffset;
	uint16_t spcOffset;
	uint idxVertOffset;
	uint transformOffset;
	uint prevTransformOffset;
};

layout (binding = 3, rgba32f) uniform writeonly image2D materialAttach;
layout (binding = 4, rgba32f) uniform writeonly image2D worldPosAttach;
layout (binding = 5, rgba32f) uniform writeonly image2D normAttach;
layout (binding = 6, r32ui) uniform uimage2D velocityAttach;

layout (scalar, set = 2, binding = 0) buffer InstanceInfoSSBO
{
	InstanceProps props[];
} instanceInfo;

layout(scalar, set = 2, binding = 1) buffer GiantVertBuffer
{
	uint dat[];
} giantVB;

layout (set = 2, binding = 2) buffer TransformsSSBO
{
	mat4 mats[];
} transforms;

struct TriangleAnimWeights
{
	vec4 bones1Weights1;
	vec4 bones2Weights2;
	vec4 bones3Weights3;
};

void GetTangentBiTangent(vec3 v_0, vec3 v_1, vec3 v_2, vec2 tex0, vec2 tex1, vec2 tex2, out vec3 x_1_out, out vec3 y_1_out)
{
	vec3 A = v_0 - v_1, B = v_2 - v_1;
	vec2 v1 = tex0 - tex1, v2 = tex2 - tex1, v3;
	vec3 origin, x_1, y_1;
	float a, b;

	float v1xv2y_v1yv2x = v1.x*v2.y - v1.y*v2.x;
	float inv_v1xv2y_v1yv2x;
	if (v1xv2y_v1yv2x != 0.0) inv_v1xv2y_v1yv2x = 1.0f / v1xv2y_v1yv2x;

	v3 = -tex1;
	if (v1xv2y_v1yv2x == 0.0)
		a = 1.0;
	else
		a = (v3.x*v2.y - v3.y*v2.x) * inv_v1xv2y_v1yv2x;
	if (v2.x != 0.0)
		b = (v3.x - a * v1.x) / v2.x;
	else
		b = (v3.y - a * v1.y) / v2.y;
	origin = v_1 + a * A + b * B;

	v3 = vec2(1.0, 0.0) - tex1;
	if (v1xv2y_v1yv2x == 0.0)
		a = 1.0;
	else
		a = (v3.x*v2.y - v3.y*v2.x) * inv_v1xv2y_v1yv2x;
	if (v2.x != 0.0)
		b = (v3.x - a * v1.x) / v2.x;
	else
		b = (v3.y - a * v1.y) / v2.y;

	x_1 = v_1 + a * A + b * B;

	v3 = vec2(0.0, 1.0) - tex1;
	if (v1xv2y_v1yv2x == 0.0)
		a = 1.0;
	else
		a = (v3.x*v2.y - v3.y*v2.x) * inv_v1xv2y_v1yv2x;
	if (v2.x != 0.0)
		b = (v3.x - a * v1.x) / v2.x;
	else
		b = (v3.y - a * v1.y) / v2.y;

	y_1 = v_1 + a * A + b * B;

	x_1_out = x_1 - origin;
	y_1_out = y_1 - origin;
}

uint toZSignXY(vec3 inpVec)
{
	uint retVal = ((uint((inpVec.x + 1.0) * 16383.0) << 16) | uint((inpVec.y + 1.0) * 32767.0));
	if (inpVec.z < 0.0) retVal |= 0x80000000u;
	return retVal;
}

vec3 fromZSignXY(uint inpPack)
{
	vec3 retVal;
	retVal.x = (float((inpPack & 0x7FFF0000u) >> 16) / 32766.0) * 2.0 - 1.0;
	retVal.y = (float(inpPack & 0x0000FFFFu) / 65534.0) * 2.0 - 1.0;
	vec2 xyVec = vec2(retVal.x, retVal.y);
	retVal.z = sqrt(clamp (1.0 - dot(xyVec, xyVec), 0.0, 1.0));
	if ((inpPack & 0x80000000u) != 0) retVal.z = -retVal.z;
	return retVal;
}

vec3 sampleTerrainWeights (uint InstID, vec2 curUV, vec4 dUVdxdy)
{
	vec3 terrainMap = textureGrad (diffuseSampler, vec3 (curUV, 3.0), dUVdxdy.xy, dUVdxdy.zw).rgb;
	terrainMap /= (terrainMap.x + terrainMap.y + terrainMap.z);
	return terrainMap;
}

// https://www.shadertoy.com/view/4djSRW by Dave Hoskins
float hash12(vec2 p)
{
	vec3 p3  = fract(vec3(p.xyx) * .1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}

// iq technique + suslik
// https://iquilezles.org/articles/texturerepetition/
// https://www.shadertoy.com/view/Xtl3zf
void computeDeTileOffsets (vec2 inCoord, out vec4 coordOffsets, out float mixFactor)
{
	inCoord *= 10.0;
	float k00 = hash12(floor(inCoord));
	float k01 = hash12(floor(inCoord) + vec2 (0.0, 1.0));
	float k10 = hash12(floor(inCoord) + vec2 (1.0, 0.0));
	float k11 = hash12(floor(inCoord) + vec2 (1.0, 1.0));
	vec2 inUVFrac = fract(inCoord);
	float k = mix(mix(k00, k01, inUVFrac.y), mix(k10, k11, inUVFrac.y), inUVFrac.x);

	float l = k*8.0;
	mixFactor = fract(l);

	float ia = floor(l+0.5);
	float ib = floor(l);
	mixFactor = min(mixFactor, 1.0-mixFactor)*2.0;

	coordOffsets.xy = sin(vec2(3.0,7.0)*ia);
	coordOffsets.zw = sin(vec2(3.0,7.0)*ib);
}

vec4 sampleDiffuse (vec3 inpWeights, bool isTerrain, vec3 surfNorm, vec3 PosW, uint InstID, vec2 curUV, vec4 dUVdxdy, vec4 coordOffsets, float mixFactor)
{
	if ( isTerrain )
	{
		vec2 planarUV;
		vec3 absNorm = abs(surfNorm);
		if ( absNorm.y > 0.7 )
			planarUV = PosW.xz;
		else if ( absNorm.x > 0.7 )
			planarUV = PosW.yz;
		else
			planarUV = PosW.xy;
		vec2 planarFactor = vec2 (33.33333) / vec2 (textureSize (diffuseSampler, 0).xy);
		vec2 curTerrainUV = planarUV * planarFactor;
		dUVdxdy *= planarFactor.xyxy;
		vec3 retVal = vec3 (0.0);

		vec3 colLayer2a = textureGrad(diffuseSampler, vec3 (curTerrainUV + coordOffsets.xy, 2.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer2b = textureGrad(diffuseSampler, vec3 (curTerrainUV + coordOffsets.zw, 2.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer2Diff = colLayer2a - colLayer2b;
		vec3 colLayer2 = mix(colLayer2a, colLayer2b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer2Diff.x + colLayer2Diff.y + colLayer2Diff.z)));

		vec3 colLayer1a = textureGrad(diffuseSampler, vec3 (curTerrainUV + coordOffsets.xy, 1.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer1b = textureGrad(diffuseSampler, vec3 (curTerrainUV + coordOffsets.zw, 1.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer1Diff = colLayer1a - colLayer1b;
		vec3 colLayer1 = mix(colLayer1a, colLayer1b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer1Diff.x + colLayer1Diff.y + colLayer1Diff.z)));

		vec3 colLayer0a = textureGrad(diffuseSampler, vec3 (curTerrainUV + coordOffsets.xy, 0.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer0b = textureGrad(diffuseSampler, vec3 (curTerrainUV + coordOffsets.zw, 0.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer0Diff = colLayer0a - colLayer0b;
		vec3 colLayer0 = mix(colLayer0a, colLayer0b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer0Diff.x + colLayer0Diff.y + colLayer0Diff.z)));

		retVal += colLayer2 * inpWeights.r;
		retVal += colLayer1 * inpWeights.g;
		retVal += colLayer0 * inpWeights.b;
		return vec4 (retVal, 1.0);
	}
	return textureGrad (diffuseSampler, vec3 (curUV, 0.0), dUVdxdy.xy, dUVdxdy.zw);
}

vec4 sampleSpecular (vec3 inpWeights, bool isTerrain, vec3 surfNorm, vec3 PosW, uint InstID, vec2 curUV, vec4 dUVdxdy, vec4 coordOffsets, float mixFactor)
{
	if ( isTerrain )
	{
		vec2 planarUV;
		vec3 absNorm = abs(surfNorm);
		if ( absNorm.y > 0.7 )
			planarUV = PosW.xz;
		else if ( absNorm.x > 0.7 )
			planarUV = PosW.yz;
		else
			planarUV = PosW.xy;
		vec2 planarFactor = vec2 (33.33333) / vec2 (textureSize (specularSampler, 0).xy);
		vec2 curTerrainUV = planarUV * planarFactor;
		dUVdxdy *= planarFactor.xyxy;
		vec3 retVal = vec3 (0.0);

		vec3 colLayer2a = textureGrad(specularSampler, vec3 (curTerrainUV + coordOffsets.xy, 2.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer2b = textureGrad(specularSampler, vec3 (curTerrainUV + coordOffsets.zw, 2.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer2Diff = colLayer2a - colLayer2b;
		vec3 colLayer2 = mix(colLayer2a, colLayer2b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer2Diff.x + colLayer2Diff.y + colLayer2Diff.z)));

		vec3 colLayer1a = textureGrad(specularSampler, vec3 (curTerrainUV + coordOffsets.xy, 1.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer1b = textureGrad(specularSampler, vec3 (curTerrainUV + coordOffsets.zw, 1.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer1Diff = colLayer1a - colLayer1b;
		vec3 colLayer1 = mix(colLayer1a, colLayer1b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer1Diff.x + colLayer1Diff.y + colLayer1Diff.z)));

		vec3 colLayer0a = textureGrad(specularSampler, vec3 (curTerrainUV + coordOffsets.xy, 0.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer0b = textureGrad(specularSampler, vec3 (curTerrainUV + coordOffsets.zw, 0.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer0Diff = colLayer0a - colLayer0b;
		vec3 colLayer0 = mix(colLayer0a, colLayer0b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer0Diff.x + colLayer0Diff.y + colLayer0Diff.z)));

		retVal += colLayer2 * inpWeights.r;
		retVal += colLayer1 * inpWeights.g;
		retVal += colLayer0 * inpWeights.b;
		return vec4 (retVal, 1.0);
	}
	return textureGrad (specularSampler, vec3 (curUV, 0.0), dUVdxdy.xy, dUVdxdy.zw);
}

vec3 sampleNormal (vec3 inpWeights, bool isTerrain, vec3 surfNorm, vec3 PosW, uint InstID, vec2 curUV, vec4 dUVdxdy, inout mat3 tanSpace, vec4 coordOffsets, float mixFactor)
{
	if ( isTerrain )
	{
		vec2 planarUV;
		vec3 absNorm = abs(surfNorm);
		if ( absNorm.y > 0.7 )
		{
			tanSpace[0] = vec3 (1.0, 0.0, 0.0);
			tanSpace[1] = vec3 (0.0, 0.0, 1.0);
			planarUV = PosW.xz;
		}
		else if ( absNorm.x > 0.7 )
		{
			tanSpace[0] = vec3 (0.0, 1.0, 0.0);
			tanSpace[1] = vec3 (0.0, 0.0, 1.0);
			planarUV = PosW.yz;
		}
		else
		{
			tanSpace[0] = vec3 (1.0, 0.0, 0.0);
			tanSpace[1] = vec3 (0.0, 1.0, 0.0);
			planarUV = PosW.xy;
		}
		vec2 planarFactor = vec2 (33.33333) / vec2 (textureSize (normalSampler, 0).xy);
		vec2 curTerrainUV = planarUV * planarFactor;
		dUVdxdy *= planarFactor.xyxy;
		vec3 retVal = vec3 (0.0);

		vec3 colLayer2a = normalize (textureGrad(normalSampler, vec3 (curTerrainUV + coordOffsets.xy, 2.0), dUVdxdy.xy, dUVdxdy.zw).xyz * 2.0 - vec3(1.0));
		vec3 colLayer2b = normalize (textureGrad(normalSampler, vec3 (curTerrainUV + coordOffsets.zw, 2.0), dUVdxdy.xy, dUVdxdy.zw).xyz * 2.0 - vec3(1.0));
		vec3 colLayer2Diff = colLayer2a - colLayer2b;
		vec3 colLayer2 = mix(colLayer2a, colLayer2b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer2Diff.x + colLayer2Diff.y + colLayer2Diff.z)));

		vec3 colLayer1a = normalize (textureGrad(normalSampler, vec3 (curTerrainUV + coordOffsets.xy, 1.0), dUVdxdy.xy, dUVdxdy.zw).xyz * 2.0 - vec3(1.0));
		vec3 colLayer1b = normalize (textureGrad(normalSampler, vec3 (curTerrainUV + coordOffsets.zw, 1.0), dUVdxdy.xy, dUVdxdy.zw).xyz * 2.0 - vec3(1.0));
		vec3 colLayer1Diff = colLayer1a - colLayer1b;
		vec3 colLayer1 = mix(colLayer1a, colLayer1b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer1Diff.x + colLayer1Diff.y + colLayer1Diff.z)));

		vec3 colLayer0a = normalize (textureGrad(normalSampler, vec3 (curTerrainUV + coordOffsets.xy, 0.0), dUVdxdy.xy, dUVdxdy.zw).xyz * 2.0 - vec3(1.0));
		vec3 colLayer0b = normalize (textureGrad(normalSampler, vec3 (curTerrainUV + coordOffsets.zw, 0.0), dUVdxdy.xy, dUVdxdy.zw).xyz * 2.0 - vec3(1.0));
		vec3 colLayer0Diff = colLayer0a - colLayer0b;
		vec3 colLayer0 = mix(colLayer0a, colLayer0b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer0Diff.x + colLayer0Diff.y + colLayer0Diff.z)));

		retVal += normalize (colLayer2) * inpWeights.r;
		retVal += normalize (colLayer1) * inpWeights.g;
		retVal += normalize (colLayer0) * inpWeights.b;
		return normalize (retVal);
	}
	return 2.0 * textureGrad (normalSampler, vec3 (curUV, 0.0), dUVdxdy.xy, dUVdxdy.zw).rgb - vec3 (1.0);
}

vec4 sampleRoughness (vec3 inpWeights, bool isTerrain, vec3 surfNorm, vec3 PosW, uint InstID, vec2 curUV, vec4 dUVdxdy, vec4 coordOffsets, float mixFactor)
{
	if ( isTerrain )
	{
		vec2 planarUV;
		vec3 absNorm = abs(surfNorm);
		if ( absNorm.y > 0.7 )
			planarUV = PosW.xz;
		else if ( absNorm.x > 0.7 )
			planarUV = PosW.yz;
		else
			planarUV = PosW.xy;
		vec2 planarFactor = vec2 (33.33333) / vec2 (textureSize (roughnessAndSpecSampler, 0).xy);
		vec2 curTerrainUV = planarUV * planarFactor;
		dUVdxdy *= planarFactor.xyxy;
		vec3 retVal = vec3 (0.0);

		vec3 colLayer2a = textureGrad(roughnessAndSpecSampler, vec3 (curTerrainUV + coordOffsets.xy, 2.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer2b = textureGrad(roughnessAndSpecSampler, vec3 (curTerrainUV + coordOffsets.zw, 2.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer2Diff = colLayer2a - colLayer2b;
		vec3 colLayer2 = mix(colLayer2a, colLayer2b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer2Diff.x + colLayer2Diff.y + colLayer2Diff.z)));

		vec3 colLayer1a = textureGrad(roughnessAndSpecSampler, vec3 (curTerrainUV + coordOffsets.xy, 1.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer1b = textureGrad(roughnessAndSpecSampler, vec3 (curTerrainUV + coordOffsets.zw, 1.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer1Diff = colLayer1a - colLayer1b;
		vec3 colLayer1 = mix(colLayer1a, colLayer1b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer1Diff.x + colLayer1Diff.y + colLayer1Diff.z)));

		vec3 colLayer0a = textureGrad(roughnessAndSpecSampler, vec3 (curTerrainUV + coordOffsets.xy, 0.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer0b = textureGrad(roughnessAndSpecSampler, vec3 (curTerrainUV + coordOffsets.zw, 0.0), dUVdxdy.xy, dUVdxdy.zw).xyz;
		vec3 colLayer0Diff = colLayer0a - colLayer0b;
		vec3 colLayer0 = mix(colLayer0a, colLayer0b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer0Diff.x + colLayer0Diff.y + colLayer0Diff.z)));

		retVal += colLayer2 * inpWeights.r;
		retVal += colLayer1 * inpWeights.g;
		retVal += colLayer0 * inpWeights.b;
		return vec4 (retVal, 1.0);
	}
	return textureGrad (roughnessAndSpecSampler, vec3 (curUV, 0.0), dUVdxdy.xy, dUVdxdy.zw);
}

bool getHasNrmMap (uint packedFlags)
{
	return (packedFlags & 0x00000001) != 0;
}

bool getHasRghMap (uint packedFlags)
{
	return (packedFlags & 0x00000002) != 0;
}

bool getSmooth (uint packedFlags)
{
	return (packedFlags & 0x00000004) != 0;
}

bool getDielectric (uint packedFlags)
{
	return (packedFlags & 0x00000040) != 0;
}

bool getDoubleSided (uint packedFlags)
{
	return (packedFlags & 0x00000008) != 0;
}

bool getParallaxOcclusionMapping (uint packedFlags)
{
	return (packedFlags & 0x00000100) != 0;
}

bool getHasPerVertexVelocity (uint packedFlags)
{
	return (packedFlags & 0x00000800) != 0;
}

bool isViewerRelative (uint packedFlags)
{
	return (packedFlags & 0x00001000) != 0;
}

float packEmissivityRefractiveIndexDielectric (uint InstID, uint packedFlags)
{
	vec4 retVal;
	retVal.x = clamp (instanceInfo.props[InstID].attribs1.y, 0.0, 25.5) / 25.5;
	retVal.y = clamp (instanceInfo.props[InstID].attribs1.z, 0.0, 4.0) / 4.0;
	retVal.z = getDielectric (packedFlags) ? 1.0 : 0.0;
	return uintBitsToFloat (packUnorm4x8 (retVal));
}

vec3 barycentricCoords(vec3 p, vec3 a, vec3 b, vec3 c)
{
    vec3 v0 = b - a, v1 = c - a, v2 = p - a;
    float d00 = dot(v0, v0);
    float d01 = dot(v0, v1);
    float d11 = dot(v1, v1);
    float d20 = dot(v2, v0);
    float d21 = dot(v2, v1);
    float invDenom = 1.0 / (d00 * d11 - d01 * d01);
    float v = (d11 * d20 - d01 * d21) * invDenom;
    float w = (d00 * d21 - d01 * d20) * invDenom;
    float u = 1.0 - v - w;
	return vec3 (u,v,w);
}

vec2 parallaxMapMarch (vec3 view, mat3 tanSpace, float heightMapDisplaceFactor, uint InstID, vec2 curUV, vec4 dUVdxdy, out vec3 tanSpaceNorm)
{
	vec2 pomUV = curUV, optimalUV = curUV;

	vec3 viewNormTanSpace = inverse(tanSpace) * view;
	float viewNormTanSpaceProjLen = length (viewNormTanSpace.xy);
	if ( viewNormTanSpaceProjLen == 0.0 ) return curUV;
	vec2 viewNormTanSpaceProjNorm = viewNormTanSpace.xy / viewNormTanSpaceProjLen;
	float marchLen = length(vec2 (1.0)/vec2 (textureSize(heightmapSampler, 0).xy));
	float shrinkAmount = dot(tanSpace[2], normalize (view));
	shrinkAmount *= shrinkAmount;
	shrinkAmount *= shrinkAmount;
	vec2 tanSpaceMarchDir = normalize (viewNormTanSpace.xy) * marchLen * (1.0 - shrinkAmount);
	float ratio = viewNormTanSpace.z / (viewNormTanSpaceProjLen * heightMapDisplaceFactor);
	float queryHeight = 0.0, calcHeight = 0.0, cachedHeightDiff = 0.0;
	float cachedI = 0.0;
	[[unroll]]
	for (uint i = 0; i != 40; i++)
	{
		pomUV += tanSpaceMarchDir;
		queryHeight = textureGrad (heightmapSampler, vec3 (pomUV, 0.0), dUVdxdy.xy, dUVdxdy.zw).r;
		calcHeight = float (i) * marchLen * ratio;
		if ( queryHeight >= calcHeight )
		{
			optimalUV = pomUV;
			cachedHeightDiff = calcHeight - queryHeight;
			cachedI = float(i);
		}
		if ( calcHeight >= 1.0 ) break;
	}
	float nextHeightDiff = (cachedI + 1.0) * marchLen * ratio - textureGrad (heightmapSampler, vec3 (optimalUV + tanSpaceMarchDir, 0.0), dUVdxdy.xy, dUVdxdy.zw).r;
	optimalUV = mix (optimalUV, optimalUV + tanSpaceMarchDir, clamp (cachedHeightDiff / (cachedHeightDiff - nextHeightDiff), 0.0, 1.0));
	vec2 singlePix = vec2 (1.0) / vec2 (textureSize(heightmapSampler, 0).xy);
	vec3 heightFieldTan = vec3 (singlePix.x, 0.0, (textureGrad (heightmapSampler, vec3 (optimalUV + vec2 (singlePix.x * 0.5, 0.0), 0.0), dUVdxdy.xy, dUVdxdy.zw).r - textureGrad (heightmapSampler, vec3 (optimalUV - vec2 (singlePix.x * 0.5, 0.0), 0.0), dUVdxdy.xy, dUVdxdy.zw).r) * 0.01 * heightMapDisplaceFactor);
	vec3 heightFieldBiTan = vec3 (0.0, singlePix.y, (textureGrad (heightmapSampler, vec3 (optimalUV + vec2 (0.0, singlePix.y * 0.5), 0.0), dUVdxdy.xy, dUVdxdy.zw).r - textureGrad (heightmapSampler, vec3 (optimalUV - vec2 (0.0, singlePix.y * 0.5), 0.0), dUVdxdy.xy, dUVdxdy.zw).r) * 0.01 * heightMapDisplaceFactor);
	tanSpaceNorm = normalize (cross(heightFieldTan, heightFieldBiTan));
	if ( tanSpaceNorm.z < 0.0 ) tanSpaceNorm = -tanSpaceNorm;
	return optimalUV;
}

mat4 DirectionTransform(mat4 transform)
{
	mat4 retVal = mat4(1.0);
	retVal[0].xyz = cross(transform[1].xyz, transform[2].xyz);
	retVal[1].xyz = cross(transform[2].xyz, transform[0].xyz);
	retVal[2].xyz = cross(transform[0].xyz, transform[1].xyz);
	return retVal;
}

vec3 projectCoord (vec3 coord, mat4 MVP, vec3 eyeLoc)
{
	vec4 pCoord = MVP * vec4 (coord - eyeLoc, 1.0);
	pCoord.xyz = pCoord.xyz/pCoord.w;
	pCoord.xy = (pCoord.xy + vec2 (1.0)) * 0.5;
	return pCoord.xyz;
}

vec3 unpackVertexVelocity(float inpPackedColor)
{
	vec3 packedVelChannels = unpackUnorm4x8 (floatBitsToUint(inpPackedColor)).yzw;
	uint packedVelChannelZSignX = uint(packedVelChannels.x * 255.0);
	vec2 xyVec = vec2 ((float(packedVelChannelZSignX & 0x7F) / 127.0) * 2.0 - 1.0, packedVelChannels.y * 2.0 - 1.0);
	float velZ = sqrt(clamp (1.0 - dot(xyVec, xyVec), 0.0, 1.0));
	if ((packedVelChannelZSignX & 0x80) != 0) velZ = -velZ;
	return packedVelChannels.z * 25.5 * vec3 (xyVec, velZ);
}

void main()
{
	bool returnFunc = false;
	if ( int(gl_GlobalInvocationID.x) >= textureSize(visBufTriInfo, 0).x || int(gl_GlobalInvocationID.y) >= textureSize(visBufTriInfo, 0).y )
	{
		returnFunc = true;
	}

	uint InstID = 0u, TriID = 0u;
	uvec2 triInfoFetch = uvec2 (0);
	vec2 outputSize = vec2 (0.0), inUV = vec2(0.0);
	if (!returnFunc)
	{
		outputSize = vec2 (textureSize(visBufTriInfo, 0).xy);
		inUV = (vec2(gl_GlobalInvocationID.xy) + vec2(0.5)) / outputSize;
		ivec2 fetchCoord = ivec2 (inUV * outputSize);
		triInfoFetch = texelFetch(visBufTriInfo, fetchCoord, 0).xy;
		InstID = triInfoFetch.x;
		TriID = triInfoFetch.y;
		
		if ( triInfoFetch.xy == uvec2(0xFFFFFFFF) )
		{
			imageStore (materialAttach, ivec2 (gl_GlobalInvocationID.xy), vec4 (0.0));
			imageStore (worldPosAttach, ivec2 (gl_GlobalInvocationID.xy), vec4 (0.0));
			imageStore (normAttach, ivec2 (gl_GlobalInvocationID.xy), vec4 (0.0));
			returnFunc = true;
		}
	}
	
	uint packedFlags = floatBitsToUint (instanceInfo.props[InstID].attribs1.x);

	vec3 curTriE1, curTriE2, curTriE3;
	vec3 velE1, velE2, velE3;
	vec3 curTriN1, curTriN2, curTriN3;
	TriangleFromVertBufWide curTri;
	if (!returnFunc)
	{
		ReadTri (curTri, instanceInfo.props[InstID].idxVertOffset, TriID);
		if (gl_LocalInvocationID.xy == uvec2 (0))
		{
			cachedInstTriID = triInfoFetch;
			cachedE1 = (transforms.mats[instanceInfo.props[InstID].transformOffset] * vec4 (curTri.e1Col1.xyz, 1.0)).xyz;
			cachedE2 = (transforms.mats[instanceInfo.props[InstID].transformOffset] * vec4 (curTri.e2Col2.xyz, 1.0)).xyz;
			cachedE3 = (transforms.mats[instanceInfo.props[InstID].transformOffset] * vec4 (curTri.e3Col3.xyz, 1.0)).xyz;
			cachedVel1 = cachedVel2 = cachedVel3 = vec3 (0.0);
			if (getHasPerVertexVelocity(packedFlags))
			{
				cachedVel1 = unpackVertexVelocity(curTri.e1Col1.w);
				cachedVel2 = unpackVertexVelocity(curTri.e2Col2.w);
				cachedVel3 = unpackVertexVelocity(curTri.e3Col3.w);
			}
			mat4 transformDT = DirectionTransform(transforms.mats[instanceInfo.props[InstID].transformOffset]);
			cachedN1 = normalize((transformDT * vec4 (fromZSignXY (curTri.Norm1), 1.0)).xyz);
			cachedN2 = normalize((transformDT * vec4 (fromZSignXY (curTri.Norm2), 1.0)).xyz);
			cachedN3 = normalize((transformDT * vec4 (fromZSignXY (curTri.Norm3), 1.0)).xyz);
		}
	}
	
	memoryBarrier();
	barrier();
	
	if (returnFunc) return ;
	
	if (cachedInstTriID == triInfoFetch)
	{
		curTriE1 = cachedE1;
		curTriE2 = cachedE2;
		curTriE3 = cachedE3;
		velE1 = cachedVel1;
		velE2 = cachedVel2;
		velE3 = cachedVel3;
		curTriN1 = cachedN1;
		curTriN2 = cachedN2;
		curTriN3 = cachedN3;
	}
	else
	{
		curTriE1 = (transforms.mats[instanceInfo.props[InstID].transformOffset] * vec4 (curTri.e1Col1.xyz, 1.0)).xyz;
		curTriE2 = (transforms.mats[instanceInfo.props[InstID].transformOffset] * vec4 (curTri.e2Col2.xyz, 1.0)).xyz;
		curTriE3 = (transforms.mats[instanceInfo.props[InstID].transformOffset] * vec4 (curTri.e3Col3.xyz, 1.0)).xyz;
		velE1 = velE2 = velE3 = vec3 (0.0);
		if (getHasPerVertexVelocity(packedFlags))
		{
			velE1 = unpackVertexVelocity(curTri.e1Col1.w);
			velE2 = unpackVertexVelocity(curTri.e2Col2.w);
			velE3 = unpackVertexVelocity(curTri.e3Col3.w);
		}
		mat4 transformDT = DirectionTransform(transforms.mats[instanceInfo.props[InstID].transformOffset]);
		curTriN1 = normalize((transformDT * vec4 (fromZSignXY (curTri.Norm1), 1.0)).xyz);
		curTriN2 = normalize((transformDT * vec4 (fromZSignXY (curTri.Norm2), 1.0)).xyz);
		curTriN3 = normalize((transformDT * vec4 (fromZSignXY (curTri.Norm3), 1.0)).xyz);
	}
	
	vec2 pixelFootPrint = vec2(1.0) / outputSize;
	vec3 viewEye = vec3 (frameMVP.lookEyeX.a, frameMVP.upEyeY.a, frameMVP.sideEyeZ.a);	
	vec3 curFNorm = normalize (cross (curTriE1 - curTriE2, curTriE3 - curTriE2));
	float topIsectTime = dot (curFNorm, curTriE1) - dot (viewEye, curFNorm);
	vec2 curRayUV = inUV * 2.0 - vec2 (1.0);
	vec2 rayDiff1UV = (inUV + vec2 (pixelFootPrint.x, 0.0)) * 2.0 - vec2 (1.0);
	vec2 rayDiff2UV = (inUV + vec2 (0.0, pixelFootPrint.y)) * 2.0 - vec2 (1.0);
	vec3 curRay = frameMVP.lookEyeX.xyz - curRayUV.y * frameMVP.upEyeY.xyz * frameMVP.whrTanHalfFovY.y - curRayUV.x * frameMVP.sideEyeZ.xyz * frameMVP.whrTanHalfFovY.y * frameMVP.whrTanHalfFovY.x;
	vec3 rayDiff1 = frameMVP.lookEyeX.xyz - rayDiff1UV.y * frameMVP.upEyeY.xyz * frameMVP.whrTanHalfFovY.y - rayDiff1UV.x * frameMVP.sideEyeZ.xyz * frameMVP.whrTanHalfFovY.y * frameMVP.whrTanHalfFovY.x;
	vec3 rayDiff2 = frameMVP.lookEyeX.xyz - rayDiff2UV.y * frameMVP.upEyeY.xyz * frameMVP.whrTanHalfFovY.y - rayDiff2UV.x * frameMVP.sideEyeZ.xyz * frameMVP.whrTanHalfFovY.y * frameMVP.whrTanHalfFovY.x;
	vec3 curPos = viewEye + (topIsectTime/dot (curRay, curFNorm)) * curRay;
	vec3 isect1 = viewEye + (topIsectTime/dot (rayDiff1, curFNorm)) * rayDiff1;
	vec3 isect2 = viewEye + (topIsectTime/dot (rayDiff2, curFNorm)) * rayDiff2;
	vec3 curIsectBary = barycentricCoords (curPos, curTriE1, curTriE2, curTriE3);
	vec3 isect1Bary = barycentricCoords (isect1, curTriE1, curTriE2, curTriE3);
	vec3 isect2Bary = barycentricCoords (isect2, curTriE1, curTriE2, curTriE3);
	vec2 curUV = curTri.uv1 * curIsectBary.x + curTri.uv2 * curIsectBary.y + curTri.uv3 * curIsectBary.z;
	vec2 rightUV  = curTri.uv1 * isect1Bary.x + curTri.uv2 * isect1Bary.y + curTri.uv3 * isect1Bary.z;
	vec2 bottomUV = curTri.uv1 * isect2Bary.x + curTri.uv2 * isect2Bary.y + curTri.uv3 * isect2Bary.z;
	vec4 dUVdxdy = vec4 (rightUV - curUV, bottomUV - curUV);

	vec3 prevPos = curPos;
	if (instanceInfo.props[InstID].prevTransformOffset != 0xFFFFFFFFu)
		prevPos = (transforms.mats[instanceInfo.props[InstID].prevTransformOffset] * vec4 (curTri.e1Col1.xyz * curIsectBary.x + curTri.e2Col2.xyz * curIsectBary.y + curTri.e3Col3.xyz * curIsectBary.z, 1.0)).xyz;
	else if (getHasPerVertexVelocity(packedFlags))
		prevPos = curPos - (velE1 * curIsectBary.x + velE2 * curIsectBary.y + velE3 * curIsectBary.z);
	bool viewerRelative = isViewerRelative(packedFlags);

	vec3 prevProjectedCoord = projectCoord (prevPos, prevFrameMVP.projectionViewMatrix, vec3 (prevFrameMVP.lookEyeX.a, prevFrameMVP.upEyeY.a, prevFrameMVP.sideEyeZ.a));
	vec2 velocity = prevProjectedCoord.xy * vec2 (imageSize (velocityAttach).xy) - vec2(gl_GlobalInvocationID.xy);
	float velLen = length(velocity); vec2 velNorm = velocity / max (velLen, 0.001);
	if (velLen > 127.0) { velocity = velNorm * 127.0; velLen = 127.0; }

	vec3 curNorm = curTriN1 * curIsectBary.x + curTriN2 * curIsectBary.y + curTriN3 * curIsectBary.z;
	if ( dot (curFNorm, curNorm) < 0.0 ) curFNorm = -curFNorm;
	curNorm = normalize (curNorm);
	if ( getDoubleSided (packedFlags) && dot (viewEye - curTriE1, curFNorm) < 0.0 )
	{
		curNorm = -curNorm;
		curFNorm = -curFNorm;
	}
	mat3 tanSpace, unormTanSpace;
	GetTangentBiTangent (curTriE1, curTriE2, curTriE3, curTri.uv1, curTri.uv2, curTri.uv3, tanSpace[0], tanSpace[1]);
	unormTanSpace[0] = tanSpace[0];
	unormTanSpace[1] = tanSpace[1];
	unormTanSpace[2] = getSmooth(packedFlags) ? curNorm : curFNorm;
	tanSpace[0] = normalize (tanSpace[0]);
	tanSpace[1] = normalize (tanSpace[1]);
	tanSpace[2] = getSmooth(packedFlags) ? curNorm : curFNorm;

	vec4 coordOffsets = vec4(0.0);
	float mixFactor = 0.0;
	vec3 terrainSampleWeights = vec3 (0.0);
	bool isTerrain = textureSize (diffuseSampler, 0).z > 1;
	if ( isTerrain )
	{
		terrainSampleWeights = sampleTerrainWeights (InstID, curUV, dUVdxdy);
		computeDeTileOffsets (curUV, coordOffsets, mixFactor);
	}

	vec3 heightFieldNorm;
	bool isParallaxMapping = getParallaxOcclusionMapping (packedFlags);
	if (isParallaxMapping)
		curUV = parallaxMapMarch(viewEye - curPos, unormTanSpace, instanceInfo.props[InstID].attribs2.z, InstID, curUV, dUVdxdy, heightFieldNorm);

	vec4 diffFetch = sampleDiffuse (terrainSampleWeights, isTerrain, curFNorm, curPos, InstID, curUV, dUVdxdy, coordOffsets, mixFactor);
	vec4 specFetch = sampleSpecular (terrainSampleWeights, isTerrain, curFNorm, curPos, InstID, curUV, dUVdxdy, coordOffsets, mixFactor);
	vec4 roughFetch = vec4 (1.0, 1.0, 0.0, 0.0);
	if ( getHasRghMap (packedFlags) ) roughFetch = sampleRoughness (terrainSampleWeights, isTerrain, curFNorm, curPos, InstID, curUV, dUVdxdy, coordOffsets, mixFactor);

	vec3 finalNorm;
	if (isParallaxMapping)
		finalNorm = normalize (tanSpace * heightFieldNorm);
	else if ( getHasNrmMap (packedFlags) )
	{
		vec3 normFetch = sampleNormal (terrainSampleWeights, isTerrain, curFNorm, curPos, InstID, curUV, dUVdxdy, tanSpace, coordOffsets, mixFactor);
		finalNorm = normalize (tanSpace * normFetch);
	}
	else
		finalNorm = tanSpace[2];

	imageStore (materialAttach, ivec2 (gl_GlobalInvocationID.xy), vec4 (uintBitsToFloat (packUnorm4x8 (diffFetch)), uintBitsToFloat (packUnorm4x8 (specFetch)), uintBitsToFloat (packUnorm4x8 (roughFetch)), packEmissivityRefractiveIndexDielectric (InstID, packedFlags)));
	imageStore (worldPosAttach, ivec2 (gl_GlobalInvocationID.xy), vec4 (curPos, 0.0));
	imageStore (normAttach, ivec2 (gl_GlobalInvocationID.xy), vec4 (uintBitsToFloat (toZSignXY (finalNorm)),
														   uintBitsToFloat (toZSignXY (tanSpace[2])),
														   uintBitsToFloat (toZSignXY (tanSpace[0])),
														   uintBitsToFloat (toZSignXY (tanSpace[1]))));

	uint velWrite = viewerRelative ? 0xFFFFFFFFu : (((int(velocity.x) + 127) << 8) | (int(velocity.y) + 127));
	imageStore (velocityAttach, ivec2 (gl_GlobalInvocationID.xy), uvec4 (velWrite, 0, 0, 0));
}