/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_scalar_block_layout : require

#define HIGHOMEGA_ZONE_VOXELIZE_COARSENESS 1.0

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

struct ParticleItemWide
{
	vec3 pos;
	vec3 velocity;
	vec3 xAxis;
	vec3 yAxis;
	vec4 alphaHealthFadeRateScaleRate;
	float scale;
	float deathRate;
	bool sizeXAxisToVel;
	float prevDeltaT;
	float angSpeed;
};

#define ReadSourceParticle(o,j,k) {o.pos = particles[j].item[k].pos;\
								   o.velocity = fromZSignXY (particles[j].item[k].velocityDir) * unpackHalf2x16(particles[j].item[k].scaleLinSpeed).y;\
								   o.xAxis = fromZSignXY (particles[j].item[k].xAxis);\
								   o.yAxis = fromZSignXY (particles[j].item[k].yAxis);\
								   o.alphaHealthFadeRateScaleRate = vec4(float(uint(particles[j].item[k].alpha))/255.0, float(uint(particles[j].item[k].health))/255.0, float(uint(particles[j].item[k].fadeRate))/255.0, unpackHalf2x16(particles[j].item[k].scaleRateFlagsPrevDeltaT).x);\
								   o.scale = unpackHalf2x16 (particles[j].item[k].scaleLinSpeed).x;\
								   o.deathRate = float(uint(particles[j].item[k].deathRate))/255.0;\
								   o.sizeXAxisToVel = ((particles[j].item[k].scaleRateFlagsPrevDeltaT & 0x0000FF00u) >> 8) == 1u;\
								   o.prevDeltaT = float(particles[j].item[k].scaleRateFlagsPrevDeltaT & 0x000000FFu)/255.0;\
								   o.angSpeed = particles[j].item[k].angSpeed;}

#define StoreParticle(i,j,k) {particles[j].item[k].pos = i.pos;\
							 float STOREPARTICLE_velocityLen = length(i.velocity);\
							 vec3 STOREPARTICLE_velocityNorm = i.velocity;\
							 if (STOREPARTICLE_velocityLen > 0.0) STOREPARTICLE_velocityNorm /= STOREPARTICLE_velocityLen;\
							 particles[j].item[k].velocityDir = toZSignXY (STOREPARTICLE_velocityNorm);\
							 particles[j].item[k].xAxis = toZSignXY (i.xAxis);\
							 particles[j].item[k].yAxis = toZSignXY (i.yAxis);\
							 particles[j].item[k].alpha = uint8_t(uint(i.alphaHealthFadeRateScaleRate.x * 255.0));\
							 particles[j].item[k].health = uint8_t(uint(i.alphaHealthFadeRateScaleRate.y * 255.0));\
							 particles[j].item[k].fadeRate = uint8_t(uint(i.alphaHealthFadeRateScaleRate.z * 255.0));\
							 particles[j].item[k].deathRate = uint8_t(uint(i.deathRate * 255.0));\
							 particles[j].item[k].scaleLinSpeed = packHalf2x16 (vec2(i.scale, STOREPARTICLE_velocityLen));\
							 particles[j].item[k].scaleRateFlagsPrevDeltaT = packHalf2x16 (vec2(i.alphaHealthFadeRateScaleRate.w, uintBitsToFloat(((i.sizeXAxisToVel ? 1u : 0u) << 8) | (uint(ceil(clamp (emitterParams[nonuniformEXT(gl_GlobalInvocationID.y)].params.deathRateVarInitialScaleInitialAlphaCurTime.a, 0.0, 1.0) * 255.0)) & 0x000000FFu))));\
							 particles[j].item[k].angSpeed = i.angSpeed;}

uint toZSignXY(vec3 inpVec)
{
	uint retVal = ((uint((inpVec.x + 1.0) * 16383.0) << 16) | uint((inpVec.y + 1.0) * 32767.0));
	if (inpVec.z < 0.0) retVal |= 0x80000000u;
	return retVal;
}

vec3 fromZSignXY(uint inpPack)
{
	vec3 retVal;
	retVal.x = (float((inpPack & 0x7FFF0000u) >> 16) / 32766.0) * 2.0 - 1.0;
	retVal.y = (float(inpPack & 0x0000FFFFu) / 65534.0) * 2.0 - 1.0;
	vec2 xyVec = vec2(retVal.x, retVal.y);
	retVal.z = sqrt(clamp (1.0 - dot(xyVec, xyVec), 0.0, 1.0));
	if ((inpPack & 0x80000000u) != 0) retVal.z = -retVal.z;
	return retVal;
}

struct ParticleItem
{
	vec3 pos;
	uint velocityDir;
	uint xAxis;
	uint yAxis;
	uint8_t alpha;
	uint8_t health;
	uint8_t fadeRate;
	uint8_t deathRate;
	uint scaleLinSpeed;
	uint scaleRateFlagsPrevDeltaT;
	float angSpeed;
};

layout(scalar, set = 0, binding = 0) buffer ParticlesSSBO
{
	ParticleItem item[];
} particles[];

struct EmitterParams
{
	vec4 posLinSpeedBase;
	vec4 dirGravDirGravLenLinSpeedVar;
	vec4 radAngSpeedBaseAngSpeedVarFadeRateBase;
	vec4 fadeRateVarScaleRateBaseScaleRateVarDeathRateBase;
	vec4 deathRateVarInitialScaleInitialAlphaCurTime;
	uint numParticles;
	uint elasticitySpreadFlags;
};

layout (scalar, set = 1, binding = 0) buffer EmitterParamsSSBO
{
	EmitterParams params;
} emitterParams[];

#define currentEmitter emitterParams[nonuniformEXT(gl_GlobalInvocationID.y)]

struct leafTransformInfo
{
	mat4 transMat;
	vec4 bMin;
	vec4 bMax;
};

layout (set = 2, binding = 0) buffer leafTransformInfoSSBO
{
	leafTransformInfo leaves[];
} transInfo;

struct GridLeafNode
{
	vec4 leafMinMorton;
	vec4 leafMaxLeafId;
};

layout (set = 2, binding = 1) buffer GridLeafNodeSSBO
{
	GridLeafNode nodes[];
} GridLeafNodeArr;

struct CWBVHInternalNode
{
	uvec4 n0;
	uvec4 n1;
	uvec4 n2;
	uvec4 n3;
	uvec4 n4;
};

layout (set = 2, binding = 2) buffer CWBVHInternalNodeSSBO
{
	CWBVHInternalNode nodes[];
} CWBVHNodeArr;

layout (set = 3, binding = 0, rgba8) uniform readonly image3D grids[];

bool rayBoxIntersectTime (vec3 l1,vec3 invm,vec3 bmin,vec3 bmax, out float tMin, out float tMax)
{
	vec3 bmin_l1 = (bmin - l1)*invm;
	vec3 bmax_l1 = (bmax - l1)*invm;
	vec3 minVec = min (bmin_l1, bmax_l1);
	vec3 maxVec = max (bmin_l1, bmax_l1);

	float tmin = max(max(minVec.x, minVec.y), minVec.z);
	float tmax = min(min(maxVec.x, maxVec.y), maxVec.z);

	bool retVal = ((tmax >= tmin) && (tmin < 1.0) && (tmax > 0.0));
	tMin = tmin;
	tMax = tmax;
	return retVal;
}

mat4 DirectionTransform(mat4 transform)
{
	mat4 retVal = mat4(1.0);
	retVal[0].xyz = cross(transform[1].xyz, transform[2].xyz);
	retVal[1].xyz = cross(transform[2].xyz, transform[0].xyz);
	retVal[2].xyz = cross(transform[0].xyz, transform[1].xyz);
	return retVal;
}

vec3 rayBoxIntersectTMin (vec3 l1,vec3 invm,vec3 bmin,vec3 bmax)
{
	vec3 bmin_l1 = (bmin - l1)*invm;
	vec3 bmax_l1 = (bmax - l1)*invm;
	return min (bmin_l1, bmax_l1);
}

vec3 getBoxNormal(vec3 rayDir, vec3 tMinComponent)
{
	return -sign(rayDir) * step(tMinComponent.yzx, tMinComponent.xyz) * step(tMinComponent.zxy, tMinComponent.xyz);
}

bool TraceGridNonEmissive(vec3 p1, inout vec3 p2, inout vec3 voxCent, vec3 boxMin, vec3 boxMax, uint gridId, inout vec4 packedMat, inout vec3 outNorm)
{
	vec3 m = p2 - p1;
	vec3 p2_objspace;
	vec3 invm = vec3(1.0)/m;
	float tmin, tmax;
	bool orientedBox = false;
	if ( rayBoxIntersectTime (p1, invm, boxMin, boxMax, tmin, tmax) )
	{
		vec3 pmin = p1 + clamp (tmin, 0.0, 1.0) * m;
		vec3 pmax = p1 + clamp (tmax, 0.0, 1.0) * m;
		if (transInfo.leaves[gridId].transMat != mat4(1.0))
		{
			orientedBox = true;
			mat4 invTransMat = inverse(transInfo.leaves[gridId].transMat);
			p1 = (invTransMat * vec4 (p1, 1.0)).xyz;
			p2_objspace = (invTransMat * vec4 (p2, 1.0)).xyz;
			m = p2_objspace - p1;
			invm = vec3(1.0)/m;
			boxMin = transInfo.leaves[gridId].bMin.xyz;
			boxMax = transInfo.leaves[gridId].bMax.xyz;
			if ( rayBoxIntersectTime (p1, invm, boxMin, boxMax, tmin, tmax) )
			{
				pmin = p1 + clamp (tmin, 0.0, 1.0) * m;
				pmax = p1 + clamp (tmax, 0.0, 1.0) * m;
			}
			else
				return false;
		}

		vec3 pdir = pmax - pmin;
		float plen = length (pdir);
		if (plen == 0.0) return false;
		vec3 pdirNorm = pdir/plen;
		vec3 aabbLen = boxMax - boxMin;
		float plenSq = plen * plen;
		vec3 tminTemp, localInvM = vec3(1.0)/pdirNorm;
		
		vec3 sam = pmin;
		vec3 travelDiff = sam - pmin;
		while (dot(travelDiff, travelDiff) < plenSq)
		{
			ivec3 sampleLoc = ivec3 (clamp ((sam - boxMin) / aabbLen, vec3(0.0), vec3(0.999999)) * vec3(imageSize(grids[nonuniformEXT (gridId)]).xyz));
			vec4 imgFetch = imageLoad (grids[nonuniformEXT (gridId)], sampleLoc);
			if ( imgFetch.a == 0.0 && (uint (imgFetch.b * 255.0) & 0x7F) == 0 ) // Avoid self intersecting emissive particles (i.e. against their own originating AABBs). Non-emissive particles should not have SDF leaves.
			{
				p2 = sam;
				if ( orientedBox ) p2 = (transInfo.leaves[gridId].transMat * vec4 (p2, 1.0)).xyz;
				vec3 voxCentLocal = voxCent = boxMin + (vec3 (sampleLoc) + vec3 (0.5)) * HIGHOMEGA_ZONE_VOXELIZE_COARSENESS;
				if ( orientedBox ) voxCent = (transInfo.leaves[gridId].transMat * vec4 (voxCent, 1.0)).xyz;
				packedMat = imgFetch;
				tminTemp = rayBoxIntersectTMin (sam - pdirNorm, localInvM, voxCentLocal - vec3(HIGHOMEGA_ZONE_VOXELIZE_COARSENESS * 0.5), voxCentLocal + vec3(HIGHOMEGA_ZONE_VOXELIZE_COARSENESS * 0.5));
				outNorm = getBoxNormal (pdirNorm, tminTemp);
				if ( orientedBox ) outNorm = normalize ((DirectionTransform(transInfo.leaves[gridId].transMat) * vec4 (outNorm, 1.0)).xyz);
				return true;
			}
			else
			{
				if (imgFetch.a != 0.0)
					sam += pdirNorm * floor(imgFetch.a * 255.0) * HIGHOMEGA_ZONE_VOXELIZE_COARSENESS * 0.2;
				else
					sam += pdirNorm * HIGHOMEGA_ZONE_VOXELIZE_COARSENESS;
				travelDiff = sam - pmin;
			}
		}
	}
	return false;
}

struct VoxelHit
{
	vec3 color;
	bool specular;
	float emissivity;
	mat3 tanSpace;
	vec3 hitPos;
};

VoxelHit getHit (vec4 packedMat, vec3 hitNorm, vec3 traceDir, vec3 tracePos, vec3 voxCent)
{
	VoxelHit retVal;
	uint packedMatDeNorm = uint (packedMat.b * 255.0);
	retVal.color.r = float(uint(packedMat.g * 255.0) >> 4) / 15.0;
	retVal.color.g = packedMat.r;
	retVal.color.b = float(uint(packedMat.g * 255.0) & 0x0F) / 15.0;
	retVal.color = pow (retVal.color, vec3 (2.2)); // These are stored in gammaspace in the material channels.
	retVal.specular = ((packedMatDeNorm & 0x80) == 0x80) ? true : false;
	retVal.emissivity = (float(packedMatDeNorm & 0x7F) / 127.0) * 25.5;
	retVal.hitPos = tracePos;
	retVal.hitPos += hitNorm * HIGHOMEGA_ZONE_VOXELIZE_COARSENESS * 1.73;
	retVal.tanSpace[2] = hitNorm;
	retVal.tanSpace[0] = normalize (cross (retVal.tanSpace[2], retVal.tanSpace[2] + vec3 (0.1)));
	retVal.tanSpace[1] = cross (retVal.tanSpace[2], retVal.tanSpace[0]);
	return retVal;
}

uint sign_extend_s8x4 (uint i)
{
	uint retVal = ((i & 0x80000000) != 0) ? 0xFF000000 : 0;
	retVal |=    (((i & 0x00800000) != 0) ? 0x00FF0000 : 0);
	retVal |=    (((i & 0x00008000) != 0) ? 0x0000FF00 : 0);
	retVal |=    (((i & 0x00000080) != 0) ? 0x000000FF : 0);
	return retVal;
}

bool LineGridCWBVH (vec3 p1, vec3 p2, out VoxelHit hitProps)
{
	uvec2 traversalStack[12];
	uint hitAddr = 0, stackPtr = 0;
	float tmin = 0.0, tmax = 1.0;
	vec3 rayD = p2 - p1;
	float originalRayLen = length(rayD);
	vec3 invRayD = 1.0 / rayD;
	uint octinv = (7 - ((rayD.x < 0.0 ? 4 : 0) | (rayD.y < 0.0 ? 2 : 0) | (rayD.z < 0.0 ? 1 : 0))) * 0x1010101;
	bool retVal = false;
	vec3 voxCent = vec3 (0.0), outNorm = vec3 (0.0);
	vec4 packedMat = vec4 (0.0);
	uvec2 ngroup = uvec2(0, 0x80000000), tgroup = uvec2(0);
	do
	{
		if (ngroup.y > 0x00FFFFFF)
		{
			uint hits = ngroup.y, imask = ngroup.y;
			uint child_bit_index = findMSB(hits);
			uint child_node_base_index = ngroup.x;
			ngroup.y &= (~(1 << child_bit_index));
			if (ngroup.y > 0x00FFFFFF) { traversalStack[stackPtr++] = ngroup; }
			{
				uint slot_index = (child_bit_index - 24) ^ (octinv & 255);
				uint relative_index = bitCount(imask & (~(0xFFFFFFFF << slot_index)));
				uint child_node_index = child_node_base_index + relative_index;
				uvec4 n0 = CWBVHNodeArr.nodes[child_node_index].n0, n1 = CWBVHNodeArr.nodes[child_node_index].n1;
				uvec4 n2 = CWBVHNodeArr.nodes[child_node_index].n2, n3 = CWBVHNodeArr.nodes[child_node_index].n3;
				uvec4 n4 = CWBVHNodeArr.nodes[child_node_index].n4;
				vec3 p = vec3(uintBitsToFloat(n0.x), uintBitsToFloat(n0.y), uintBitsToFloat(n0.z));
				uvec3 e = uvec3 (bitfieldExtract(n0.w, 0, 8), bitfieldExtract(n0.w, 8, 8), bitfieldExtract(n0.w, 16, 8));
				e = uvec3 ((e.x + 127) & 0xFF, (e.y + 127) & 0xFF, (e.z + 127) & 0xFF); // Kill the sign bit...
				ngroup.x = n1.x; tgroup.x = n1.y; tgroup.y = 0;
				uint hitmask = 0;
				float adjusted_idirx = uintBitsToFloat(e.x << 23u) * invRayD.x;
				float adjusted_idiry = uintBitsToFloat(e.y << 23u) * invRayD.y;
				float adjusted_idirz = uintBitsToFloat(e.z << 23u) * invRayD.z;
				float origx = -(p1.x - p.x) * invRayD.x;
				float origy = -(p1.y - p.y) * invRayD.y;
				float origz = -(p1.z - p.z) * invRayD.z;
				{	// First 4
					uint meta4 = n1.z, is_inner4 = (meta4 & (meta4 << 1)) & 0x10101010;
					uint inner_mask4 = sign_extend_s8x4 (is_inner4 << 3);
					uint bit_index4 = (meta4 ^ (octinv & inner_mask4)) & 0x1F1F1F1F;
					uint child_bits4 = (meta4 >> 5) & 0x07070707;
					uint swizzledLox = (invRayD.x < 0.0) ? n3.z : n2.x, swizzledHix = (invRayD.x < 0.0) ? n2.x : n3.z;
					uint swizzledLoy = (invRayD.y < 0.0) ? n4.x : n2.z, swizzledHiy = (invRayD.y < 0.0) ? n2.z : n4.x;
					uint swizzledLoz = (invRayD.z < 0.0) ? n4.z : n3.x, swizzledHiz = (invRayD.z < 0.0) ? n3.x : n4.z;
					float tminx[4], tminy[4], tminz[4], tmaxx[4], tmaxy[4], tmaxz[4];
					tminx[0] = bitfieldExtract(swizzledLox, 0 , 8) * adjusted_idirx + origx, tminx[1] = bitfieldExtract(swizzledLox, 8 , 8) * adjusted_idirx + origx, tminx[2] = bitfieldExtract(swizzledLox, 16, 8) * adjusted_idirx + origx;
					tminx[3] = bitfieldExtract(swizzledLox, 24, 8) * adjusted_idirx + origx, tminy[0] = bitfieldExtract(swizzledLoy, 0 , 8) * adjusted_idiry + origy, tminy[1] = bitfieldExtract(swizzledLoy, 8 , 8) * adjusted_idiry + origy;
					tminy[2] = bitfieldExtract(swizzledLoy, 16, 8) * adjusted_idiry + origy, tminy[3] = bitfieldExtract(swizzledLoy, 24, 8) * adjusted_idiry + origy, tminz[0] = bitfieldExtract(swizzledLoz, 0 , 8) * adjusted_idirz + origz;
					tminz[1] = bitfieldExtract(swizzledLoz, 8 , 8) * adjusted_idirz + origz, tminz[2] = bitfieldExtract(swizzledLoz, 16, 8) * adjusted_idirz + origz, tminz[3] = bitfieldExtract(swizzledLoz, 24, 8) * adjusted_idirz + origz;
					tmaxx[0] = bitfieldExtract(swizzledHix, 0 , 8) * adjusted_idirx + origx, tmaxx[1] = bitfieldExtract(swizzledHix, 8 , 8) * adjusted_idirx + origx, tmaxx[2] = bitfieldExtract(swizzledHix, 16, 8) * adjusted_idirx + origx;
					tmaxx[3] = bitfieldExtract(swizzledHix, 24, 8) * adjusted_idirx + origx, tmaxy[0] = bitfieldExtract(swizzledHiy, 0 , 8) * adjusted_idiry + origy, tmaxy[1] = bitfieldExtract(swizzledHiy, 8 , 8) * adjusted_idiry + origy;
					tmaxy[2] = bitfieldExtract(swizzledHiy, 16, 8) * adjusted_idiry + origy, tmaxy[3] = bitfieldExtract(swizzledHiy, 24, 8) * adjusted_idiry + origy, tmaxz[0] = bitfieldExtract(swizzledHiz, 0 , 8) * adjusted_idirz + origz;
					tmaxz[1] = bitfieldExtract(swizzledHiz, 8 , 8) * adjusted_idirz + origz, tmaxz[2] = bitfieldExtract(swizzledHiz, 16, 8) * adjusted_idirz + origz, tmaxz[3] = bitfieldExtract(swizzledHiz, 24, 8) * adjusted_idirz + origz;
					for (int i = 0; i < 4; i++)
					{
						// Use VMIN, VMAX to compute the slabs
						float cmin = max(max(max(tminx[i], tminy[i]), tminz[i]), tmin);
						float cmax = min(min(min(tmaxx[i], tmaxy[i]), tmaxz[i]), tmax);
						if (cmin <= cmax) hitmask |= bitfieldExtract(child_bits4, i * 8, 8) << bitfieldExtract(bit_index4, i * 8, 8);
					}
				}
				{	// Second 4
					uint meta4 = n1.w, is_inner4 = (meta4 & (meta4 << 1)) & 0x10101010;
					uint inner_mask4 = sign_extend_s8x4 (is_inner4 << 3);
					uint bit_index4 = (meta4 ^ (octinv & inner_mask4)) & 0x1F1F1F1F;
					uint child_bits4 = (meta4 >> 5) & 0x07070707;
					uint swizzledLox = (invRayD.x < 0.0) ? n3.w : n2.y, swizzledHix = (invRayD.x < 0.0) ? n2.y : n3.w;
					uint swizzledLoy = (invRayD.y < 0.0) ? n4.y : n2.w, swizzledHiy = (invRayD.y < 0.0) ? n2.w : n4.y;
					uint swizzledLoz = (invRayD.z < 0.0) ? n4.w : n3.y, swizzledHiz = (invRayD.z < 0.0) ? n3.y : n4.w;
					float tminx[4], tminy[4], tminz[4], tmaxx[4], tmaxy[4], tmaxz[4];
					tminx[0] = bitfieldExtract(swizzledLox, 0 , 8) * adjusted_idirx + origx, tminx[1] = bitfieldExtract(swizzledLox, 8 , 8) * adjusted_idirx + origx, tminx[2] = bitfieldExtract(swizzledLox, 16, 8) * adjusted_idirx + origx;
					tminx[3] = bitfieldExtract(swizzledLox, 24, 8) * adjusted_idirx + origx, tminy[0] = bitfieldExtract(swizzledLoy, 0 , 8) * adjusted_idiry + origy, tminy[1] = bitfieldExtract(swizzledLoy, 8 , 8) * adjusted_idiry + origy;
					tminy[2] = bitfieldExtract(swizzledLoy, 16, 8) * adjusted_idiry + origy, tminy[3] = bitfieldExtract(swizzledLoy, 24, 8) * adjusted_idiry + origy, tminz[0] = bitfieldExtract(swizzledLoz, 0 , 8) * adjusted_idirz + origz;
					tminz[1] = bitfieldExtract(swizzledLoz, 8 , 8) * adjusted_idirz + origz, tminz[2] = bitfieldExtract(swizzledLoz, 16, 8) * adjusted_idirz + origz, tminz[3] = bitfieldExtract(swizzledLoz, 24, 8) * adjusted_idirz + origz;
					tmaxx[0] = bitfieldExtract(swizzledHix, 0 , 8) * adjusted_idirx + origx, tmaxx[1] = bitfieldExtract(swizzledHix, 8 , 8) * adjusted_idirx + origx, tmaxx[2] = bitfieldExtract(swizzledHix, 16, 8) * adjusted_idirx + origx;
					tmaxx[3] = bitfieldExtract(swizzledHix, 24, 8) * adjusted_idirx + origx, tmaxy[0] = bitfieldExtract(swizzledHiy, 0 , 8) * adjusted_idiry + origy, tmaxy[1] = bitfieldExtract(swizzledHiy, 8 , 8) * adjusted_idiry + origy;
					tmaxy[2] = bitfieldExtract(swizzledHiy, 16, 8) * adjusted_idiry + origy, tmaxy[3] = bitfieldExtract(swizzledHiy, 24, 8) * adjusted_idiry + origy, tmaxz[0] = bitfieldExtract(swizzledHiz, 0 , 8) * adjusted_idirz + origz;
					tmaxz[1] = bitfieldExtract(swizzledHiz, 8 , 8) * adjusted_idirz + origz, tmaxz[2] = bitfieldExtract(swizzledHiz, 16, 8) * adjusted_idirz + origz, tmaxz[3] = bitfieldExtract(swizzledHiz, 24, 8) * adjusted_idirz + origz;
					for (int i = 0; i < 4; i++)
					{
						float cmin = max(max(max(tminx[i], tminy[i]), tminz[i]), tmin);
						float cmax = min(min(min(tmaxx[i], tmaxy[i]), tmaxz[i]), tmax);
						if (cmin <= cmax) hitmask |= bitfieldExtract(child_bits4, i * 8, 8) << bitfieldExtract(bit_index4, i * 8, 8);
					}
				}
				ngroup.y = (hitmask & 0xFF000000) | bitfieldExtract(n0.w, 24, 8);
				tgroup.y = hitmask & 0x00FFFFFF;
			}
		}
		else
		{
			tgroup = ngroup;
			ngroup = uvec2(0);
		}
		while (tgroup.y != 0)
		{
			uint primIndex = findMSB (tgroup.y);
			uint primAddr = tgroup.x + primIndex;
			if (TraceGridNonEmissive(p1, p2, voxCent, GridLeafNodeArr.nodes[primAddr].leafMinMorton.xyz, GridLeafNodeArr.nodes[primAddr].leafMaxLeafId.xyz, floatBitsToUint (GridLeafNodeArr.nodes[primAddr].leafMaxLeafId.a), packedMat, outNorm))
			{
				tmax = length(p2 - p1)/originalRayLen;
				retVal = true;
			}
			tgroup.y -= (1 << primIndex);
		}
		if (ngroup.y <= 0x00FFFFFF)
		{
			if (stackPtr > 0)
			{
				ngroup = traversalStack[--stackPtr];
			}
			else
			{
				break;
			}
		}
	} while (true);
	
	hitProps = getHit (packedMat, outNorm, p2 - p1, p2, voxCent);
	return retVal;
}

float getElasticity()
{
	return float(bitfieldExtract(currentEmitter.params.elasticitySpreadFlags, 24, 8)) / 255.0;
}

float getSpread()
{
	return float(bitfieldExtract(currentEmitter.params.elasticitySpreadFlags, 16, 8)) / 255.0;
}

bool isAffectedByGravity()
{
	return bitfieldExtract(currentEmitter.params.elasticitySpreadFlags, 0, 1) == 1u;
}

bool isOrientedToLinVel()
{
	return bitfieldExtract(currentEmitter.params.elasticitySpreadFlags, 1, 1) == 1u;
}

bool isScaledToLinVel()
{
	return bitfieldExtract(currentEmitter.params.elasticitySpreadFlags, 2, 1) == 1u;
}

bool isRepeating()
{
	return bitfieldExtract(currentEmitter.params.elasticitySpreadFlags, 3, 1) == 1u;
}

vec3 getRand (vec3 forPos)
{
    float rx = fract(sin(dot(forPos, vec3(-9062.9898,  4528.233,  1296.1938))) * 43758.5453);
    float ry = fract(cos(dot(forPos, vec3( 1137.1948,  7670.963, -4424.0687))) * 43758.5453);
    float rz = fract(sin(dot(forPos, vec3( 5649.4233, -3286.248,  4353.5856))) * 93758.5453);
    
    return (vec3 (rx,ry,rz) - vec3 (0.5))* 2.0;
}

vec3 Spin(vec3 axis, vec3 vec, float angle)
{
	vec3 axis_n = normalize(axis);
	float shadow = dot (axis_n, vec);
	vec3 bring_down = shadow * axis_n;
	vec3 plane_pt = vec - bring_down;

	vec3 X = normalize(plane_pt);
	vec3 Y = cross(axis_n, X);

	float pt_x = dot (plane_pt, X);
	float new_pt_x = cos(angle)*pt_x;
	float new_pt_y = sin(angle)*pt_x;

	return ((new_pt_x)*X) + ((new_pt_y)*Y) + bring_down;
}

void main()
{
	if ( gl_GlobalInvocationID.x >= currentEmitter.params.numParticles || currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.a == 0.0 ) return ;

	ParticleItemWide curParticle;
	ReadSourceParticle (curParticle, nonuniformEXT(gl_GlobalInvocationID.y), gl_GlobalInvocationID.x)

	if (isAffectedByGravity())
	{
		vec3 gravity = fromZSignXY (floatBitsToUint(currentEmitter.params.dirGravDirGravLenLinSpeedVar.y)) * currentEmitter.params.dirGravDirGravLenLinSpeedVar.z;
		curParticle.velocity += gravity * currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.a;
	}
	VoxelHit hitProps;
	if ( LineGridCWBVH (curParticle.pos, curParticle.pos + curParticle.velocity * currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.a, hitProps) )
		curParticle.velocity -= dot (hitProps.tanSpace[2], curParticle.velocity) * hitProps.tanSpace[2] * (1.0 + getElasticity());

	curParticle.pos += curParticle.velocity * currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.a;

	vec3 initVelDir = fromZSignXY (floatBitsToUint(currentEmitter.params.dirGravDirGravLenLinSpeedVar.x));
	if (isOrientedToLinVel())
	{
		curParticle.xAxis = normalize (curParticle.velocity);
		vec3 zAxis = cross (curParticle.xAxis, vec3 (0.0, 1.0, 0.0));
		if (zAxis == vec3(0.0)) zAxis = cross (curParticle.xAxis, vec3 (-1.0, 0.0, 0.0));
		curParticle.yAxis = cross (normalize(zAxis), curParticle.xAxis);
	}
	else
	{
		vec3 spinAxis;
		if (abs(initVelDir) != vec3 (1.0, 0.0, 0.0))
		{
			vec3 rotBiVector = normalize (cross (initVelDir, vec3 (1.0, 0.0, 0.0)));
			spinAxis = cross (initVelDir, rotBiVector);
			if (spinAxis.x < 0.0) spinAxis = -spinAxis;
		}
		else
		{
			vec3 rotBiVector = normalize (cross (initVelDir, vec3 (0.0, 0.0, 1.0)));
			spinAxis = cross (initVelDir, rotBiVector);
			if (spinAxis.z < 0.0) spinAxis = -spinAxis;
		}
		curParticle.xAxis = Spin (spinAxis, curParticle.xAxis, curParticle.angSpeed * currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.a);
		curParticle.yAxis = Spin (spinAxis, curParticle.yAxis, curParticle.angSpeed * currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.a);
	}

	curParticle.alphaHealthFadeRateScaleRate.x *= curParticle.alphaHealthFadeRateScaleRate.z;
	curParticle.alphaHealthFadeRateScaleRate.x = max (curParticle.alphaHealthFadeRateScaleRate.x, 1.0 / 255.0);
	curParticle.alphaHealthFadeRateScaleRate.y *= curParticle.deathRate;
	curParticle.scale *= curParticle.alphaHealthFadeRateScaleRate.w;

	if (isRepeating() && curParticle.alphaHealthFadeRateScaleRate.y < 0.05)
	{
		vec3 randVec = getRand (curParticle.pos.xyz);
		vec3 randVec2 = getRand (curParticle.pos.xyz + randVec * 30.0);
		vec3 randVecNorm = (randVec + vec3 (1.0)) * 0.5;
		vec3 randVec2Norm = (randVec2 + vec3 (1.0)) * 0.5;
		curParticle.pos = currentEmitter.params.posLinSpeedBase.xyz + normalize (cross(initVelDir, randVec)) * currentEmitter.params.radAngSpeedBaseAngSpeedVarFadeRateBase.x;
		curParticle.velocity = normalize (initVelDir + getSpread() * randVec) * (currentEmitter.params.posLinSpeedBase.a + currentEmitter.params.dirGravDirGravLenLinSpeedVar.a * randVecNorm.x);
		curParticle.xAxis = normalize (randVec);
		curParticle.yAxis = normalize (cross (randVec, randVec + vec3(0.1)));
		curParticle.alphaHealthFadeRateScaleRate.x = currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.z;
		curParticle.alphaHealthFadeRateScaleRate.y = 1.0f;
		curParticle.alphaHealthFadeRateScaleRate.z = currentEmitter.params.radAngSpeedBaseAngSpeedVarFadeRateBase.a + currentEmitter.params.fadeRateVarScaleRateBaseScaleRateVarDeathRateBase.x * randVecNorm.y;
		curParticle.alphaHealthFadeRateScaleRate.w = currentEmitter.params.fadeRateVarScaleRateBaseScaleRateVarDeathRateBase.y + currentEmitter.params.fadeRateVarScaleRateBaseScaleRateVarDeathRateBase.z * randVecNorm.z;
		curParticle.scale = currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.y;
		curParticle.deathRate = currentEmitter.params.fadeRateVarScaleRateBaseScaleRateVarDeathRateBase.a + currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.x * randVec2Norm.x;
		curParticle.angSpeed = currentEmitter.params.radAngSpeedBaseAngSpeedVarFadeRateBase.y + currentEmitter.params.radAngSpeedBaseAngSpeedVarFadeRateBase.z * randVec2Norm.y;
		curParticle.sizeXAxisToVel = isScaledToLinVel();
	}
	
	StoreParticle (curParticle, nonuniformEXT(gl_GlobalInvocationID.y), gl_GlobalInvocationID.x)
}