/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_ARB_shading_language_420pack : enable

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

struct TransformDataSource
{
	mat4 tran;
};

layout(set = 0, binding = 0) buffer TransformDataSourceSSBO
{
	TransformDataSource mats[];
} sourceMats[];

struct TransformData
{
	mat4 tran;
	mat4 prevTran;
};

layout(set = 1, binding = 0) buffer TransformDataSSBO
{
	TransformData mats[];
} destMats[];

layout (set = 2, binding = 0) buffer IntegrateParamsSSBO
{
	vec4 InstanceCountAmplitudePhaseCurTime;
} integrateParams[];

vec3 Spin(vec3 axis, vec3 vec, float angle)
{
	vec3 axis_n = normalize(axis);
	float shadow = dot (axis_n, vec);
	vec3 bring_down = shadow * axis_n;
	vec3 plane_pt = vec - bring_down;

	vec3 X = normalize(plane_pt);
	vec3 Y = cross(axis_n, X);

	float pt_x = dot (plane_pt, X);
	float new_pt_x = cos(angle)*pt_x;
	float new_pt_y = sin(angle)*pt_x;

	return ((new_pt_x)*X) + ((new_pt_y)*Y) + bring_down;
}

void main()
{
	if ( gl_GlobalInvocationID.x >= floatBitsToUint(integrateParams[nonuniformEXT(gl_GlobalInvocationID.y)].InstanceCountAmplitudePhaseCurTime.x) ) return ;
	
	const vec3 spinAxis = vec3 (0.707106781, 0.0, 0.707106781);
	mat4 itemMat = sourceMats[nonuniformEXT(gl_GlobalInvocationID.y)].mats[gl_GlobalInvocationID.x].tran;
	vec3 itemPos = itemMat[3].xyz;
	float itemDist = dot (itemPos, spinAxis);
	float itemRotate = sin((itemDist + integrateParams[nonuniformEXT(gl_GlobalInvocationID.y)].InstanceCountAmplitudePhaseCurTime.w) * integrateParams[nonuniformEXT(gl_GlobalInvocationID.y)].InstanceCountAmplitudePhaseCurTime.z) * integrateParams[nonuniformEXT(gl_GlobalInvocationID.y)].InstanceCountAmplitudePhaseCurTime.y;
	vec3 xAxis = Spin (spinAxis, itemMat[0].xyz, itemRotate);
	vec3 yAxis = Spin (spinAxis, itemMat[1].xyz, itemRotate);
	vec3 zAxis = Spin (spinAxis, itemMat[2].xyz, itemRotate);
	itemMat[0] = vec4 (xAxis, 0.0);
	itemMat[1] = vec4 (yAxis, 0.0);
	itemMat[2] = vec4 (zAxis, 0.0);
	destMats[nonuniformEXT(gl_GlobalInvocationID.y)].mats[gl_GlobalInvocationID.x].prevTran = destMats[nonuniformEXT(gl_GlobalInvocationID.y)].mats[gl_GlobalInvocationID.x].tran;
	destMats[nonuniformEXT(gl_GlobalInvocationID.y)].mats[gl_GlobalInvocationID.x].tran = itemMat;
}