/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 460

#extension GL_EXT_ray_query : require
#extension GL_EXT_ray_flags_primitive_culling : require
#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_shader_8bit_storage : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_shader_explicit_arithmetic_types_float16 : require

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

struct ParticleItemWide
{
	vec3 pos;
	vec3 velocity;
	vec3 xAxis;
	vec3 yAxis;
	vec4 alphaHealthFadeRateScaleRate;
	float scale;
	float deathRate;
	bool sizeXAxisToVel;
	float prevDeltaT;
	float angSpeed;
};

#define ReadSourceParticle(o,j,k) {o.pos = particles[j].item[k].pos;\
								   o.velocity = fromZSignXY (particles[j].item[k].velocityDir) * unpackHalf2x16(particles[j].item[k].scaleLinSpeed).y;\
								   o.xAxis = fromZSignXY (particles[j].item[k].xAxis);\
								   o.yAxis = fromZSignXY (particles[j].item[k].yAxis);\
								   o.alphaHealthFadeRateScaleRate = vec4(float(uint(particles[j].item[k].alpha))/255.0, float(uint(particles[j].item[k].health))/255.0, float(uint(particles[j].item[k].fadeRate))/255.0, unpackHalf2x16(particles[j].item[k].scaleRateFlagsPrevDeltaT).x);\
								   o.scale = unpackHalf2x16 (particles[j].item[k].scaleLinSpeed).x;\
								   o.deathRate = float(uint(particles[j].item[k].deathRate))/255.0;\
								   o.sizeXAxisToVel = ((particles[j].item[k].scaleRateFlagsPrevDeltaT & 0x0000FF00u) >> 8) == 1u;\
								   o.prevDeltaT = float(particles[j].item[k].scaleRateFlagsPrevDeltaT & 0x000000FFu)/255.0;\
								   o.angSpeed = particles[j].item[k].angSpeed;}

#define StoreParticle(i,j,k) {particles[j].item[k].pos = i.pos;\
							 float STOREPARTICLE_velocityLen = length(i.velocity);\
							 vec3 STOREPARTICLE_velocityNorm = i.velocity;\
							 if (STOREPARTICLE_velocityLen > 0.0) STOREPARTICLE_velocityNorm /= STOREPARTICLE_velocityLen;\
							 particles[j].item[k].velocityDir = toZSignXY (STOREPARTICLE_velocityNorm);\
							 particles[j].item[k].xAxis = toZSignXY (i.xAxis);\
							 particles[j].item[k].yAxis = toZSignXY (i.yAxis);\
							 particles[j].item[k].alpha = uint8_t(uint(i.alphaHealthFadeRateScaleRate.x * 255.0));\
							 particles[j].item[k].health = uint8_t(uint(i.alphaHealthFadeRateScaleRate.y * 255.0));\
							 particles[j].item[k].fadeRate = uint8_t(uint(i.alphaHealthFadeRateScaleRate.z * 255.0));\
							 particles[j].item[k].deathRate = uint8_t(uint(i.deathRate * 255.0));\
							 particles[j].item[k].scaleLinSpeed = packHalf2x16 (vec2(i.scale, STOREPARTICLE_velocityLen));\
							 particles[j].item[k].scaleRateFlagsPrevDeltaT = packHalf2x16 (vec2(i.alphaHealthFadeRateScaleRate.w, uintBitsToFloat(((i.sizeXAxisToVel ? 1u : 0u) << 8) | (uint(ceil(clamp (emitterParams[nonuniformEXT(gl_GlobalInvocationID.y)].params.deathRateVarInitialScaleInitialAlphaCurTime.a, 0.0, 1.0) * 255.0)) & 0x000000FFu))));\
							 particles[j].item[k].angSpeed = i.angSpeed;}

uint toZSignXY(vec3 inpVec)
{
	uint retVal = ((uint((inpVec.x + 1.0) * 16383.0) << 16) | uint((inpVec.y + 1.0) * 32767.0));
	if (inpVec.z < 0.0) retVal |= 0x80000000u;
	return retVal;
}

vec3 fromZSignXY(uint inpPack)
{
	vec3 retVal;
	retVal.x = (float((inpPack & 0x7FFF0000u) >> 16) / 32766.0) * 2.0 - 1.0;
	retVal.y = (float(inpPack & 0x0000FFFFu) / 65534.0) * 2.0 - 1.0;
	vec2 xyVec = vec2(retVal.x, retVal.y);
	retVal.z = sqrt(clamp (1.0 - dot(xyVec, xyVec), 0.0, 1.0));
	if ((inpPack & 0x80000000u) != 0) retVal.z = -retVal.z;
	return retVal;
}

struct ParticleItem
{
	vec3 pos;
	uint velocityDir;
	uint xAxis;
	uint yAxis;
	uint8_t alpha;
	uint8_t health;
	uint8_t fadeRate;
	uint8_t deathRate;
	uint scaleLinSpeed;
	uint scaleRateFlagsPrevDeltaT;
	float angSpeed;
};

layout(scalar, set = 0, binding = 0) buffer ParticlesSSBO
{
	ParticleItem item[];
} particles[];

struct EmitterParams
{
	vec4 posLinSpeedBase;
	vec4 dirGravDirGravLenLinSpeedVar;
	vec4 radAngSpeedBaseAngSpeedVarFadeRateBase;
	vec4 fadeRateVarScaleRateBaseScaleRateVarDeathRateBase;
	vec4 deathRateVarInitialScaleInitialAlphaCurTime;
	uint numParticles;
	uint elasticitySpreadFlags;
};

layout (scalar, set = 1, binding = 0) buffer EmitterParamsSSBO
{
	EmitterParams params;
} emitterParams[];

#define currentEmitter emitterParams[nonuniformEXT(gl_GlobalInvocationID.y)]

layout (set = 2, binding = 0) uniform accelerationStructureEXT topLevelAS;

struct TriangleFromVertBufWide
{
	vec4 e1Col1;
	vec2 uv1;
	uint Norm1;
	vec4 e2Col2;
	vec2 uv2;
	uint Norm2;
	vec4 e3Col3;
	vec2 uv3;
	uint Norm3;
};

#define ReadTri(o,i,j) {uint triCount = giantVB.dat[i];\
						uint offsetToIndices = i + 2, offsetToVertices = 2 + (triCount * 3); offsetToVertices += i + ((24 - ((offsetToVertices * 4) % 24 /* sizeof(RasterVertex) */ )) / 4);\
						uint e1Offset = offsetToVertices + giantVB.dat[offsetToIndices + j * 3] * 6;\
						uint e2Offset = offsetToVertices + giantVB.dat[offsetToIndices + j * 3 + 1] * 6;\
						uint e3Offset = offsetToVertices + giantVB.dat[offsetToIndices + j * 3 + 2] * 6;\
						o.e1Col1 = vec4 (uintBitsToFloat(giantVB.dat[e1Offset]), uintBitsToFloat(giantVB.dat[e1Offset + 1]), uintBitsToFloat(giantVB.dat[e1Offset + 2]), uintBitsToFloat(giantVB.dat[e1Offset + 3]));\
						o.uv1 = unpackHalf2x16(giantVB.dat[e1Offset + 4]);\
						o.Norm1 = giantVB.dat[e1Offset + 5];\
						o.e2Col2 = vec4 (uintBitsToFloat(giantVB.dat[e2Offset]), uintBitsToFloat(giantVB.dat[e2Offset + 1]), uintBitsToFloat(giantVB.dat[e2Offset + 2]), uintBitsToFloat(giantVB.dat[e2Offset + 3]));\
						o.uv2 = unpackHalf2x16(giantVB.dat[e2Offset + 4]);\
						o.Norm2 = giantVB.dat[e2Offset + 5];\
						o.e3Col3 = vec4 (uintBitsToFloat(giantVB.dat[e3Offset]), uintBitsToFloat(giantVB.dat[e3Offset + 1]), uintBitsToFloat(giantVB.dat[e3Offset + 2]), uintBitsToFloat(giantVB.dat[e3Offset + 3]));\
						o.uv3 = unpackHalf2x16(giantVB.dat[e3Offset + 4]);\
						o.Norm3 = giantVB.dat[e3Offset + 5];}

layout(set = 3, binding = 0) uniform sampler2DArray sceneTextures[];

struct InstanceProps
{
	vec3 geomMin;
	vec3 geomMax;
    vec3 attribs1;
    vec4 attribs2;
	uint16_t splatOffset;
	uint16_t diffOffset;
	uint16_t nrmOffset;
	uint16_t rghOffset;
	uint16_t hgtOffset;
	uint16_t spcOffset;
	uint idxVertOffset;
	uint transformOffset;
	uint prevTransformOffset;
};

layout (scalar, set = 4, binding = 0) buffer InstanceInfoSSBO
{
	InstanceProps props[];
} instanceInfo;

layout(scalar, set = 4, binding = 1) buffer GiantVertBuffer
{
	uint dat[];
} giantVB;

layout (set = 4, binding = 2) buffer TransformsSSBO
{
	mat4 mats[];
} transforms;

#define diffuseSampler(i) sceneTextures[nonuniformEXT(instanceInfo.props[i].diffOffset)]
#define normalSampler(i) sceneTextures[nonuniformEXT(instanceInfo.props[i].nrmOffset)]
#define roughnessAndSpecSampler(i) sceneTextures[nonuniformEXT(instanceInfo.props[i].rghOffset)]
#define specularSampler(i) sceneTextures[nonuniformEXT(instanceInfo.props[i].spcOffset)]
#define curInstInfo(i) instanceInfo.props[i]
#define curTransform(i) transforms.mats[instanceInfo.props[i].transformOffset]

float getElasticity()
{
	return float(bitfieldExtract(currentEmitter.params.elasticitySpreadFlags, 24, 8)) / 255.0;
}

float getSpread()
{
	return float(bitfieldExtract(currentEmitter.params.elasticitySpreadFlags, 16, 8)) / 255.0;
}

bool isAffectedByGravity()
{
	return bitfieldExtract(currentEmitter.params.elasticitySpreadFlags, 0, 1) == 1u;
}

bool isOrientedToLinVel()
{
	return bitfieldExtract(currentEmitter.params.elasticitySpreadFlags, 1, 1) == 1u;
}

bool isScaledToLinVel()
{
	return bitfieldExtract(currentEmitter.params.elasticitySpreadFlags, 2, 1) == 1u;
}

bool isRepeating()
{
	return bitfieldExtract(currentEmitter.params.elasticitySpreadFlags, 3, 1) == 1u;
}

vec3 getRand (vec3 forPos)
{
    float rx = fract(sin(dot(forPos, vec3(-9062.9898,  4528.233,  1296.1938))) * 43758.5453);
    float ry = fract(cos(dot(forPos, vec3( 1137.1948,  7670.963, -4424.0687))) * 43758.5453);
    float rz = fract(sin(dot(forPos, vec3( 5649.4233, -3286.248,  4353.5856))) * 93758.5453);
    
    return (vec3 (rx,ry,rz) - vec3 (0.5))* 2.0;
}

vec3 Spin(vec3 axis, vec3 vec, float angle)
{
	vec3 axis_n = normalize(axis);
	float shadow = dot (axis_n, vec);
	vec3 bring_down = shadow * axis_n;
	vec3 plane_pt = vec - bring_down;

	vec3 X = normalize(plane_pt);
	vec3 Y = cross(axis_n, X);

	float pt_x = dot (plane_pt, X);
	float new_pt_x = cos(angle)*pt_x;
	float new_pt_y = sin(angle)*pt_x;

	return ((new_pt_x)*X) + ((new_pt_y)*Y) + bring_down;
}

vec4 sampleDiffuse (uint instanceID, vec2 curUV)
{
	return texture (diffuseSampler(instanceID), vec3 (curUV, 0.0));
}

vec3 sampleTerrainWeights (uint instanceID, vec2 curUV)
{
	vec3 terrainMap = texture (diffuseSampler(instanceID), vec3 (curUV, 3.0)).rgb;
	terrainMap /= (terrainMap.x + terrainMap.y + terrainMap.z);
	return terrainMap;
}

bool getIsDecal (uint packedFlags)
{
	return (packedFlags & 0x00000200) != 0;
}

bool getHolographicInParticleScene (uint packedFlags)
{
	return (packedFlags & 0x00000400) != 0;
}

void main()
{
	if ( gl_GlobalInvocationID.x >= currentEmitter.params.numParticles || currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.a == 0.0 ) return ;

	ParticleItemWide curParticle;
	ReadSourceParticle (curParticle, nonuniformEXT(gl_GlobalInvocationID.y), gl_GlobalInvocationID.x)

	if (isAffectedByGravity())
	{
		vec3 gravity = fromZSignXY (floatBitsToUint(currentEmitter.params.dirGravDirGravLenLinSpeedVar.y)) * currentEmitter.params.dirGravDirGravLenLinSpeedVar.z;
		curParticle.velocity += gravity * currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.a;
	}
	
	rayQueryEXT rayQuery;
	vec3 pDiff = curParticle.velocity * currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.a;
	rayQueryInitializeEXT(rayQuery, topLevelAS, 0, 0xff, curParticle.pos, 0.0, pDiff, 1.0);
	TriangleFromVertBufWide hitTri;
	while(rayQueryProceedEXT(rayQuery))
	{
		if (rayQueryGetIntersectionTypeEXT(rayQuery, false) == gl_RayQueryCandidateIntersectionTriangleEXT)
		{
			uint hitInstID = rayQueryGetIntersectionInstanceCustomIndexEXT(rayQuery, false);
			if (getHolographicInParticleScene(floatBitsToUint (curInstInfo(hitInstID).attribs1.x)) || getIsDecal(floatBitsToUint (curInstInfo(hitInstID).attribs1.x))) continue;
			uint hitPrimID = rayQueryGetIntersectionPrimitiveIndexEXT(rayQuery, false);
			vec2 hitBaryCoord = rayQueryGetIntersectionBarycentricsEXT(rayQuery, false);
			vec3 barycoords = vec3(1.0 - hitBaryCoord.x - hitBaryCoord.y, hitBaryCoord.x, hitBaryCoord.y);
			uint curIdxVertOffset = curInstInfo(hitInstID).idxVertOffset;
			ReadTri (hitTri, curIdxVertOffset, hitPrimID)
			vec3 triE1 = (curTransform(hitInstID) * vec4 (hitTri.e1Col1.xyz, 1.0)).xyz;
			vec3 triE2 = (curTransform(hitInstID) * vec4 (hitTri.e2Col2.xyz, 1.0)).xyz;
			vec3 triE3 = (curTransform(hitInstID) * vec4 (hitTri.e3Col3.xyz, 1.0)).xyz;
			vec2 hitUV = hitTri.uv1 * barycoords.x + hitTri.uv2 * barycoords.y + hitTri.uv3 * barycoords.z;
			vec3 hitPos = triE1 * barycoords.x + triE2 * barycoords.y + triE3 * barycoords.z;
			vec3 curFNorm = normalize (cross (triE1 - triE2, triE3 - triE2));
			vec4 albedoFetch = sampleDiffuse (hitInstID, hitUV);
			if ( albedoFetch.a < 0.1 ) continue;
			rayQueryConfirmIntersectionEXT(rayQuery);
		}
	}
	if (rayQueryGetIntersectionTypeEXT(rayQuery, true) == gl_RayQueryCommittedIntersectionTriangleEXT)
	{
		uint hitInstID = rayQueryGetIntersectionInstanceCustomIndexEXT(rayQuery, true);
		uint hitPrimID = rayQueryGetIntersectionPrimitiveIndexEXT(rayQuery, true);
		uint curIdxVertOffset = curInstInfo(hitInstID).idxVertOffset;
		ReadTri (hitTri, curIdxVertOffset, hitPrimID)
		vec3 triE1 = (curTransform(hitInstID) * vec4 (hitTri.e1Col1.xyz, 1.0)).xyz;
		vec3 triE2 = (curTransform(hitInstID) * vec4 (hitTri.e2Col2.xyz, 1.0)).xyz;
		vec3 triE3 = (curTransform(hitInstID) * vec4 (hitTri.e3Col3.xyz, 1.0)).xyz;
		vec3 curFNorm = normalize (cross (triE1 - triE2, triE3 - triE2));
		curParticle.velocity -= dot (curFNorm, curParticle.velocity) * curFNorm * (1.0 + getElasticity());
	}

	curParticle.pos += curParticle.velocity * currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.a;

	vec3 initVelDir = fromZSignXY (floatBitsToUint(currentEmitter.params.dirGravDirGravLenLinSpeedVar.x));
	if (isOrientedToLinVel())
	{
		curParticle.xAxis = normalize (curParticle.velocity);
		vec3 zAxis = cross (curParticle.xAxis, vec3 (0.0, 1.0, 0.0));
		if (zAxis == vec3(0.0)) zAxis = cross (curParticle.xAxis, vec3 (-1.0, 0.0, 0.0));
		curParticle.yAxis = cross (normalize(zAxis), curParticle.xAxis);
	}
	else
	{
		vec3 spinAxis;
		if (abs(initVelDir) != vec3 (1.0, 0.0, 0.0))
		{
			vec3 rotBiVector = normalize (cross (initVelDir, vec3 (1.0, 0.0, 0.0)));
			spinAxis = cross (initVelDir, rotBiVector);
			if (spinAxis.x < 0.0) spinAxis = -spinAxis;
		}
		else
		{
			vec3 rotBiVector = normalize (cross (initVelDir, vec3 (0.0, 0.0, 1.0)));
			spinAxis = cross (initVelDir, rotBiVector);
			if (spinAxis.z < 0.0) spinAxis = -spinAxis;
		}
		curParticle.xAxis = Spin (spinAxis, curParticle.xAxis, curParticle.angSpeed * currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.a);
		curParticle.yAxis = Spin (spinAxis, curParticle.yAxis, curParticle.angSpeed * currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.a);
	}

	curParticle.alphaHealthFadeRateScaleRate.x *= curParticle.alphaHealthFadeRateScaleRate.z;
	curParticle.alphaHealthFadeRateScaleRate.x = max (curParticle.alphaHealthFadeRateScaleRate.x, 1.0 / 255.0);
	curParticle.alphaHealthFadeRateScaleRate.y *= curParticle.deathRate;
	curParticle.scale *= curParticle.alphaHealthFadeRateScaleRate.w;

	if (isRepeating() && curParticle.alphaHealthFadeRateScaleRate.y < 0.05)
	{
		vec3 randVec = getRand (curParticle.pos.xyz);
		vec3 randVec2 = getRand (curParticle.pos.xyz + randVec * 30.0);
		vec3 randVecNorm = (randVec + vec3 (1.0)) * 0.5;
		vec3 randVec2Norm = (randVec2 + vec3 (1.0)) * 0.5;
		curParticle.pos = currentEmitter.params.posLinSpeedBase.xyz + normalize (cross(initVelDir, randVec)) * currentEmitter.params.radAngSpeedBaseAngSpeedVarFadeRateBase.x;
		curParticle.velocity = normalize (initVelDir + getSpread() * randVec) * (currentEmitter.params.posLinSpeedBase.a + currentEmitter.params.dirGravDirGravLenLinSpeedVar.a * randVecNorm.x);
		curParticle.xAxis = normalize (randVec);
		curParticle.yAxis = normalize (cross (randVec, randVec + vec3(0.1)));
		curParticle.alphaHealthFadeRateScaleRate.x = currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.z;
		curParticle.alphaHealthFadeRateScaleRate.y = 1.0f;
		curParticle.alphaHealthFadeRateScaleRate.z = currentEmitter.params.radAngSpeedBaseAngSpeedVarFadeRateBase.a + currentEmitter.params.fadeRateVarScaleRateBaseScaleRateVarDeathRateBase.x * randVecNorm.y;
		curParticle.alphaHealthFadeRateScaleRate.w = currentEmitter.params.fadeRateVarScaleRateBaseScaleRateVarDeathRateBase.y + currentEmitter.params.fadeRateVarScaleRateBaseScaleRateVarDeathRateBase.z * randVecNorm.z;
		curParticle.scale = currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.y;
		curParticle.deathRate = currentEmitter.params.fadeRateVarScaleRateBaseScaleRateVarDeathRateBase.a + currentEmitter.params.deathRateVarInitialScaleInitialAlphaCurTime.x * randVec2Norm.x;
		curParticle.angSpeed = currentEmitter.params.radAngSpeedBaseAngSpeedVarFadeRateBase.y + currentEmitter.params.radAngSpeedBaseAngSpeedVarFadeRateBase.z * randVec2Norm.y;
		curParticle.sizeXAxisToVel = isScaledToLinVel();
	}
	
	StoreParticle (curParticle, nonuniformEXT(gl_GlobalInvocationID.y), gl_GlobalInvocationID.x)
}