/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_scalar_block_layout : require

layout (local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

shared vec3 minVals[64];
shared vec3 maxVals[64];

struct VertexFromVertBufWide
{
	vec4 eCol;
	vec2 uv;
	uint Norm;
};

#define ReadVertex(v,i,j) {uint triCount = giantVB.dat[i];\
						   uint offsetToVertices = 2 + (triCount * 3); offsetToVertices += i + ((24 - ((offsetToVertices * 4) % 24 /* sizeof(RasterVertex) */ )) / 4);\
						   v.eCol.x = uintBitsToFloat(giantVB.dat[offsetToVertices + (j) * 6]);\
						   v.eCol.y = uintBitsToFloat(giantVB.dat[offsetToVertices + (j) * 6 + 1]);\
						   v.eCol.z = uintBitsToFloat(giantVB.dat[offsetToVertices + (j) * 6 + 2]);\
						   v.eCol.w = uintBitsToFloat(giantVB.dat[offsetToVertices + (j) * 6 + 3]);\
						   v.uv = unpackHalf2x16(giantVB.dat[offsetToVertices + (j) * 6 + 4]);\
						   v.Norm = giantVB.dat[offsetToVertices + (j) * 6 + 5];}

layout(scalar, set = 0, binding = 0) buffer GiantVertBuffer
{
	uint dat[];
} giantVB;

struct MinMaxParams
{
	vec4 minValueIdxVertOffset;
	vec4 maxValueNumVerts;
};

layout(set = 1, binding = 0) buffer ParamsBuffer
{
	MinMaxParams data[];
} params;

void main()
{
	uint vertCount = floatBitsToUint (params.data[gl_WorkGroupID.y].maxValueNumVerts.w);
	uint chunkSize = ((vertCount / 64) + 1);
	if ( gl_LocalInvocationID.x * chunkSize < vertCount )
	{
		uint curChunkStart = gl_LocalInvocationID.x * chunkSize;
		uint curChunkEnd = (gl_LocalInvocationID.x + 1) * chunkSize;
		for (uint i = curChunkStart; i != curChunkEnd; i++)
		{
			if ( i >= vertCount ) break;
			VertexFromVertBufWide curVert;
			ReadVertex (curVert, floatBitsToUint (params.data[gl_WorkGroupID.y].minValueIdxVertOffset.w), i);
			if ( i == curChunkStart )
			{
				maxVals[gl_LocalInvocationID.x] = minVals[gl_LocalInvocationID.x] = curVert.eCol.xyz;
			}
			else
			{
				minVals[gl_LocalInvocationID.x] = min (curVert.eCol.xyz, minVals[gl_LocalInvocationID.x]);
				maxVals[gl_LocalInvocationID.x] = max (curVert.eCol.xyz, maxVals[gl_LocalInvocationID.x]);
			}
		}
	}

	memoryBarrierShared();
	barrier();
	
	vec3 globalMin, globalMax;
	if ( gl_LocalInvocationID.x == 0 )
	{
		[[unroll]]
		for (uint i = 0; i != 64; i++)
		{
			if ( i * chunkSize >= vertCount ) continue;
			if ( i == 0 )
			{
				globalMin = minVals[i];
				globalMax = maxVals[i];
			}
			else
			{
				globalMin = min (globalMin, minVals[i]);
				globalMax = max (globalMax, maxVals[i]);
			}
		}
		params.data[gl_WorkGroupID.y].minValueIdxVertOffset.xyz = globalMin;
		params.data[gl_WorkGroupID.y].maxValueNumVerts.xyz = globalMax;
	}
}