/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_control_flow_attributes : enable
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_scalar_block_layout : require

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

struct TriangleFromVertBufWide
{
	vec4 e1Col1;
	vec2 uv1;
	uint Norm1;
	vec4 e2Col2;
	vec2 uv2;
	uint Norm2;
	vec4 e3Col3;
	vec2 uv3;
	uint Norm3;
};

struct VertexFromVertBufWide
{
	vec4 eCol;
	vec2 uv;
	uint Norm;
};

#define ReadTri(o,i,j) {uint triCount = giantVB.dat[i];\
						uint offsetToIndices = i + 2, offsetToVertices = 2 + (triCount * 3); offsetToVertices += i + ((24 - ((offsetToVertices * 4) % 24 /* sizeof(RasterVertex) */ )) / 4);\
						uint e1Offset = offsetToVertices + giantVB.dat[offsetToIndices + (j) * 3] * 6;\
						uint e2Offset = offsetToVertices + giantVB.dat[offsetToIndices + (j) * 3 + 1] * 6;\
						uint e3Offset = offsetToVertices + giantVB.dat[offsetToIndices + (j) * 3 + 2] * 6;\
						o.e1Col1 = vec4 (uintBitsToFloat(giantVB.dat[e1Offset]), uintBitsToFloat(giantVB.dat[e1Offset + 1]), uintBitsToFloat(giantVB.dat[e1Offset + 2]), uintBitsToFloat(giantVB.dat[e1Offset + 3]));\
						o.uv1 = unpackHalf2x16(giantVB.dat[e1Offset + 4]);\
						o.Norm1 = giantVB.dat[e1Offset + 5];\
						o.e2Col2 = vec4 (uintBitsToFloat(giantVB.dat[e2Offset]), uintBitsToFloat(giantVB.dat[e2Offset + 1]), uintBitsToFloat(giantVB.dat[e2Offset + 2]), uintBitsToFloat(giantVB.dat[e2Offset + 3]));\
						o.uv2 = unpackHalf2x16(giantVB.dat[e2Offset + 4]);\
						o.Norm2 = giantVB.dat[e2Offset + 5];\
						o.e3Col3 = vec4 (uintBitsToFloat(giantVB.dat[e3Offset]), uintBitsToFloat(giantVB.dat[e3Offset + 1]), uintBitsToFloat(giantVB.dat[e3Offset + 2]), uintBitsToFloat(giantVB.dat[e3Offset + 3]));\
						o.uv3 = unpackHalf2x16(giantVB.dat[e3Offset + 4]);\
						o.Norm3 = giantVB.dat[e3Offset + 5];}

#define StoreTriangle(i1,i2,i3,i,j) {uint offsetToIndices = i + 2;\
									 giantVB.dat[offsetToIndices + (j) * 3] = i1;\
									 giantVB.dat[offsetToIndices + (j) * 3 + 1] = i2;\
									 giantVB.dat[offsetToIndices + (j) * 3 + 2] = i3;}

#define StoreVertex(v,i,j) {uint triCount = giantVB.dat[i];\
							uint offsetToVertices = 2 + (triCount * 3); offsetToVertices += i + ((24 - ((offsetToVertices * 4) % 24 /* sizeof(RasterVertex) */ )) / 4);\
							giantVB.dat[offsetToVertices + (j) * 6] = floatBitsToUint(v.eCol.x);\
							giantVB.dat[offsetToVertices + (j) * 6 + 1] = floatBitsToUint(v.eCol.y);\
							giantVB.dat[offsetToVertices + (j) * 6 + 2] = floatBitsToUint(v.eCol.z);\
							giantVB.dat[offsetToVertices + (j) * 6 + 3] = floatBitsToUint(v.eCol.w);\
							giantVB.dat[offsetToVertices + (j) * 6 + 4] = packHalf2x16(v.uv);\
							giantVB.dat[offsetToVertices + (j) * 6 + 5] = v.Norm;}

layout(scalar, binding = 0) buffer GiantVertBuffer
{
	uint dat[];
} giantVB;

layout (binding = 1) uniform sampler2DArray heightMapSampler;

layout (scalar, binding = 2) uniform PrimitiveTessellateUBO
{
	uint sourceTriCount;
	uint trisPerPatch;
	uint sideVertexCount;
	uint vertsPerPatch;
	uint srcIdxVertOffset;
	uint dstIdxVertOffset;
	float displacementAmount;
} primitiveTessellateParams;

uint toZSignXY(vec3 inpVec)
{
	uint retVal = ((uint((inpVec.x + 1.0) * 16383.0) << 16) | uint((inpVec.y + 1.0) * 32767.0));
	if (inpVec.z < 0.0) retVal |= 0x80000000u;
	return retVal;
}

vec3 fromZSignXY(uint inpPack)
{
	vec3 retVal;
	retVal.x = (float((inpPack & 0x7FFF0000u) >> 16) / 32766.0) * 2.0 - 1.0;
	retVal.y = (float(inpPack & 0x0000FFFFu) / 65534.0) * 2.0 - 1.0;
	vec2 xyVec = vec2(retVal.x, retVal.y);
	retVal.z = sqrt(clamp (1.0 - dot(xyVec, xyVec), 0.0, 1.0));
	if ((inpPack & 0x80000000u) != 0) retVal.z = -retVal.z;
	return retVal;
}

void GetTangentBiTangent(vec3 v_0, vec3 v_1, vec3 v_2, vec2 tex0, vec2 tex1, vec2 tex2, out vec3 x_1_out, out vec3 y_1_out)
{
	vec3 A = v_0 - v_1, B = v_2 - v_1;
	vec2 v1 = tex0 - tex1, v2 = tex2 - tex1, v3;
	vec3 origin, x_1, y_1;
	float a, b;

	float v1xv2y_v1yv2x = v1.x*v2.y - v1.y*v2.x;
	float inv_v1xv2y_v1yv2x;
	if (v1xv2y_v1yv2x != 0.0) inv_v1xv2y_v1yv2x = 1.0f / v1xv2y_v1yv2x;

	v3 = -tex1;
	if (v1xv2y_v1yv2x == 0.0)
		a = 1.0;
	else
		a = (v3.x*v2.y - v3.y*v2.x) * inv_v1xv2y_v1yv2x;
	if (v2.x != 0.0)
		b = (v3.x - a * v1.x) / v2.x;
	else
		b = (v3.y - a * v1.y) / v2.y;
	origin = v_1 + a * A + b * B;

	v3 = vec2(1.0, 0.0) - tex1;
	if (v1xv2y_v1yv2x == 0.0)
		a = 1.0;
	else
		a = (v3.x*v2.y - v3.y*v2.x) * inv_v1xv2y_v1yv2x;
	if (v2.x != 0.0)
		b = (v3.x - a * v1.x) / v2.x;
	else
		b = (v3.y - a * v1.y) / v2.y;

	x_1 = v_1 + a * A + b * B;

	v3 = vec2(0.0, 1.0) - tex1;
	if (v1xv2y_v1yv2x == 0.0)
		a = 1.0;
	else
		a = (v3.x*v2.y - v3.y*v2.x) * inv_v1xv2y_v1yv2x;
	if (v2.x != 0.0)
		b = (v3.x - a * v1.x) / v2.x;
	else
		b = (v3.y - a * v1.y) / v2.y;

	y_1 = v_1 + a * A + b * B;

	x_1_out = x_1 - origin;
	y_1_out = y_1 - origin;
}

vec3 Barycentric(vec3 v0, vec3 v1, vec3 v2)
{
	float d00 = dot(v0, v0);
	float d01 = dot(v0, v1);
	float d11 = dot(v1, v1);
	float d20 = dot(v2, v0);
	float d21 = dot(v2, v1);
	float invDenom = 1.0 / (d00 * d11 - d01 * d01);
	vec3 retVal;
	retVal.y = (d11 * d20 - d01 * d21) * invDenom;
	retVal.z = (d00 * d21 - d01 * d20) * invDenom;
	retVal.x = 1.0f - retVal.y - retVal.z;
	return retVal;
}

vec3 sampleTerrainWeights (vec2 inUV)
{
	vec3 terrainMap = texture (heightMapSampler, vec3 (inUV, 3)).rgb;
	terrainMap /= (terrainMap.x + terrainMap.y + terrainMap.z);
	return terrainMap;
}

// https://www.shadertoy.com/view/4djSRW by Dave Hoskins
float hash12(vec2 p)
{
	vec3 p3  = fract(vec3(p.xyx) * .1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}

// iq technique + suslik
// https://iquilezles.org/articles/texturerepetition/
// https://www.shadertoy.com/view/Xtl3zf
void computeDeTileOffsets (vec2 inCoord, out vec4 coordOffsets, out float mixFactor)
{
	inCoord *= 10.0;
	float k00 = hash12(floor(inCoord));
	float k01 = hash12(floor(inCoord) + vec2 (0.0, 1.0));
	float k10 = hash12(floor(inCoord) + vec2 (1.0, 0.0));
	float k11 = hash12(floor(inCoord) + vec2 (1.0, 1.0));
	vec2 inUVFrac = fract(inCoord);
	float k = mix(mix(k00, k01, inUVFrac.y), mix(k10, k11, inUVFrac.y), inUVFrac.x);

	float l = k*8.0;
	mixFactor = fract(l);

	float ia = floor(l+0.5);
	float ib = floor(l);
	mixFactor = min(mixFactor, 1.0-mixFactor)*2.0;

	coordOffsets.xy = sin(vec2(3.0,7.0)*ia);
	coordOffsets.zw = sin(vec2(3.0,7.0)*ib);
}

float sampleHeight (vec3 inpWeights, vec2 inUV, vec3 surfNorm, vec3 inPos, bool isTerrain, vec4 coordOffsets, float mixFactor)
{
	if ( isTerrain )
	{
		vec2 planarUV;
		vec3 absNorm = abs(surfNorm);
		if ( absNorm.y > 0.7 )
			planarUV = inPos.xz;
		else if ( absNorm.x > 0.7 )
			planarUV = inPos.yz;
		else
			planarUV = inPos.xy;
		vec2 curTerrainUV = (planarUV * 33.33333)/vec2 (textureSize (heightMapSampler, 0).xy);
		float retVal = 0.0;

		float colLayer2a = texture(heightMapSampler, vec3 (curTerrainUV + coordOffsets.xy, 2.0)).x;
		float colLayer2b = texture(heightMapSampler, vec3 (curTerrainUV + coordOffsets.zw, 2.0)).x;
		float colLayer2 = mix(colLayer2a, colLayer2b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer2a - colLayer2b)));

		float colLayer1a = texture(heightMapSampler, vec3 (curTerrainUV + coordOffsets.xy, 1.0)).x;
		float colLayer1b = texture(heightMapSampler, vec3 (curTerrainUV + coordOffsets.zw, 1.0)).x;
		float colLayer1 = mix(colLayer1a, colLayer1b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer1a - colLayer1b)));

		float colLayer0a = texture(heightMapSampler, vec3 (curTerrainUV + coordOffsets.xy, 0.0)).x;
		float colLayer0b = texture(heightMapSampler, vec3 (curTerrainUV + coordOffsets.zw, 0.0)).x;
		float colLayer0 = mix(colLayer0a, colLayer0b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer0a - colLayer0b)));

		retVal += colLayer2 * inpWeights.r;
		retVal += colLayer1 * inpWeights.g;
		retVal += colLayer0 * inpWeights.b;
		return retVal * primitiveTessellateParams.displacementAmount;
	}
	return texture (heightMapSampler, vec3 (inUV, 0)).r * primitiveTessellateParams.displacementAmount;
}

void main()
{
	if ( gl_GlobalInvocationID.x >= primitiveTessellateParams.sourceTriCount ) return ;

	uint outputVertsOffset = gl_GlobalInvocationID.x * primitiveTessellateParams.vertsPerPatch;
	uint outputTriIndicesOffset = gl_GlobalInvocationID.x * primitiveTessellateParams.trisPerPatch;

	TriangleFromVertBufWide sourceTri;
	ReadTri (sourceTri, primitiveTessellateParams.srcIdxVertOffset, gl_GlobalInvocationID.x)

	vec3 orig_e2_e1, orig_e3_e1, orig_e1, v1Norm, v2Norm, v3Norm, newVertNorm, Tan, BiTan;
	vec3 u1, u2, v1, v2, u1BC, u2BC, v1BC, v2BC;
	vec2 u1UV, u2UV, v1UV, v2UV;
	vec3 u1MoveOut, u2MoveOut, v1MoveOut, v2MoveOut;
	VertexFromVertBufWide curVert;

	GetTangentBiTangent (sourceTri.e1Col1.xyz, sourceTri.e2Col2.xyz, sourceTri.e3Col3.xyz, sourceTri.uv1, sourceTri.uv2, sourceTri.uv3, Tan, BiTan);
	orig_e2_e1 = sourceTri.e2Col2.xyz - sourceTri.e1Col1.xyz;
	orig_e3_e1 = sourceTri.e3Col3.xyz - sourceTri.e1Col1.xyz;
	orig_e1 = sourceTri.e1Col1.xyz;

	vec4 coordOffsets = vec4(0.0);
	float mixFactor = 0.0;
	bool isTerrain = textureSize (heightMapSampler, 0).z > 1;
	vec3 terrainSampleWeights = vec3(0.0);

	v1Norm = fromZSignXY (sourceTri.Norm1);
	v2Norm = fromZSignXY (sourceTri.Norm2);
	v3Norm = fromZSignXY (sourceTri.Norm3);
	vec3 faceNorm = normalize (cross (sourceTri.e1Col1.xyz - sourceTri.e2Col2.xyz, sourceTri.e3Col3.xyz - sourceTri.e2Col2.xyz));
	vec4 edge1Color = unpackUnorm4x8(floatBitsToUint(sourceTri.e1Col1.w));
	vec4 edge2Color = unpackUnorm4x8(floatBitsToUint(sourceTri.e2Col2.w));
	vec4 edge3Color = unpackUnorm4x8(floatBitsToUint(sourceTri.e3Col3.w));

	int vertCounter = 0;
	for (uint i = 0; i != primitiveTessellateParams.sideVertexCount; i++)
	{
		float sideFraction = float((primitiveTessellateParams.sideVertexCount - 1) - i)/float(primitiveTessellateParams.sideVertexCount - 1);
		vec3 startBaryCoord = mix (vec3 (0.0, 1.0, 0.0) ,vec3 (1.0, 0.0, 0.0), sideFraction);
		vec3 endBaryCoord = mix (vec3 (0.0, 1.0, 0.0) ,vec3 (0.0, 0.0, 1.0), sideFraction);
		uint curMaxMidSteps = primitiveTessellateParams.sideVertexCount - i;
		for (uint j = 0; j != curMaxMidSteps; j++)
		{
			float midFraction = (curMaxMidSteps == 1) ? 0.0 : float(j) / float(curMaxMidSteps - 1);
			vec3 curBaryCoord = mix (startBaryCoord, endBaryCoord, midFraction);
			vec3 curVertNorm = normalize (curBaryCoord.x*v1Norm + curBaryCoord.y*v2Norm + curBaryCoord.z*v3Norm);
			curVert.eCol.xyz = curBaryCoord.x*sourceTri.e1Col1.xyz + curBaryCoord.y*sourceTri.e2Col2.xyz + curBaryCoord.z*sourceTri.e3Col3.xyz;
			curVert.eCol.w = uintBitsToFloat(packUnorm4x8(curBaryCoord.x*edge1Color + curBaryCoord.y*edge2Color + curBaryCoord.z*edge3Color));
			curVert.uv = curBaryCoord.x*sourceTri.uv1 + curBaryCoord.y*sourceTri.uv2 + curBaryCoord.z*sourceTri.uv3;
			
			u1 = curVert.eCol.xyz - 0.05*Tan;
			u2 = curVert.eCol.xyz + 0.05*Tan;
			v1 = curVert.eCol.xyz - 0.05*BiTan;
			v2 = curVert.eCol.xyz + 0.05*BiTan;
			u1BC = Barycentric (orig_e2_e1, orig_e3_e1, u1 - orig_e1);
			u2BC = Barycentric (orig_e2_e1, orig_e3_e1, u2 - orig_e1);
			v1BC = Barycentric (orig_e2_e1, orig_e3_e1, v1 - orig_e1);
			v2BC = Barycentric (orig_e2_e1, orig_e3_e1, v2 - orig_e1);
			u1UV = u1BC.x*sourceTri.uv1 + u1BC.y*sourceTri.uv2 + u1BC.z*sourceTri.uv3;
			u2UV = u2BC.x*sourceTri.uv1 + u2BC.y*sourceTri.uv2 + u2BC.z*sourceTri.uv3;
			v1UV = v1BC.x*sourceTri.uv1 + v1BC.y*sourceTri.uv2 + v1BC.z*sourceTri.uv3;
			v2UV = v2BC.x*sourceTri.uv1 + v2BC.y*sourceTri.uv2 + v2BC.z*sourceTri.uv3;
			u1MoveOut = normalize (u1BC.x*v1Norm + u1BC.y*v2Norm + u1BC.z*v3Norm);
			u2MoveOut = normalize (u2BC.x*v1Norm + u2BC.y*v2Norm + u2BC.z*v3Norm);
			v1MoveOut = normalize (v1BC.x*v1Norm + v1BC.y*v2Norm + v1BC.z*v3Norm);
			v2MoveOut = normalize (v2BC.x*v1Norm + v2BC.y*v2Norm + v2BC.z*v3Norm);
			if ( isTerrain )
			{
				terrainSampleWeights = sampleTerrainWeights (u1UV);
				computeDeTileOffsets (u1UV, coordOffsets, mixFactor);
			}
			u1 += sampleHeight (terrainSampleWeights, u1UV, faceNorm, curVert.eCol.xyz, isTerrain, coordOffsets, mixFactor)*u1MoveOut;
			if ( isTerrain )
			{
				terrainSampleWeights = sampleTerrainWeights (u2UV);
				computeDeTileOffsets (u2UV, coordOffsets, mixFactor);
			}
			u2 += sampleHeight (terrainSampleWeights, u2UV, faceNorm, curVert.eCol.xyz, isTerrain, coordOffsets, mixFactor)*u2MoveOut;
			if ( isTerrain )
			{
				terrainSampleWeights = sampleTerrainWeights (v1UV);
				computeDeTileOffsets (v1UV, coordOffsets, mixFactor);
			}
			v1 += sampleHeight (terrainSampleWeights, v1UV, faceNorm, curVert.eCol.xyz, isTerrain, coordOffsets, mixFactor)*v1MoveOut;
			if ( isTerrain )
			{
				terrainSampleWeights = sampleTerrainWeights (v2UV);
				computeDeTileOffsets (v2UV, coordOffsets, mixFactor);
			}
			v2 += sampleHeight (terrainSampleWeights, v2UV, faceNorm, curVert.eCol.xyz, isTerrain, coordOffsets, mixFactor)*v2MoveOut;
			newVertNorm = normalize (cross (u2 - u1,v2 - v1));
			if ( dot (newVertNorm, curVertNorm) < 0.0 ) newVertNorm = -newVertNorm;
			curVert.Norm = toZSignXY (newVertNorm);
			if ( isTerrain )
			{
				terrainSampleWeights = sampleTerrainWeights (curVert.uv);
				computeDeTileOffsets (curVert.uv, coordOffsets, mixFactor);
			}
			curVert.eCol.xyz += sampleHeight (terrainSampleWeights, curVert.uv, faceNorm, curVert.eCol.xyz, isTerrain, coordOffsets, mixFactor)*curVertNorm;
			
			StoreVertex (curVert, primitiveTessellateParams.dstIdxVertOffset, outputVertsOffset + vertCounter)
			vertCounter++;
		}
	}

	uint triCounter = 0;
	uint currentLevelIndexCount = primitiveTessellateParams.sideVertexCount;
	uint nextLevelIndexCount = currentLevelIndexCount - 1;
	uint currentLevelIndexBase = 0;
	uint nextLevelIndexBase = currentLevelIndexCount;
	do
	{
		uint currentLevelIndex = currentLevelIndexBase;
		uint nextLevelIndex = nextLevelIndexBase;
		for (uint i = 0; i != currentLevelIndexCount - 2; i++)
		{
			StoreTriangle(outputVertsOffset + currentLevelIndex, outputVertsOffset + nextLevelIndex, outputVertsOffset + currentLevelIndex + 1, primitiveTessellateParams.dstIdxVertOffset, outputTriIndicesOffset + triCounter) triCounter++;
			StoreTriangle(outputVertsOffset + nextLevelIndex, outputVertsOffset + nextLevelIndex + 1, outputVertsOffset + currentLevelIndex + 1, primitiveTessellateParams.dstIdxVertOffset, outputTriIndicesOffset + triCounter) triCounter++;
			currentLevelIndex++;
			nextLevelIndex++;
		}
		StoreTriangle(outputVertsOffset + currentLevelIndex, outputVertsOffset + nextLevelIndex, outputVertsOffset + currentLevelIndex + 1, primitiveTessellateParams.dstIdxVertOffset, outputTriIndicesOffset + triCounter) triCounter++;
		currentLevelIndexCount--;
		nextLevelIndexCount--;
		currentLevelIndexBase = nextLevelIndexBase;
		nextLevelIndexBase += currentLevelIndexCount;
	} while (nextLevelIndexCount != 0);
}