/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_scalar_block_layout : require

layout (local_size_x = 32, local_size_y = 1, local_size_z = 1) in;

struct AccelStructInstanceAnalogue // VkAccelerationStructureInstanceKHR
{
	vec4 row1;
	vec4 row2;
	vec4 row3;
	uint instanceMask;
	uint res2;
	uint res3;
	uint res4;
};

layout (scalar, binding = 0) buffer RTInstanceBufferSSBO
{
	AccelStructInstanceAnalogue accelStructInstance[];
} rtInstanceBuffer;

layout (binding = 1) buffer TransformsSSBO
{
	mat4 mats[];
} transforms;

struct InstanceProps
{
	vec3 geomMin;
	vec3 geomMax;
    vec3 attribs1;
    vec4 attribs2;
	uint16_t splatOffset;
	uint16_t diffOffset;
	uint16_t nrmOffset;
	uint16_t rghOffset;
	uint16_t hgtOffset;
	uint16_t spcOffset;
	uint idxVertOffset;
	uint transformOffset;
	uint prevTransformOffset;
};

layout (scalar, binding = 2) buffer InstanceInfoSSBO
{
	InstanceProps props[];
} instanceInfo;

layout (scalar, binding = 3) buffer CopyTransformParamsSSBO
{
	uint nInstances;
} copyTransformParams;

void main()
{
	if ( gl_GlobalInvocationID.x >= copyTransformParams.nInstances ) return ;
	
	uint instanceId = rtInstanceBuffer.accelStructInstance[gl_GlobalInvocationID.x].instanceMask;
	instanceId &= 0x00FFFFFFu;

	mat4 instMat = transforms.mats[instanceInfo.props[instanceId].transformOffset];
	rtInstanceBuffer.accelStructInstance[gl_GlobalInvocationID.x].row1 = vec4 (instMat[0][0], instMat[1][0], instMat[2][0], instMat[3][0]);
	rtInstanceBuffer.accelStructInstance[gl_GlobalInvocationID.x].row2 = vec4 (instMat[0][1], instMat[1][1], instMat[2][1], instMat[3][1]);
	rtInstanceBuffer.accelStructInstance[gl_GlobalInvocationID.x].row3 = vec4 (instMat[0][2], instMat[1][2], instMat[2][2], instMat[3][2]);
}