/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 460
#extension GL_EXT_ray_tracing : require
#extension GL_EXT_scalar_block_layout : require

layout (binding = 0, set = 0) uniform accelerationStructureEXT topLevelAS;
layout (binding = 1, rgba32f) uniform readonly image2D worldPosAttach;

layout (binding = 2, rgba8) uniform writeonly image2D shadowMapScreen;

layout (scalar, binding = 4) uniform SkyShadowMapMVPUBO
{
	mat4 projectionViewMatrix;
	vec4 lookEyeX;
	vec4 upEyeY;
	vec4 sideEyeZ;
	vec2 whrTanHalfFovY;
} SkyShadowMapMVP;

layout(location = 0) rayPayloadEXT vec3 hitValue;

void main() 
{
	vec2 inUV = (vec2 (gl_LaunchIDEXT.xy) + vec2 (0.5)) / vec2(gl_LaunchSizeEXT.xy);
	ivec2 texelCoord =  ivec2 (inUV * vec2(imageSize(worldPosAttach)));
	vec4 fetchedWorldPos = imageLoad(worldPosAttach, texelCoord);

	if ( fetchedWorldPos == vec4 (0.0) )
	{
		imageStore (shadowMapScreen, ivec2 (gl_LaunchIDEXT.xy), vec4 (0.0));
		return ;
	}
	
    uint rayFlags = 0;
    uint cullMask = 0xff;
    float tmin = 0.1;
    float tmax = 1000000.0;
	
	traceRayEXT(topLevelAS, rayFlags, cullMask, 0 , 0 , 0 , fetchedWorldPos.xyz, tmin, -SkyShadowMapMVP.lookEyeX.xyz, tmax, 0 );
	
	imageStore (shadowMapScreen, ivec2 (gl_LaunchIDEXT.xy), vec4 (hitValue, 1.0));
}