/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_scalar_block_layout : require

layout (local_size_x = 8, local_size_y = 4, local_size_z = 1) in;

struct VertexFromVertBufWide
{
	vec4 eCol;
	vec2 uv;
	uint Norm;
};

#define ReadVertex(v,i,j) {uint triCount = giantVB.dat[i];\
						   uint offsetToVertices = 2 + (triCount * 3); offsetToVertices += i + ((24 - ((offsetToVertices * 4) % 24 /* sizeof(RasterVertex) */ )) / 4);\
						   v.eCol.x = uintBitsToFloat(giantVB.dat[offsetToVertices + (j) * 6]);\
						   v.eCol.y = uintBitsToFloat(giantVB.dat[offsetToVertices + (j) * 6 + 1]);\
						   v.eCol.z = uintBitsToFloat(giantVB.dat[offsetToVertices + (j) * 6 + 2]);\
						   v.eCol.w = uintBitsToFloat(giantVB.dat[offsetToVertices + (j) * 6 + 3]);\
						   v.uv = unpackHalf2x16(giantVB.dat[offsetToVertices + (j) * 6 + 4]);\
						   v.Norm = giantVB.dat[offsetToVertices + (j) * 6 + 5];}

#define StoreVertex(v,i,j) {uint triCount = giantVB.dat[i];\
							uint offsetToVertices = 2 + (triCount * 3); offsetToVertices += i + ((24 - ((offsetToVertices * 4) % 24 /* sizeof(RasterVertex) */ )) / 4);\
							giantVB.dat[offsetToVertices + (j) * 6] = floatBitsToUint(v.eCol.x);\
							giantVB.dat[offsetToVertices + (j) * 6 + 1] = floatBitsToUint(v.eCol.y);\
							giantVB.dat[offsetToVertices + (j) * 6 + 2] = floatBitsToUint(v.eCol.z);\
							giantVB.dat[offsetToVertices + (j) * 6 + 3] = floatBitsToUint(v.eCol.w);\
							giantVB.dat[offsetToVertices + (j) * 6 + 4] = packHalf2x16(v.uv);\
							giantVB.dat[offsetToVertices + (j) * 6 + 5] = v.Norm;}

layout(scalar, binding = 0) buffer GiantVertBuffer
{
	uint dat[];
} giantVB;

struct TransformData
{
	mat4 tran;
	mat4 prevTran;
};

layout (set = 1, binding = 0) buffer TransformDataSSBO
{
	TransformData mats[];
} transformData[];

struct TransformParams
{
	uint vertCount;
	uint instanceCount;
	uint geomInstCount;
	uint srcIdxVertOffset;
	uint dstIdxVertOffset;
};

layout (scalar, set = 2, binding = 0) buffer TransformParamsSSBO
{
	TransformParams geomInstParams[];
} transformParams[];

uint toZSignXY(vec3 inpVec)
{
	uint retVal = ((uint((inpVec.x + 1.0) * 16383.0) << 16) | uint((inpVec.y + 1.0) * 32767.0));
	if (inpVec.z < 0.0) retVal |= 0x80000000u;
	return retVal;
}

float packVertexVelocity(vec3 inpVel, float inpPackedColor)
{
	float inpVelLen = length (inpVel);
	vec3 inpVelNorm = inpVel;
	if (inpVelLen != 0.0) inpVelNorm /= inpVelLen;
	uint zSignVelX = uint(clamp (inpVelNorm.x + 1.0, 0.0, 2.0) * 63.5);
	if (inpVelNorm.z < 0.0) zSignVelX |= 0x80;
	uint velY = uint (clamp(inpVelNorm.y + 1.0, 0.0, 2.0) * 127.5);
	uint velLen = clamp (uint(inpVelLen * 10.0), 0, 255);
	
	uint inpPackedColorUint = floatBitsToUint(inpPackedColor);
	inpPackedColorUint &= 0x000000FFu;
	inpPackedColorUint |= (zSignVelX << 8);
	inpPackedColorUint |= (velY << 16);
	inpPackedColorUint |= (velLen << 24);
	return uintBitsToFloat(inpPackedColorUint);
}

vec3 fromZSignXY(uint inpPack)
{
	vec3 retVal;
	retVal.x = (float((inpPack & 0x7FFF0000u) >> 16) / 32766.0) * 2.0 - 1.0;
	retVal.y = (float(inpPack & 0x0000FFFFu) / 65534.0) * 2.0 - 1.0;
	vec2 xyVec = vec2(retVal.x, retVal.y);
	retVal.z = sqrt(clamp (1.0 - dot(xyVec, xyVec), 0.0, 1.0));
	if ((inpPack & 0x80000000u) != 0) retVal.z = -retVal.z;
	return retVal;
}

mat4 DirectionTransform(mat4 transform)
{
	mat4 retVal = mat4(1.0);
	retVal[0].xyz = cross(transform[1].xyz, transform[2].xyz);
	retVal[1].xyz = cross(transform[2].xyz, transform[0].xyz);
	retVal[2].xyz = cross(transform[0].xyz, transform[1].xyz);
	return retVal;
}

void main()
{
	for (uint i = 0; i != transformParams[nonuniformEXT(gl_GlobalInvocationID.z)].geomInstParams[0].geomInstCount; i++)
	{
		if ( any(greaterThanEqual(gl_GlobalInvocationID.xy, uvec2(transformParams[nonuniformEXT(gl_GlobalInvocationID.z)].geomInstParams[i].vertCount, transformParams[nonuniformEXT(gl_GlobalInvocationID.z)].geomInstParams[i].instanceCount))) ) continue ;

		mat4 trans = transformData[nonuniformEXT(gl_GlobalInvocationID.z)].mats[gl_GlobalInvocationID.y].tran;
		mat4 prevTrans = transformData[nonuniformEXT(gl_GlobalInvocationID.z)].mats[gl_GlobalInvocationID.y].prevTran;

		VertexFromVertBufWide sourceVert;
		ReadVertex (sourceVert, transformParams[nonuniformEXT(gl_GlobalInvocationID.z)].geomInstParams[i].srcIdxVertOffset, gl_GlobalInvocationID.x)

		vec3 curEdge = (trans * vec4 (sourceVert.eCol.xyz, 1.0)).xyz;
		vec3 edgeVel = curEdge - (prevTrans * vec4 (sourceVert.eCol.xyz, 1.0)).xyz;
		sourceVert.eCol = vec4 (curEdge, packVertexVelocity(edgeVel, sourceVert.eCol.w));
		sourceVert.Norm = toZSignXY (normalize ((DirectionTransform(trans) * vec4 (fromZSignXY(sourceVert.Norm), 1.0)).xyz));

		StoreVertex (sourceVert, transformParams[nonuniformEXT(gl_GlobalInvocationID.z)].geomInstParams[i].dstIdxVertOffset, transformParams[nonuniformEXT(gl_GlobalInvocationID.z)].geomInstParams[i].vertCount * gl_GlobalInvocationID.y + gl_GlobalInvocationID.x)
	}
}