/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_scalar_block_layout : require
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_control_flow_attributes : enable

#define NUM_THREADS 32
layout (local_size_x = NUM_THREADS, local_size_y = 1, local_size_z = 1) in;

shared uint groupVis;

layout (scalar, binding = 0) uniform cullParamsUBO
{
	vec4 p1;
	vec4 p2;
	vec4 p3;
	vec4 p4;
	uint nInstances;
} cullParams;

layout (scalar, binding = 1) uniform FrameMVPUBO
{
	mat4 projectionViewMatrix;
	vec4 lookEyeX;
	vec4 upEyeY;
	vec4 sideEyeZ;
	vec2 whrTanHalfFovY;
} frameMVP;

struct InstanceProps
{
	vec3 geomMin;
	vec3 geomMax;
    vec3 attribs1;
    vec4 attribs2;
	uint16_t splatOffset;
	uint16_t diffOffset;
	uint16_t nrmOffset;
	uint16_t rghOffset;
	uint16_t hgtOffset;
	uint16_t spcOffset;
	uint idxVertOffset;
	uint transformOffset;
	uint prevTransformOffset;
};

layout (scalar, binding = 2) buffer InstanceInfoSSBO
{
	InstanceProps props[];
} instanceInfo;

struct InstanceCull
{
	uint instId;
	uint indirectBatchId;
	uint indexCount;
	uint firstIndex;
	uint vertexOffset;
};

layout(scalar, binding = 3) buffer InstanceCullBuf
{
	InstanceCull data[];
} instances;

layout(scalar, binding = 4) coherent buffer indirectResultsBuf
{
	uint res[];
} indirectResults;

layout (scalar, binding = 5) buffer TrackedVisSSBO
{
	uint data[];
} trackedVis;

layout (binding = 6) buffer TransformsSSBO
{
	mat4 mats[];
} transforms;

layout (binding = 7) uniform sampler2D depthMipChain[7];

vec3 projectCoord (vec3 coord)
{
	vec4 pCoord = frameMVP.projectionViewMatrix * vec4 (coord - vec3 (frameMVP.lookEyeX.a, frameMVP.upEyeY.a, frameMVP.sideEyeZ.a), 1.0);
	pCoord.xyz = pCoord.xyz/pCoord.w;
	pCoord.xy = (pCoord.xy + vec2 (1.0)) * 0.5;
	if ( pCoord.z > 1.0 ) pCoord.z = 0.0; // Projections behind the viewer will go wild and since there's no near/far clipping, we need this
	return pCoord.xyz;
}

// VkDrawIndexedIndirectCommand == 5 uints
#define SIZE_OF_INDIRECT_COMMAND 5
// sizeof(uint32_t) == 1 uint
#define SIZE_OF_COMMAND_COUNT 1

mat4 DirectionTransform(mat4 transform)
{
	mat4 retVal = mat4(1.0);
	retVal[0].xyz = normalize (cross(transform[1].xyz, transform[2].xyz));
	retVal[1].xyz = normalize (cross(transform[2].xyz, transform[0].xyz));
	retVal[2].xyz = normalize (cross(transform[0].xyz, transform[1].xyz));
	return retVal;
}

void transformCorners(inout vec3 geomMin, inout vec3 geomMax, in mat4 inpMat)
{
	vec3 cent = (geomMin + geomMax) * 0.5f; // Box2D trick from zeuxcg
	vec3 extent = (geomMax - geomMin) * 0.5f;

	mat4 inpMatDT = DirectionTransform(inpMat);
	for (int i = 0; i != 4; i++)
		inpMatDT[i] = abs(inpMatDT[i]);
	cent = (inpMat * vec4 (cent, 1.0)).xyz;
	extent = (inpMatDT * vec4 (extent, 1.0)).xyz;

	geomMin = cent - extent;
	geomMax = cent + extent;
}

void main()
{
	if (gl_LocalInvocationID.x == 0)
	{
		groupVis = trackedVis.data[gl_GlobalInvocationID.x / NUM_THREADS];
	}

	memoryBarrier();
	barrier();

	if ( gl_GlobalInvocationID.x >= cullParams.nInstances ) return ;

	uint instId = instances.data[gl_GlobalInvocationID.x].instId;
	uint transformId = instanceInfo.props[instId].transformOffset;
	vec3 minCoord = instanceInfo.props[instId].geomMin.xyz;
	vec3 maxCoord = instanceInfo.props[instId].geomMax.xyz;
	uint indBatchId = instances.data[gl_GlobalInvocationID.x].indirectBatchId;
	uint indexCount = instances.data[gl_GlobalInvocationID.x].indexCount;
	uint firstIndex = instances.data[gl_GlobalInvocationID.x].firstIndex;
	uint vertexOffset = instances.data[gl_GlobalInvocationID.x].vertexOffset;
	transformCorners (minCoord, maxCoord, transforms.mats[transformId]);

	vec3 c000 = projectCoord (minCoord);
	vec3 c100 = projectCoord (vec3 (maxCoord.x, minCoord.y, minCoord.z));
	vec3 c010 = projectCoord (vec3 (minCoord.x, maxCoord.y, minCoord.z));
	vec3 c110 = projectCoord (vec3 (maxCoord.x, maxCoord.y, minCoord.z));
	vec3 c001 = projectCoord (vec3 (minCoord.x, minCoord.y, maxCoord.z));
	vec3 c101 = projectCoord (vec3 (maxCoord.x, minCoord.y, maxCoord.z));
	vec3 c011 = projectCoord (vec3 (minCoord.x, maxCoord.y, maxCoord.z));
	vec3 c111 = projectCoord (maxCoord);
	vec2 topLeft = min (min (min (c000.xy, c100.xy), min (c010.xy, c110.xy)), min (min (c001.xy, c101.xy), min (c011.xy, c111.xy)));
	vec2 bottomRight = max (max (max (c000.xy, c100.xy), max (c010.xy, c110.xy)), max (max (c001.xy, c101.xy), max (c011.xy, c111.xy)));
	topLeft = clamp (topLeft, vec2 (0.0), vec2 (0.999999));
	bottomRight = clamp (bottomRight, vec2 (0.0), vec2 (0.999999));
	
	float minZ = min (min (min (c000.z, c100.z), min (c010.z, c110.z)), min (min (c001.z, c101.z), min (c011.z, c111.z)));
	bool cullResult = false;
	
	[[unroll]]
	for (int i = 0; i != 7; i++)
	{
		vec2 curMipDim = vec2 (64 >> i);

		if ( curMipDim != vec2 (1.0) )
		{
			ivec2 topLeftTexel = ivec2 (topLeft * curMipDim);
			ivec2 bottomRightTexel = ivec2 (bottomRight * curMipDim);
			if ( topLeftTexel != bottomRightTexel ) continue;
			if ( minZ > texelFetch (depthMipChain[nonuniformEXT(i)], topLeftTexel, 0).x )
				cullResult = true;
			break;
		}
		else
		{
			if ( minZ > texelFetch (depthMipChain[nonuniformEXT(i)], ivec2 (0), 0).x )
				cullResult = true;
			break;
		}
	}

	if (!cullResult && int (groupVis & (1 << gl_LocalInvocationID.x)) == 0)
	{
		uint commandSlot = atomicAdd (indirectResults.res[indBatchId * (SIZE_OF_INDIRECT_COMMAND * cullParams.nInstances + SIZE_OF_COMMAND_COUNT)], 1u);
		uint indirectCommandOffset = indBatchId * (SIZE_OF_INDIRECT_COMMAND * cullParams.nInstances + SIZE_OF_COMMAND_COUNT) + SIZE_OF_COMMAND_COUNT + (commandSlot * SIZE_OF_INDIRECT_COMMAND);
		indirectResults.res[indirectCommandOffset] = indexCount;
		indirectResults.res[indirectCommandOffset + 1] = 1u;
		indirectResults.res[indirectCommandOffset + 2] = firstIndex;
		indirectResults.res[indirectCommandOffset + 3] = vertexOffset;
		indirectResults.res[indirectCommandOffset + 4] = instId;
	}

	if (cullResult)
		atomicAnd (groupVis, ~(1 << gl_LocalInvocationID.x));
	else
		atomicOr (groupVis, 1 << gl_LocalInvocationID.x);

	memoryBarrier();
	barrier();

	if (gl_LocalInvocationID.x == 0)
	{
		trackedVis.data[gl_GlobalInvocationID.x / NUM_THREADS] = groupVis;
	}
}