/*
	Copyright (c) 2026 TooMuchVoltage Software Inc.

	Permission is hereby granted, free of charge, to any person obtaining a copy
	of this software and associated documentation files (the "Software"), to deal
	in the Software without restriction, including without limitation the rights
	to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
	copies of the Software, and to permit persons to whom the Software is
	furnished to do so, subject to the following conditions:

	The above copyright notice and this permission notice shall be included in all
	copies or substantial portions of the Software.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
	AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
	LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
	OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
	SOFTWARE.
*/

#version 450

#extension GL_ARB_separate_shader_objects : enable
#extension GL_ARB_shading_language_420pack : enable
#extension GL_EXT_nonuniform_qualifier : require
#extension GL_EXT_shader_16bit_storage : require
#extension GL_EXT_scalar_block_layout : require

#define NUM_THREADS 32
#define COMP_VOXELIZE_TRI_PER_THREAD 1000
#define HIGHOMEGA_ZONE_VOXELIZE_COARSENESS 1.0

layout (local_size_x = NUM_THREADS, local_size_y = 1, local_size_z = 1) in;

struct InstanceProps
{
	vec3 geomMin;
	vec3 geomMax;
    vec3 attribs1;
    vec4 attribs2;
	uint16_t splatOffset;
	uint16_t diffOffset;
	uint16_t nrmOffset;
	uint16_t rghOffset;
	uint16_t hgtOffset;
	uint16_t spcOffset;
	uint idxVertOffset;
	uint transformOffset;
	uint prevTransformOffset;
};

layout(scalar, binding = 0) uniform voxelizeParamsUBO
{
	vec4 imgMinTriCount;
	vec4 imgMaxVoxelSize;
	InstanceProps instProps;
} voxelizeParams;

layout (binding = 1, rgba8) uniform writeonly image3D voxelizedImage;

struct TriangleFromVertBufWide
{
	vec4 e1Col1;
	vec2 uv1;
	uint Norm1;
	vec4 e2Col2;
	vec2 uv2;
	uint Norm2;
	vec4 e3Col3;
	vec2 uv3;
	uint Norm3;
};

#define ReadTri(o,i,j) {uint triCount = giantVB.dat[i];\
						uint offsetToIndices = i + 2, offsetToVertices = 2 + (triCount * 3); offsetToVertices += i + ((24 - ((offsetToVertices * 4) % 24 /* sizeof(RasterVertex) */ )) / 4);\
						uint e1Offset = offsetToVertices + giantVB.dat[offsetToIndices + j * 3] * 6;\
						uint e2Offset = offsetToVertices + giantVB.dat[offsetToIndices + j * 3 + 1] * 6;\
						uint e3Offset = offsetToVertices + giantVB.dat[offsetToIndices + j * 3 + 2] * 6;\
						o.e1Col1 = vec4 (uintBitsToFloat(giantVB.dat[e1Offset]), uintBitsToFloat(giantVB.dat[e1Offset + 1]), uintBitsToFloat(giantVB.dat[e1Offset + 2]), uintBitsToFloat(giantVB.dat[e1Offset + 3]));\
						o.uv1 = unpackHalf2x16(giantVB.dat[e1Offset + 4]);\
						o.Norm1 = giantVB.dat[e1Offset + 5];\
						o.e2Col2 = vec4 (uintBitsToFloat(giantVB.dat[e2Offset]), uintBitsToFloat(giantVB.dat[e2Offset + 1]), uintBitsToFloat(giantVB.dat[e2Offset + 2]), uintBitsToFloat(giantVB.dat[e2Offset + 3]));\
						o.uv2 = unpackHalf2x16(giantVB.dat[e2Offset + 4]);\
						o.Norm2 = giantVB.dat[e2Offset + 5];\
						o.e3Col3 = vec4 (uintBitsToFloat(giantVB.dat[e3Offset]), uintBitsToFloat(giantVB.dat[e3Offset + 1]), uintBitsToFloat(giantVB.dat[e3Offset + 2]), uintBitsToFloat(giantVB.dat[e3Offset + 3]));\
						o.uv3 = unpackHalf2x16(giantVB.dat[e3Offset + 4]);\
						o.Norm3 = giantVB.dat[e3Offset + 5];}

layout(scalar, set = 0, binding = 2) buffer GiantVertBuffer
{
	uint dat[];
} giantVB;

layout (set = 0, binding = 3) uniform sampler2DArray curDiffuseSampler;
layout (set = 0, binding = 4) uniform sampler2DArray curRoughnessAndSpecSampler;
layout (set = 0, binding = 5) uniform sampler2DArray curSpecularSampler;

vec3 sampleTerrainWeights (vec2 inUV)
{
	vec3 terrainMap = texture (curDiffuseSampler, vec3 (inUV, 3)).rgb;
	terrainMap /= (terrainMap.x + terrainMap.y + terrainMap.z);
	return terrainMap;
}

// https://www.shadertoy.com/view/4djSRW by Dave Hoskins
float hash12(vec2 p)
{
	vec3 p3  = fract(vec3(p.xyx) * .1031);
    p3 += dot(p3, p3.yzx + 33.33);
    return fract((p3.x + p3.y) * p3.z);
}

// iq technique + suslik
// https://iquilezles.org/articles/texturerepetition/
// https://www.shadertoy.com/view/Xtl3zf
void computeDeTileOffsets (vec2 inCoord, out vec4 coordOffsets, out float mixFactor)
{
	inCoord *= 10.0;
	float k00 = hash12(floor(inCoord));
	float k01 = hash12(floor(inCoord) + vec2 (0.0, 1.0));
	float k10 = hash12(floor(inCoord) + vec2 (1.0, 0.0));
	float k11 = hash12(floor(inCoord) + vec2 (1.0, 1.0));
	vec2 inUVFrac = fract(inCoord);
	float k = mix(mix(k00, k01, inUVFrac.y), mix(k10, k11, inUVFrac.y), inUVFrac.x);

	float l = k*8.0;
	mixFactor = fract(l);

	float ia = floor(l+0.5);
	float ib = floor(l);
	mixFactor = min(mixFactor, 1.0-mixFactor)*2.0;

	coordOffsets.xy = sin(vec2(3.0,7.0)*ia);
	coordOffsets.zw = sin(vec2(3.0,7.0)*ib);
}

vec4 sampleDiffuse (vec3 inpWeights, vec2 inUV, vec3 surfNorm, vec3 inPos, bool isTerrain, vec4 coordOffsets, float mixFactor)
{
	int mipTarget = textureQueryLevels(curDiffuseSampler) / 2;
	vec2 diffSize = vec2 (textureSize (curDiffuseSampler, mipTarget).xy);
	if ( isTerrain )
	{
		vec2 planarUV;
		vec3 absNorm = abs(surfNorm);
		if ( absNorm.y > 0.7 )
			planarUV = inPos.xz;
		else if ( absNorm.x > 0.7 )
			planarUV = inPos.yz;
		else
			planarUV = inPos.xy;
		vec2 curTerrainUV = (planarUV * 33.33333)/vec2 (textureSize (curDiffuseSampler, 0).xy);
		vec3 retVal = vec3 (0.0);

		vec3 colLayer2a = texture(curDiffuseSampler, vec3 (curTerrainUV + coordOffsets.xy, 2.0)).xyz;
		vec3 colLayer2b = texture(curDiffuseSampler, vec3 (curTerrainUV + coordOffsets.zw, 2.0)).xyz;
		vec3 colLayer2Diff = colLayer2a - colLayer2b;
		vec3 colLayer2 = mix(colLayer2a, colLayer2b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer2Diff.x + colLayer2Diff.y + colLayer2Diff.z)));

		vec3 colLayer1a = texture(curDiffuseSampler, vec3 (curTerrainUV + coordOffsets.xy, 1.0)).xyz;
		vec3 colLayer1b = texture(curDiffuseSampler, vec3 (curTerrainUV + coordOffsets.zw, 1.0)).xyz;
		vec3 colLayer1Diff = colLayer1a - colLayer1b;
		vec3 colLayer1 = mix(colLayer1a, colLayer1b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer1Diff.x + colLayer1Diff.y + colLayer1Diff.z)));

		vec3 colLayer0a = texture(curDiffuseSampler, vec3 (curTerrainUV + coordOffsets.xy, 0.0)).xyz;
		vec3 colLayer0b = texture(curDiffuseSampler, vec3 (curTerrainUV + coordOffsets.zw, 0.0)).xyz;
		vec3 colLayer0Diff = colLayer0a - colLayer0b;
		vec3 colLayer0 = mix(colLayer0a, colLayer0b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer0Diff.x + colLayer0Diff.y + colLayer0Diff.z)));

		retVal += colLayer2 * inpWeights.r;
		retVal += colLayer1 * inpWeights.g;
		retVal += colLayer0 * inpWeights.b;
		return vec4 (retVal, 1.0);
	}
	return texelFetch (curDiffuseSampler, ivec3 (inUV * diffSize, 0), mipTarget);
}

vec4 sampleSpecular (vec3 inpWeights, vec2 inUV, vec3 surfNorm, vec3 inPos, bool isTerrain, vec4 coordOffsets, float mixFactor)
{
	int mipTarget = textureQueryLevels(curSpecularSampler) / 2;
	vec2 specSize = vec2 (textureSize (curSpecularSampler, mipTarget).xy);
	if ( isTerrain )
	{
		vec2 planarUV;
		vec3 absNorm = abs(surfNorm);
		if ( absNorm.y > 0.7 )
			planarUV = inPos.xz;
		else if ( absNorm.x > 0.7 )
			planarUV = inPos.yz;
		else
			planarUV = inPos.xy;
		vec2 curTerrainUV = (planarUV * 33.33333)/vec2 (textureSize (curSpecularSampler, 0).xy);
		vec3 retVal = vec3 (0.0);

		vec3 colLayer2a = texture(curSpecularSampler, vec3 (curTerrainUV + coordOffsets.xy, 2.0)).xyz;
		vec3 colLayer2b = texture(curSpecularSampler, vec3 (curTerrainUV + coordOffsets.zw, 2.0)).xyz;
		vec3 colLayer2Diff = colLayer2a - colLayer2b;
		vec3 colLayer2 = mix(colLayer2a, colLayer2b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer2Diff.x + colLayer2Diff.y + colLayer2Diff.z)));

		vec3 colLayer1a = texture(curSpecularSampler, vec3 (curTerrainUV + coordOffsets.xy, 1.0)).xyz;
		vec3 colLayer1b = texture(curSpecularSampler, vec3 (curTerrainUV + coordOffsets.zw, 1.0)).xyz;
		vec3 colLayer1Diff = colLayer1a - colLayer1b;
		vec3 colLayer1 = mix(colLayer1a, colLayer1b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer1Diff.x + colLayer1Diff.y + colLayer1Diff.z)));

		vec3 colLayer0a = texture(curSpecularSampler, vec3 (curTerrainUV + coordOffsets.xy, 0.0)).xyz;
		vec3 colLayer0b = texture(curSpecularSampler, vec3 (curTerrainUV + coordOffsets.zw, 0.0)).xyz;
		vec3 colLayer0Diff = colLayer0a - colLayer0b;
		vec3 colLayer0 = mix(colLayer0a, colLayer0b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer0Diff.x + colLayer0Diff.y + colLayer0Diff.z)));

		retVal += colLayer2 * inpWeights.r;
		retVal += colLayer1 * inpWeights.g;
		retVal += colLayer0 * inpWeights.b;
		return vec4 (retVal, 1.0);
	}
	return texelFetch (curSpecularSampler, ivec3 (inUV * specSize, 0), mipTarget);
}

vec4 sampleRoughness (vec3 inpWeights, vec2 inUV, vec3 surfNorm, vec3 inPos, bool isTerrain, vec4 coordOffsets, float mixFactor)
{
	int mipTarget = textureQueryLevels(curRoughnessAndSpecSampler) / 2;
	vec2 roughSize = vec2 (textureSize (curRoughnessAndSpecSampler, mipTarget).xy);
	if ( isTerrain )
	{
		vec2 planarUV;
		vec3 absNorm = abs(surfNorm);
		if ( absNorm.y > 0.7 )
			planarUV = inPos.xz;
		else if ( absNorm.x > 0.7 )
			planarUV = inPos.yz;
		else
			planarUV = inPos.xy;
		vec2 curTerrainUV = (planarUV * 33.33333)/vec2 (textureSize (curRoughnessAndSpecSampler, 0).xy);
		vec3 retVal = vec3 (0.0);

		vec3 colLayer2a = texture(curRoughnessAndSpecSampler, vec3 (curTerrainUV + coordOffsets.xy, 2.0)).xyz;
		vec3 colLayer2b = texture(curRoughnessAndSpecSampler, vec3 (curTerrainUV + coordOffsets.zw, 2.0)).xyz;
		vec3 colLayer2Diff = colLayer2a - colLayer2b;
		vec3 colLayer2 = mix(colLayer2a, colLayer2b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer2Diff.x + colLayer2Diff.y + colLayer2Diff.z)));

		vec3 colLayer1a = texture(curRoughnessAndSpecSampler, vec3 (curTerrainUV + coordOffsets.xy, 1.0)).xyz;
		vec3 colLayer1b = texture(curRoughnessAndSpecSampler, vec3 (curTerrainUV + coordOffsets.zw, 1.0)).xyz;
		vec3 colLayer1Diff = colLayer1a - colLayer1b;
		vec3 colLayer1 = mix(colLayer1a, colLayer1b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer1Diff.x + colLayer1Diff.y + colLayer1Diff.z)));

		vec3 colLayer0a = texture(curRoughnessAndSpecSampler, vec3 (curTerrainUV + coordOffsets.xy, 0.0)).xyz;
		vec3 colLayer0b = texture(curRoughnessAndSpecSampler, vec3 (curTerrainUV + coordOffsets.zw, 0.0)).xyz;
		vec3 colLayer0Diff = colLayer0a - colLayer0b;
		vec3 colLayer0 = mix(colLayer0a, colLayer0b, smoothstep(0.2, 0.8, mixFactor - 0.1 * (colLayer0Diff.x + colLayer0Diff.y + colLayer0Diff.z)));

		retVal += colLayer2 * inpWeights.r;
		retVal += colLayer1 * inpWeights.g;
		retVal += colLayer0 * inpWeights.b;
		return vec4 (retVal, 1.0);
	}
	return texelFetch (curRoughnessAndSpecSampler, ivec3 (inUV * roughSize, 0), mipTarget);
}

vec2 packG8R4B4 (vec3 col)
{
	vec2 retVal;
	retVal.x = col.g;
	retVal.y = (uint(col.r * 15.0) << 4) | uint(col.b * 15.0);
	return vec2 (retVal.x, float(retVal.y) / 255.0);
}

bool getHasRghMap (uint packedFlags)
{
	return (packedFlags & 0x00000002) != 0;
}

bool fetchMaterial (vec2 inUV, vec3 surfNorm, vec3 inPos, out vec4 storeVal)
{
	vec4 coordOffsets = vec4(0.0);
	float mixFactor = 0.0;
	vec3 terrainSampleWeights = vec3 (0.0);
	bool isTerrain = textureSize (curDiffuseSampler, 0).z > 1;
	if ( isTerrain )
	{
		terrainSampleWeights = sampleTerrainWeights (inUV);
		computeDeTileOffsets (inUV, coordOffsets, mixFactor);
	}
	vec4 diffFetch = sampleDiffuse (terrainSampleWeights, inUV, surfNorm, inPos, isTerrain, coordOffsets, mixFactor);
	if ( diffFetch.a < 0.1 ) return false;
	vec4 specFetch = sampleSpecular (terrainSampleWeights, inUV, surfNorm, inPos, isTerrain, coordOffsets, mixFactor);
	vec4 roughFetch = vec4 (1.0, 1.0, 0.0, 1.0);
	if ( getHasRghMap (floatBitsToUint(voxelizeParams.instProps.attribs1.x)) ) roughFetch = sampleRoughness (terrainSampleWeights, inUV, surfNorm, inPos, isTerrain, coordOffsets, mixFactor);
	storeVal.rg = packG8R4B4 (pow ((roughFetch.b > 0.5) ? specFetch.rgb : diffFetch.rgb, vec3(1.0/2.2))); // Bring specular and albedo maps into gamma space before compaction. Heavy discretization darkens them already.
	storeVal.b = float (((roughFetch.b > 0.5) ? 128 : 0) | uint((clamp (voxelizeParams.instProps.attribs1.y, 0.0, 25.5) / 25.5) * 127.0)) / 255.0;
	storeVal.a = diffFetch.a;
	return true;
}

void main()
{
	uint curTriBaseID = gl_WorkGroupID.x * NUM_THREADS * COMP_VOXELIZE_TRI_PER_THREAD;
	if ( curTriBaseID >= floatBitsToUint (voxelizeParams.imgMinTriCount.a) ) return ;

	vec3 aabbLen = voxelizeParams.imgMaxVoxelSize.xyz - voxelizeParams.imgMinTriCount.xyz;
	vec3 voxSize = vec3 (imageSize(voxelizedImage));
	int mipTarget = textureQueryLevels(curDiffuseSampler) / 2;
	vec2 diffSize = vec2 (textureSize (curDiffuseSampler, mipTarget).xy);

	for (int i = 0; i != COMP_VOXELIZE_TRI_PER_THREAD; i++)
	{
		uint curTriID = curTriBaseID + (gl_LocalInvocationID.x * COMP_VOXELIZE_TRI_PER_THREAD) + i;
		if ( curTriID >= floatBitsToUint (voxelizeParams.imgMinTriCount.a) ) return;
		TriangleFromVertBufWide curTri;
		ReadTri (curTri, voxelizeParams.instProps.idxVertOffset, curTriID)

		vec3 e3_e2_norm = normalize (curTri.e3Col3.xyz - curTri.e2Col2.xyz);
		vec3 e1_e2 = curTri.e1Col1.xyz - curTri.e2Col2.xyz;
		vec3 altitudeBase = curTri.e2Col2.xyz + dot (e1_e2, e3_e2_norm) * e3_e2_norm;
		float altitudeLen = length(curTri.e1Col1.xyz - altitudeBase);
		vec3 v3_v1 = curTri.e3Col3.xyz - curTri.e1Col1.xyz;
		vec3 v1_v2 = curTri.e1Col1.xyz - curTri.e2Col2.xyz;
		vec3 v2_v3 = curTri.e2Col2.xyz - curTri.e3Col3.xyz;
		vec3 surfaceNorm = normalize (cross (curTri.e3Col3.xyz - curTri.e2Col2.xyz, curTri.e1Col1.xyz - curTri.e2Col2.xyz));

		float v3_v1_len = length(v3_v1);
		if ( v3_v1_len != 0.0 )
		{
			vec3 v3_v1_norm = v3_v1 / v3_v1_len;
			vec3 curPos = curTri.e1Col1.xyz;
			for (float i = 0.0; i < v3_v1_len; i += HIGHOMEGA_ZONE_VOXELIZE_COARSENESS)
			{
				ivec3 imgLoc = ivec3 (clamp ((curPos - voxelizeParams.imgMinTriCount.xyz) / aabbLen, vec3 (0.0), vec3 (0.999999)) * voxSize);
				vec3 curBary = mix (vec3 (1.0, 0.0, 0.0), vec3 (0.0, 0.0, 1.0), i / v3_v1_len);
				vec2 curUV = clamp (fract (curBary.x * curTri.uv1 + curBary.y * curTri.uv2 + curBary.z * curTri.uv3), vec2 (0.0), vec2 (0.999999));

				vec4 packedMat;
				if ( fetchMaterial (curUV, surfaceNorm, curPos, packedMat) ) imageStore (voxelizedImage, imgLoc, packedMat);
				curPos += v3_v1_norm * HIGHOMEGA_ZONE_VOXELIZE_COARSENESS;
			}
		}
		float v1_v2_len = length(v1_v2);
		if ( v1_v2_len != 0.0 )
		{
			vec3 v1_v2_norm = v1_v2 / v1_v2_len;
			vec3 curPos = curTri.e2Col2.xyz;
			for (float i = 0.0; i < v1_v2_len; i += HIGHOMEGA_ZONE_VOXELIZE_COARSENESS)
			{
				ivec3 imgLoc = ivec3 (clamp ((curPos - voxelizeParams.imgMinTriCount.xyz) / aabbLen, vec3 (0.0), vec3 (0.999999)) * voxSize);
				vec3 curBary = mix (vec3 (0.0, 1.0, 0.0), vec3 (1.0, 0.0, 0.0), i / v1_v2_len);
				vec2 curUV = clamp (fract (curBary.x * curTri.uv1 + curBary.y * curTri.uv2 + curBary.z * curTri.uv3), vec2 (0.0), vec2 (0.999999));

				vec4 packedMat;
				if ( fetchMaterial (curUV, surfaceNorm, curPos, packedMat) ) imageStore (voxelizedImage, imgLoc, packedMat);
				curPos += v1_v2_norm * HIGHOMEGA_ZONE_VOXELIZE_COARSENESS;
			}
		}
		float v2_v3_len = length(v2_v3);
		if ( v2_v3_len != 0.0 )
		{
			vec3 v2_v3_norm = v2_v3 / v2_v3_len;
			vec3 curPos = curTri.e3Col3.xyz;
			for (float i = 0.0; i < v2_v3_len; i += HIGHOMEGA_ZONE_VOXELIZE_COARSENESS)
			{
				ivec3 imgLoc = ivec3 (clamp ((curPos - voxelizeParams.imgMinTriCount.xyz) / aabbLen, vec3 (0.0), vec3 (0.999999)) * voxSize);
				vec3 curBary = mix (vec3 (0.0, 0.0, 1.0), vec3 (0.0, 1.0, 0.0), i / v2_v3_len);
				vec2 curUV = clamp (fract (curBary.x * curTri.uv1 + curBary.y * curTri.uv2 + curBary.z * curTri.uv3), vec2 (0.0), vec2 (0.999999));

				vec4 packedMat;
				if ( fetchMaterial (curUV, surfaceNorm, curPos, packedMat) ) imageStore (voxelizedImage, imgLoc, packedMat);
				curPos += v2_v3_norm * HIGHOMEGA_ZONE_VOXELIZE_COARSENESS;
			}
		}

		for (float i = 0.0; i < altitudeLen; i += HIGHOMEGA_ZONE_VOXELIZE_COARSENESS)
		{
			float frac = i / altitudeLen;
			vec3 startL = curTri.e1Col1.xyz - v1_v2 * frac;
			vec3 endL = curTri.e1Col1.xyz + v3_v1 * frac;
			vec3 lDir = endL - startL;
			float lDirLen = length(lDir);
			if (lDirLen == 0.0) continue;
			vec3 lDirNorm = lDir / lDirLen;
			vec3 startBary = mix (vec3 (1.0, 0.0, 0.0), vec3 (0.0, 1.0, 0.0), frac);
			vec3 endBary = mix (vec3 (1.0, 0.0, 0.0), vec3 (0.0, 0.0, 1.0), frac);
			for (float j = 0.0; j < lDirLen; j += HIGHOMEGA_ZONE_VOXELIZE_COARSENESS)
			{
				vec3 curPos = startL + lDirNorm * j;
				ivec3 imgLoc = ivec3 (clamp ((curPos - voxelizeParams.imgMinTriCount.xyz) / aabbLen, vec3 (0.0), vec3 (0.999999)) * voxSize);
				vec3 curBary = mix (startBary, endBary, j / lDirLen);
				vec2 curUV = clamp (fract (curBary.x * curTri.uv1 + curBary.y * curTri.uv2 + curBary.z * curTri.uv3), vec2 (0.0), vec2 (0.999999));

				vec4 packedMat;
				if ( fetchMaterial (curUV, surfaceNorm, curPos, packedMat) ) imageStore (voxelizedImage, imgLoc, packedMat);
			}
		}
	}
}